-- Rebuilds "3D Design & Animation (Blender)" onto the Course -> Level ->
-- Module -> Lesson model. Level 1 "Blender Foundations" is fully built with
-- real, individually-verified videos and full lesson content
-- (objectives/notes/practice/knowledge-check); Levels 2-9 are scaffolded
-- (title + description only) so the Learning Path shows its full intended
-- shape without pretending content exists that hasn't been researched yet.
--
-- This course has ZERO enrollments (confirmed via direct query before this
-- migration was written), so replacing its old 6-module/12-lesson structure
-- outright is safe -- no learner progress exists to preserve or reset.

delete from public.modules where course_id = 'f0a11b8b-11e0-4af4-999c-ae4c8d3dc0a7';

do $$
declare
  v_course_id uuid := 'f0a11b8b-11e0-4af4-999c-ae4c8d3dc0a7';
  v_level1 uuid; v_level2 uuid; v_level3 uuid; v_level4 uuid; v_level5 uuid;
  v_level6 uuid; v_level7 uuid; v_level8 uuid; v_level9 uuid;
  v_m1 uuid; v_m2 uuid; v_m3 uuid;
begin
  -- ---------------------------------------------------------------------
  -- Levels
  -- ---------------------------------------------------------------------
  insert into public.levels (course_id, title, description, order_number) values
    (v_course_id, 'Blender Foundations', 'Get comfortable navigating Blender''s interface, understand objects and edit mode, and complete your first full project -- the classic donut -- before tackling real modeling work.', 1) returning id into v_level1;
  insert into public.levels (course_id, title, description, order_number) values
    (v_course_id, 'Modeling', 'Core 3D modeling techniques -- box modeling, edit-mode tools, and modeling real objects from furniture to simple characters. Coming soon.', 2) returning id into v_level2;
  insert into public.levels (course_id, title, description, order_number) values
    (v_course_id, 'Materials, Texturing & Shading', 'Blender''s shader node system, PBR materials, UV unwrapping, and texture painting. Coming soon.', 3) returning id into v_level3;
  insert into public.levels (course_id, title, description, order_number) values
    (v_course_id, 'Lighting & Rendering', 'Studio and scene lighting, Cycles vs Eevee, camera composition, and render settings for finished-looking images. Coming soon.', 4) returning id into v_level4;
  insert into public.levels (course_id, title, description, order_number) values
    (v_course_id, 'Animation', 'Keyframes, the timeline and graph editor, and animation principles like easing and timing. Coming soon.', 5) returning id into v_level5;
  insert into public.levels (course_id, title, description, order_number) values
    (v_course_id, 'Rigging & Character Animation', 'Armatures, bones, weight painting, inverse kinematics, and animating a rigged character. Coming soon.', 6) returning id into v_level6;
  insert into public.levels (course_id, title, description, order_number) values
    (v_course_id, 'Advanced 3D Workflow', 'Sculpting, hard-surface modeling, simulations, geometry nodes, and optimizing scenes for performance. Coming soon.', 7) returning id into v_level7;
  insert into public.levels (course_id, title, description, order_number) values
    (v_course_id, 'Real-World Projects', 'End-to-end guided projects -- a game-ready asset, an animated scene, a product visualization -- combining everything learned so far. Coming soon.', 8) returning id into v_level8;
  insert into public.levels (course_id, title, description, order_number) values
    (v_course_id, 'Portfolio & Freelancing', 'Building a portfolio, rendering a demo reel, and finding freelance 3D work. Coming soon.', 9) returning id into v_level9;

  -- ---------------------------------------------------------------------
  -- Level 1 modules
  -- ---------------------------------------------------------------------
  insert into public.modules (course_id, level_id, title, description, order_number) values
    (v_course_id, v_level1, 'Blender Interface & Navigation', 'Install Blender and learn to navigate the 3D viewport, interface panels, object/edit modes, and file saving.', 1) returning id into v_m1;
  insert into public.modules (course_id, level_id, title, description, order_number) values
    (v_course_id, v_level1, 'Basic Transforms & Modifiers', 'Move, rotate, and scale objects precisely, duplicate and instance geometry, and start using non-destructive modifiers.', 2) returning id into v_m2;
  insert into public.modules (course_id, level_id, title, description, order_number) values
    (v_course_id, v_level1, 'Your First Blender Project (The Donut)', 'Apply everything from this level to model, sculpt, texture, light, and render your first complete Blender project.', 3) returning id into v_m3;

  -- ---------------------------------------------------------------------
  -- Module 1: Blender Interface & Navigation
  -- ---------------------------------------------------------------------
  insert into public.lessons (module_id, title, description, youtube_url, order_number, learning_objectives, notes, practice_activity, knowledge_check) values
    (v_m1, 'Installing Blender & First Launch Tour', 'Download and install Blender, then take a guided first look at the default startup screen so it stops feeling overwhelming.', 'https://www.youtube.com/watch?v=JdXhR6S7J5s', 1,
      array['Download and install the correct Blender version for your operating system', 'Identify the main areas of the default startup screen', 'Open, close, and reset Blender''s default layout'],
      'Blender is free, open-source, and available for Windows, macOS, and Linux from blender.org — always download from the official site to avoid bundled junk software some third-party download sites add. On first launch, the default scene contains a cube, a light, and a camera, surrounded by panels that look intimidating at first but break down into a handful of consistent regions you''ll learn one at a time over this level: the 3D Viewport in the center, the Outliner and Properties panels on the right, and the Timeline at the bottom.',
      'Install Blender from blender.org if you haven''t already, open it, and spend five minutes just clicking around the default panels without worrying about breaking anything — Blender''s undo (Ctrl+Z) covers almost everything.',
      '[{"question":"Where should you download Blender from?","options":["Any file-sharing site","blender.org, the official site","A random YouTube link","It doesn''t matter"],"correct_index":1},{"question":"What three objects appear in Blender''s default startup scene?","options":["A sphere, a car, and a tree","A cube, a light, and a camera","Two cubes and a plane","Nothing — it starts empty"],"correct_index":1}]'::jsonb),
    (v_m1, 'Navigating the 3D Viewport', 'Learn to orbit, pan, and zoom around a 3D scene confidently using the mouse and numpad view shortcuts.', 'https://www.youtube.com/watch?v=A6XVDqnZYCY', 2,
      array['Orbit, pan, and zoom the 3D viewport using the mouse', 'Use numpad shortcuts to snap to Front, Side, and Top views', 'Switch between perspective and orthographic view'],
      'Moving around 3D space is the first real skill every Blender user needs before anything else makes sense. Middle-mouse-drag orbits the view, Shift+middle-mouse pans, and the scroll wheel zooms. The numpad gives instant, precise views: 1 for Front, 3 for Side, 7 for Top, and 0 for the camera view — much faster than manually orbiting to check an angle. Perspective view (mimicking how eyes/cameras see, with distant objects appearing smaller) and Orthographic view (no distance distortion, useful for precise modeling) are toggled with Numpad 5.',
      'Practice orbiting, panning, and zooming around the default cube for a few minutes, then use Numpad 1, 3, and 7 to snap between Front, Side, and Top views, and Numpad 5 to toggle Orthographic/Perspective.',
      '[{"question":"What does dragging with the middle mouse button do in the 3D viewport?","options":["Deletes the selected object","Orbits the view around the scene","Opens a menu","Renders the scene"],"correct_index":1},{"question":"Which numpad key snaps the view to Top?","options":["Numpad 1","Numpad 3","Numpad 7","Numpad 0"],"correct_index":2}]'::jsonb),
    (v_m1, 'The Interface: Workspaces, Panels, Outliner, and Properties Editor', 'Tour Blender''s main interface regions — workspaces along the top, the Outliner for scene structure, and the Properties editor for object settings.', 'https://www.youtube.com/watch?v=7MRonzqYJgw', 3,
      array['Identify and switch between Blender''s Workspaces tabs (Layout, Modeling, Shading, etc.)', 'Read and use the Outliner to find and select objects in a scene', 'Navigate the Properties editor''s tabs to find object, material, and render settings'],
      'Blender organizes its huge feature set into Workspaces — tabs along the top (Layout, Modeling, Sculpting, UV Editing, Shading, Animation, Rendering) that each rearrange the screen for a specific task, so you''re not hunting through one giant cluttered interface. The Outliner (top-right by default) lists every object in the scene in a tree structure, letting you click to select things that are hard to click in the viewport. The Properties editor (bottom-right) has a column of small icons down the side — each one is a different settings category (Object, Modifiers, Material, Render, etc.) for whatever''s currently selected.',
      'Click through each Workspace tab along the top of the screen to see how the layout changes, then click through a few icons in the Properties editor''s sidebar to see what settings live under each one.',
      '[{"question":"What do Blender''s Workspace tabs (Layout, Modeling, Shading, etc.) do?","options":["Nothing, they''re just labels","Rearrange the screen''s panels for a specific task","Render the scene","Save the file"],"correct_index":1},{"question":"What does the Outliner show?","options":["Render settings","A tree list of every object in the scene","Material colors","Keyboard shortcuts"],"correct_index":1}]'::jsonb),
    (v_m1, 'Object Mode vs Edit Mode', 'Understand the difference between moving whole objects around (Object Mode) and editing their underlying geometry (Edit Mode).', 'https://www.youtube.com/watch?v=iSHMlLSzsrk', 4,
      array['Switch between Object Mode and Edit Mode using Tab', 'Explain what each mode is used for', 'Select individual vertices, edges, and faces in Edit Mode'],
      'Object Mode treats an object as one solid, movable unit — good for arranging a scene. Edit Mode (toggled with Tab) lets you get inside that object''s actual geometry: its vertices (points), edges (lines connecting points), and faces (surfaces between edges) — this is where real modeling happens, since you''re reshaping the mesh itself rather than just moving it around. The three small icons near the top-left of the viewport in Edit Mode switch between Vertex, Edge, and Face select modes (shortcuts 1, 2, 3).',
      'Select the default cube, press Tab to enter Edit Mode, switch between Vertex/Edge/Face select modes (1/2/3), select a few different vertices, then press Tab again to return to Object Mode.',
      '[{"question":"What does Edit Mode let you do that Object Mode doesn''t?","options":["Change render settings","Select and modify individual vertices, edges, and faces","Add lights","Save the file"],"correct_index":1},{"question":"What shortcut toggles between Object Mode and Edit Mode?","options":["Ctrl+E","Tab","Alt+M","Space"],"correct_index":1}]'::jsonb),
    (v_m1, 'Adding, Deleting, and the 3D Cursor', 'Learn how to add new objects into a scene, delete unwanted ones, and understand what the 3D Cursor controls when adding new geometry.', 'https://www.youtube.com/watch?v=G4FIxBXzDns', 5,
      array['Add new objects to a scene using the Add menu (Shift+A)', 'Delete objects with X or Delete', 'Explain what the 3D Cursor is and how it affects where new objects appear'],
      'Shift+A opens the Add menu anywhere in the 3D viewport, letting you add primitives (cubes, spheres, etc.), lights, cameras, and more. New objects spawn at the 3D Cursor''s position — a small red-and-white striped target icon in the viewport — not necessarily at the world origin, which surprises a lot of beginners the first time an object appears somewhere unexpected. Shift+Right-Click moves the 3D Cursor to a new location; Shift+C resets it to the origin. Selecting an object (left-click) and deleting it (X, then confirm, or Delete) removes it from the scene entirely.',
      'Move the 3D Cursor to a new spot with Shift+Right-Click, add a new object with Shift+A and notice it appears at the cursor, then select and delete it with X.',
      '[{"question":"Where do new objects spawn when added via Shift+A?","options":["Always at the world origin (0,0,0)","At the 3D Cursor''s position","Randomly","Where the camera is pointing"],"correct_index":1},{"question":"What resets the 3D Cursor back to the world origin?","options":["Tab","Shift+C","Ctrl+Z","X"],"correct_index":1}]'::jsonb),
    (v_m1, 'Saving Your Work and Blender''s Auto-Save & File Recovery', 'Save your Blender file properly and understand how Blender''s auto-save and recovery features can rescue your work after a crash.', 'https://www.youtube.com/watch?v=yZiOOiJSYOI', 6,
      array['Save a Blender file with Ctrl+S and understand .blend files', 'Locate and use Blender''s auto-save temp files after an unexpected crash', 'Explain why saving incremental versions of a project is good practice'],
      'Ctrl+S saves your work as a .blend file — Blender''s native project format, containing the entire scene. Beyond manual saving, Blender automatically saves temporary backup copies at a regular interval (configurable in Preferences), which matters a lot the first time an app crashes mid-session: File > Recover > Auto Save lets you reopen the most recent auto-saved state instead of losing everything back to your last manual save. Many working artists also save incremental versions (project_v01.blend, project_v02.blend...) so they can roll back if something goes wrong later in a project.',
      'Save your current file with Ctrl+S, then check Blender''s Preferences > Save & Load settings to see the auto-save interval, and try File > Recover > Auto Save to see what recovery options exist.',
      '[{"question":"What does Ctrl+S do in Blender?","options":["Deletes the scene","Saves the current file as a .blend project","Starts a render","Undoes the last action"],"correct_index":1},{"question":"What can you use to recover work after an unexpected crash?","options":["File > Recover > Auto Save","There is no way to recover lost work","Ctrl+Z only","Restarting always loses everything"],"correct_index":0}]'::jsonb)
  on conflict (module_id, order_number) do nothing;

  -- ---------------------------------------------------------------------
  -- Module 2: Basic Transforms & Modifiers
  -- ---------------------------------------------------------------------
  insert into public.lessons (module_id, title, description, youtube_url, order_number, learning_objectives, notes, practice_activity, knowledge_check) values
    (v_m2, 'Move, Rotate, Scale (G/R/S) and the 3D Cursor', 'Master Blender''s three fundamental transform shortcuts — Grab, Rotate, Scale — the foundation of arranging any 3D scene.', 'https://www.youtube.com/watch?v=qa22WtLufDU', 1,
      array['Move, rotate, and scale objects using G, R, and S', 'Constrain a transform to a single axis (X, Y, or Z)', 'Type an exact numeric value while transforming for precision'],
      'G (Grab/Move), R (Rotate), and S (Scale) are the three most-used shortcuts in all of Blender — you''ll type them thousands of times. Pressing a transform key and then an axis letter (G, then X) constrains the movement to just that axis, which is essential for controlled, predictable edits instead of dragging freehand. You can also type a number right after starting a transform (G, X, then type 2, Enter) to move exactly 2 units — far more precise than eyeballing it with the mouse.',
      'Select an object and practice: G then X then type a number then Enter to move it exactly along X; R then Z then a number to rotate around Z; S then Shift+X to scale on every axis except X.',
      '[{"question":"What does pressing G, then X do?","options":["Rotates around X","Moves the object, constrained to the X axis","Deletes the object","Scales along X"],"correct_index":1},{"question":"How can you move an object exactly 2 units along an axis?","options":["It''s not possible to be precise","Press G, the axis key, type 2, then Enter","Only by dragging with the mouse","Using the render settings"],"correct_index":1}]'::jsonb),
    (v_m2, 'Using Object Properties for Precise Numeric Transforms', 'Use Blender''s Object Properties panel (the N-panel) to type exact position, rotation, and scale values instead of dragging by hand.', 'https://www.youtube.com/watch?v=zXP3Bk5dOpc', 2,
      array['Open the N-panel/sidebar in the 3D viewport', 'Type exact Location, Rotation, and Scale values for a selected object', 'Understand why numeric precision matters for consistent scenes'],
      'Pressing N in the 3D viewport toggles a sidebar showing the selected object''s exact Location, Rotation, and Scale values as editable number fields — the same information the Object Properties tab shows, just available right in the viewport for quick access. Click-dragging a number field changes it freely, or click once and type an exact value for total precision. This matters whenever you need objects lined up exactly (e.g., scale exactly 1.0, rotation exactly 0°) rather than approximately right.',
      'Select an object, press N to open the sidebar, and type exact values into the Location X/Y/Z fields to place it at a precise position.',
      '[{"question":"What shortcut toggles the sidebar showing exact transform values?","options":["Tab","N","G","F12"],"correct_index":1},{"question":"Why would you type an exact number into a transform field instead of dragging?","options":["Dragging is always better","For total precision, e.g. placing something at exactly 0","It renders faster","It''s required to save the file"],"correct_index":1}]'::jsonb),
    (v_m2, 'Duplicating and Instancing Objects', 'Create copies of objects two ways: a full independent duplicate, and a linked instance that stays connected to the original.', 'https://www.youtube.com/watch?v=JlVwzbUFr_k', 3,
      array['Duplicate an object with Shift+D', 'Create a linked instance with Alt+D and explain how it differs from a normal duplicate', 'Decide which type of copy to use for a given situation'],
      'Shift+D duplicates an object completely — the copy has its own independent mesh data, so editing one doesn''t affect the other. Alt+D creates a linked instance instead: the copy shares the same underlying mesh data, so editing the geometry of one instance updates every linked copy at once. Instances are useful for repeated identical elements (like windows on a building) where you want a later edit to apply everywhere at once; independent duplicates are better when copies need to diverge from each other.',
      'Duplicate an object with Shift+D and edit its shape in Edit Mode — notice the original is unaffected. Then create a linked instance with Alt+D of a different object, edit one copy''s mesh, and notice both instances change together.',
      '[{"question":"What''s the key difference between Shift+D and Alt+D?","options":["No difference","Shift+D makes an independent copy; Alt+D makes a linked instance sharing mesh data","Alt+D deletes the object","Shift+D only works in Edit Mode"],"correct_index":1},{"question":"When is a linked instance (Alt+D) most useful?","options":["When copies need to look completely different from each other","When you want repeated identical elements to update together from one edit","Only for lights","Never — it''s rarely used"],"correct_index":1}]'::jsonb),
    (v_m2, 'Introduction to Modifiers and the Non-Destructive Workflow', 'Understand what modifiers are and why applying effects non-destructively (keeping the original mesh editable) is a core Blender workflow habit.', 'https://www.youtube.com/watch?v=F_f-O-W9lMU', 4,
      array['Explain what a modifier is and where to add one', 'Describe what ''non-destructive'' means in a 3D workflow', 'Reorder and adjust a modifier''s settings in the modifier stack'],
      'A modifier is an effect applied on top of an object''s base mesh — like a Subdivision Surface modifier smoothing a low-poly cube — without permanently altering the original geometry underneath. This is the ''non-destructive'' part: you can tweak or remove a modifier''s settings at any time, or turn it off entirely, and the base mesh is still there, unedited. Modifiers stack in an ordered list in the Properties editor''s wrench icon tab, and their order can change the result, so it''s worth understanding what each one does before combining several.',
      'Add a Subdivision Surface modifier to a cube and adjust its Levels Viewport value to see the shape smooth out, then disable the modifier''s visibility eye icon to confirm the original cube underneath is unchanged.',
      '[{"question":"What does ''non-destructive'' mean regarding modifiers?","options":["The modifier deletes the original mesh","The original mesh stays intact and editable underneath the modifier''s effect","Modifiers can''t be removed","It means the file can''t be corrupted"],"correct_index":1},{"question":"Where do you find and manage an object''s modifiers?","options":["The Render tab","The Modifier Properties tab (wrench icon)","The Outliner","The Timeline"],"correct_index":1}]'::jsonb),
    (v_m2, 'The Mirror Modifier', 'Use the Mirror modifier to model only half of a symmetrical object and have Blender automatically generate the other half.', 'https://www.youtube.com/watch?v=_YEyik7UQZ8', 5,
      array['Add a Mirror modifier and choose the correct mirror axis', 'Model one half of a symmetrical shape and see it reflected live', 'Use the Clipping option to keep both halves seamlessly joined at the center'],
      'Many real-world objects (faces, vehicles, furniture) are symmetrical, so modeling only half and mirroring it saves significant time and guarantees perfect symmetry. The Mirror modifier reflects an object''s geometry across a chosen axis (X, Y, or Z) in real time as you edit — model changes on one side, the mirrored side updates instantly. Enabling Clipping prevents vertices near the mirror line from drifting apart, keeping the two halves seamlessly connected instead of splitting into a visible gap.',
      'Add a Mirror modifier to a simple object, delete half of its geometry in Edit Mode, and model just that half — watch the mirrored half update automatically, then enable Clipping and test moving a center vertex.',
      '[{"question":"What does the Mirror modifier do?","options":["Deletes half the mesh permanently","Reflects geometry across a chosen axis in real time as you edit","Renders the scene twice","Duplicates the whole object elsewhere in the scene"],"correct_index":1},{"question":"What does the Clipping option prevent?","options":["The object from being deleted","Vertices near the mirror line from drifting apart into a visible gap","The modifier from being removed","The mesh from being scaled"],"correct_index":1}]'::jsonb),
    (v_m2, 'Applying Transforms and Why It Matters', 'Understand why Blender tracks an object''s transform separately from its mesh data, and why applying transforms (Ctrl+A) avoids common beginner bugs.', 'https://www.youtube.com/watch?v=A8byDoKfxMc', 6,
      array['Explain the difference between an object''s mesh data and its transform values', 'Apply Location, Rotation, and Scale with Ctrl+A', 'Recognize symptoms of un-applied transforms (e.g., modifiers behaving unexpectedly)'],
      'Every object in Blender has two separate things: its actual mesh data (the vertices/edges/faces) and a transform (position, rotation, scale) applied on top of that data. Scaling an object to look bigger doesn''t change its underlying mesh — it just multiplies a scale value, which is efficient but can cause confusing bugs later: a Mirror modifier or an Array modifier can behave strangely on an object whose scale isn''t 1.0, 1.0, 1.0. Ctrl+A opens the Apply menu, letting you ''bake'' the current transform values into the mesh data itself and reset the transform to its defaults — a common fix before adding modifiers or exporting a model.',
      'Scale an object non-uniformly, then check its scale values in the N-panel (they won''t be 1,1,1). Apply Ctrl+A > Scale and check again — the values reset to 1,1,1 while the object''s visual size stays the same.',
      '[{"question":"What does Ctrl+A > Apply Scale do?","options":["Deletes the object","Bakes the current scale into the mesh data and resets the scale value to 1","Undoes the last scale","Renders the object at its current scale"],"correct_index":1},{"question":"Why can un-applied transforms cause problems with modifiers like Mirror?","options":["They never cause problems","Some modifiers assume a default (1,1,1) scale/rotation and behave unexpectedly otherwise","Modifiers ignore transforms entirely","It only affects render time"],"correct_index":1}]'::jsonb)
  on conflict (module_id, order_number) do nothing;

  -- ---------------------------------------------------------------------
  -- Module 3: Your First Blender Project (The Donut)
  -- ---------------------------------------------------------------------
  insert into public.lessons (module_id, title, description, youtube_url, order_number, learning_objectives, notes, practice_activity, knowledge_check) values
    (v_m3, 'Modeling a Simple Donut Shape', 'Build the base donut mesh from a torus, then reshape it in Edit Mode so it looks hand-made rather than a perfect geometric ring.', 'https://www.youtube.com/watch?v=tBpnKTAc5Eo', 1,
      array['Add a torus primitive and adjust its major/minor segments and radius', 'Use proportional editing to give the donut an irregular, hand-made shape', 'Apply a Subdivision Surface modifier for a smooth final mesh'],
      'Every 3D model starts from a primitive shape — a cube, sphere, or in this case a torus (a ring/donut shape). Blender lets you tweak a primitive''s settings right after adding it (segment count, radius) in the operator panel at the bottom-left of the viewport. Real donuts aren''t perfectly symmetrical, so proportional editing (O key) lets you nudge vertices with a falloff, deforming a wide area smoothly instead of one sharp point — that''s what turns a stiff geometric ring into something that reads as food.',
      'Add a torus, adjust its Major/Minor Radius until it looks donut-sized, then use proportional editing (O) to gently push a few points so the shape looks less perfectly circular.',
      '[{"question":"What primitive shape is the donut modeled from?","options":["Cube","Torus","Sphere","Cylinder"],"correct_index":1},{"question":"What does proportional editing (O) do?","options":["Deletes nearby vertices","Moves selected vertices with a smooth falloff on nearby geometry","Adds a new modifier","Renders the scene"],"correct_index":1}]'::jsonb),
    (v_m3, 'Adding Sprinkles with Geometry Nodes', 'Use Blender''s Geometry Nodes system to scatter sprinkle-shaped objects across the donut''s surface automatically, instead of placing each one by hand.', 'https://www.youtube.com/watch?v=EWTOy5-e4Ns', 2,
      array['Add a Geometry Nodes modifier to an object', 'Use a Distribute Points node to scatter points across a surface', 'Instance a sprinkle mesh onto those points and randomize rotation/scale'],
      'Geometry Nodes is Blender''s node-based system for generating and controlling geometry procedurally — instead of manually duplicating a sprinkle mesh hundreds of times, you build a small network of nodes that generates and places copies automatically, and you can tweak the whole scattering pattern later by adjusting node values instead of redoing manual work. This lesson only needs the basics: distributing points on a surface and instancing an object on those points.',
      'Add a Geometry Nodes modifier to a simple sprinkle-shaped mesh''s surface object, use Distribute Points on Faces, then Instance on Points to scatter copies across the donut icing.',
      '[{"question":"What does the Distribute Points on Faces node do?","options":["Renders the final image","Scatters points across a mesh''s surface","Deletes selected faces","Adds a light source"],"correct_index":1},{"question":"Why use Geometry Nodes for sprinkles instead of manually placing each one?","options":["It''s required by Blender","It lets you generate and adjust hundreds of copies procedurally instead of by hand","It renders faster automatically","It only works on textures"],"correct_index":1}]'::jsonb),
    (v_m3, 'Sculpting Basics for the Icing', 'Enter Sculpt Mode to shape a drippy, uneven icing layer on top of the donut using basic sculpting brushes.', 'https://www.youtube.com/watch?v=--GVNZnSROc', 3,
      array['Switch into Sculpt Mode and understand how it differs from Edit Mode', 'Use the Draw, Smooth, and Grab brushes to shape the icing', 'Adjust brush size and strength for controlled sculpting'],
      'Sculpt Mode treats a mesh more like digital clay: brushes push, pull, and smooth vertices in real time based on where your cursor is, rather than selecting and moving individual vertices/edges like Edit Mode does. A high-resolution mesh (via a Multiresolution or Subdivision modifier) is needed first so there''s enough geometry for the brushes to actually deform. For icing, a soft Draw brush builds up the drip shapes, and the Smooth brush blends everything so it doesn''t look blocky.',
      'Add a Multiresolution modifier and subdivide a few times, then use the Draw and Smooth brushes in Sculpt Mode to push a drippy icing layer over the top of the donut mesh.',
      '[{"question":"What''s the main difference between Sculpt Mode and Edit Mode?","options":["Sculpt Mode only works on materials","Sculpt Mode deforms the mesh with brushes in real time instead of selecting individual vertices","Edit Mode is only for animation","There is no difference"],"correct_index":1},{"question":"Why does sculpting need a high-resolution mesh first?","options":["It doesn''t need one","Brushes need enough geometry/vertices to actually deform detail into","High resolution speeds up rendering","It''s required to add materials"],"correct_index":1}]'::jsonb),
    (v_m3, 'Introduction to Materials and Shaders', 'Create and assign materials for the donut and icing using Blender''s node-based Shader Editor, setting base color and roughness.', 'https://www.youtube.com/watch?v=fsLO1F5x7yM', 4,
      array['Create a new material and assign it to an object', 'Use the Principled BSDF shader''s Base Color and Roughness inputs', 'Understand what roughness controls visually (matte vs shiny surfaces)'],
      'A material defines how a surface looks — its color, how shiny or matte it is, whether it''s transparent, and more. Blender''s default shader, the Principled BSDF, is a single node that covers most realistic materials through a handful of key inputs: Base Color (the surface''s color), Roughness (0 = mirror-like, 1 = fully matte), and others you''ll explore later. For the donut, a warm brown base color with mid-high roughness reads as baked dough; the icing gets a brighter color with lower roughness for a glossier look.',
      'Create two materials — one for the donut base, one for the icing — and assign each to the right part of the mesh, adjusting Base Color and Roughness until they look distinct.',
      '[{"question":"In the Principled BSDF shader, what does Roughness control?","options":["The object''s size","How shiny (low) vs matte (high) a surface looks","The base color","The number of vertices"],"correct_index":1},{"question":"What is a material in Blender?","options":["A type of modifier","A definition of how a surface looks (color, shininess, etc.)","A camera setting","A lighting rig"],"correct_index":1}]'::jsonb),
    (v_m3, 'Basic Lighting Setup', 'Light the donut scene using a simple studio-style setup so the final render looks intentional rather than flat.', 'https://www.youtube.com/watch?v=KO29y5eW61g', 5,
      array['Add and position light sources in a Blender scene', 'Understand the difference between a Point, Sun, and Area light', 'Use light strength and softness to control mood and shadow quality'],
      'Lighting shapes how a 3D scene reads visually — flat, even light makes objects look fake, while a well-placed key light with soft shadows sells realism. Blender offers a few light types: Point (light from a single spot in all directions, like a bulb), Sun (parallel rays, like the actual sun, unaffected by distance), and Area (light from a flat rectangular surface, producing soft, realistic shadows — commonly used for product-style shots like this donut). A simple one- or two-light setup is enough for a small still-life scene.',
      'Add an Area light above and to the side of the donut, adjust its size (larger = softer shadows) and strength until the scene looks well-lit without blowing out highlights.',
      '[{"question":"Which light type produces soft, realistic shadows from a flat surface, commonly used for product shots?","options":["Point light","Sun light","Area light","Spot light"],"correct_index":2},{"question":"What generally makes shadows softer from an Area light?","options":["Increasing its size","Decreasing its size","Changing its color","Moving the camera"],"correct_index":0}]'::jsonb),
    (v_m3, 'Setting Up Your First Render', 'Configure the camera and render settings (Cycles vs Eevee, resolution, samples) to produce your first finished image of the donut.', 'https://www.youtube.com/watch?v=D2rZljDYGdM', 6,
      array['Position and aim a camera at the scene', 'Understand the tradeoff between Cycles (ray-traced, slower, more realistic) and Eevee (real-time, faster)', 'Set resolution and sample count and render a still image'],
      'Blender ships with two render engines with different tradeoffs: Cycles simulates how light actually bounces around a scene (ray tracing), producing very realistic results at the cost of render time; Eevee is a real-time engine that approximates lighting much faster, good for quick previews or stylized work. For a beginner still-life render like this donut, Cycles at a moderate sample count gives a convincing result without an excessive wait. The camera view (Numpad 0) shows exactly what will be rendered, so framing it well before hitting render matters.',
      'Position the camera for a pleasing angle on the donut using Numpad 0 to preview, choose Cycles as the render engine, set a moderate sample count, and render a still image (F12).',
      '[{"question":"What is the key tradeoff between Cycles and Eevee?","options":["Cycles is more realistic but slower; Eevee is faster but less physically accurate","They produce identical results","Eevee is only for animation","Cycles cannot render materials"],"correct_index":0},{"question":"What shortcut renders a still image in Blender?","options":["F9","F12","Ctrl+R","Alt+R"],"correct_index":1}]'::jsonb),
    (v_m3, 'Compositing and Final Touches', 'Use Blender''s Compositor to add finishing touches to the rendered donut image — color grading, glare, and depth of field.', 'https://www.youtube.com/watch?v=nxrEV-OUTEg', 7,
      array['Understand what the Compositor does with a rendered image', 'Add basic color correction and a Glare node for polish', 'Use depth of field to draw focus toward the donut'],
      'Compositing is post-processing applied after the render — much like editing a photo after taking it. Blender''s node-based Compositor lets you adjust color balance, add effects like Glare (soft blooming highlights), and combine render passes for finer control, all without re-rendering the whole scene from scratch. A shallow depth of field (a blurred background, sharp subject) is a simple but effective way to make the donut the clear focal point of the image, mimicking how a real camera lens works.',
      'In the Compositor, add a Glare node to your rendered donut image and adjust a Color Balance node until the final image looks warmer and more polished than the raw render.',
      '[{"question":"What does the Compositor let you do?","options":["Model new geometry","Post-process the rendered image (color, effects) without re-rendering","Rig a character","Add physics simulations"],"correct_index":1},{"question":"What visual effect does a shallow depth of field create?","options":["Everything in focus equally","A blurred background with a sharp subject, drawing focus to it","Faster render times","Brighter colors overall"],"correct_index":1}]'::jsonb)
  on conflict (module_id, order_number) do nothing;
end $$;
