-- Rebuilds "Web Development for Beginners" onto the Course -> Level ->
-- Module -> Lesson model, starting with Level 1 "Foundations".
--
-- The old flat 6-module/20-lesson structure is replaced: it jumped straight
-- into HTML/CSS/JS syntax with no groundwork, and doesn't map onto the level
-- progression (Foundations -> HTML -> CSS -> JavaScript -> Frontend ->
-- Backend & Databases -> APIs/Auth/Security -> Deployment & Projects ->
-- Portfolio & Freelancing). Confirmed safe before writing this: the course
-- has 1 enrollment but ZERO completed lesson_progress rows, so no learner
-- progress is lost.
--
-- The course stays curriculum_status='draft' until all 9 levels are built.

delete from public.modules where course_id = '1ad74fd3-6a25-452c-a4b1-668f8e3be8e6';

-- Auto-generated by scripts/curriculum/build-level-sql.mjs -- do not
-- hand-edit the lesson content below; regenerate from the source plan
-- JSON instead if something needs to change.

do $$
declare
  v_course_id uuid := '1ad74fd3-6a25-452c-a4b1-668f8e3be8e6';
  v_level uuid;
  -- modules.order_number is unique per COURSE, not per level (a course's
  -- modules are numbered continuously across all its levels) -- so this
  -- can't just start at 1 for a level beyond the first. Computed here
  -- instead of hardcoded so this script works correctly regardless of how
  -- many modules the course already has.
  v_module_offset int;
  v_m1 uuid;
  v_m2 uuid;
  v_m3 uuid;
begin
  select coalesce(max(order_number), 0) into v_module_offset
    from public.modules where course_id = v_course_id;

  insert into public.levels (course_id, title, description, order_number) values
    (v_course_id, 'Foundations', 'How the web actually works, the tools every developer uses daily, and the mental models that make everything after this make sense — before writing a line of HTML.', 1)
  returning id into v_level;

  insert into public.modules (course_id, level_id, title, description, order_number) values
    (v_course_id, v_level, 'How the Web Works', 'Before writing a line of code, understand what actually happens between typing a web address and seeing a page — requests, servers, DNS, and how the browser builds what you see.', v_module_offset + 1)
  returning id into v_m1;

  insert into public.lessons (module_id, title, description, youtube_url, order_number, learning_objectives, notes, practice_activity, knowledge_check) values
    (v_m1, 'What Happens When You Visit a Website', 'Follow the whole journey from typing a URL to seeing a page — the request and response cycle that underpins everything else.', 'https://www.youtube.com/watch?v=AlkDbnbv7dk', 1,
      array['Describe the request/response cycle in plain terms', 'Identify the main players: browser, DNS, server, response', 'Explain why a page can load slowly or fail at different points in that chain'],
      'When you type an address and press Enter, a chain of steps runs in well under a second. Your browser first works out which server the domain belongs to (a DNS lookup), opens a connection to that server, and sends an HTTP request asking for the page. The server responds with HTML, and the browser then requests whatever else that HTML references — CSS, JavaScript, images — before assembling everything on screen. Knowing this chain matters practically: when a site is slow or broken, the cause sits at a specific link in it, and being able to name the links is the start of being able to debug them.',
      'Open any website with DevTools'' Network tab open (F12 → Network), reload the page, and count how many separate requests the browser makes to build that one page.',
      '[{"question":"What does the browser do first when you enter a web address?","options":["Downloads all the images","Looks up which server the domain belongs to (DNS)","Runs the JavaScript","Prints the page"],"correct_index":1},{"question":"What does the server send back in response to a page request?","options":["Only images","HTML, which may reference further CSS, JS, and images","A finished screenshot of the page","Nothing until you click something"],"correct_index":1}]'::jsonb),
    (v_m1, 'How the Internet Works: Clients, Servers, and Networks', 'The client-server relationship underneath every website — who asks, who answers, and how those machines find each other at all.', 'https://www.youtube.com/watch?v=zN8YNNHcaZc', 2,
      array['Define client and server and give an example of each', 'Explain what an IP address does', 'Describe at a high level how data travels between networks'],
      'Almost everything on the web runs on a client-server model. The client is whatever asks for something — your browser, your phone app. The server is a computer that stays running to answer those requests. Each machine on a network has an IP address, which functions like a postal address so data knows where to go, and data itself travels in small packets that get reassembled at the other end. As a web developer you will eventually write both sides: the frontend that runs on the client, and the backend that runs on the server, which is exactly how the later levels of this Learning Path are structured.',
      'Write down three things acting as a client in your own daily life (apps, browsers) and one thing acting as a server, then explain in a sentence what each one asks for or provides.',
      '[{"question":"In the client-server model, what is the client?","options":["The machine that stays running to answer requests","Whatever asks for something, like your browser","The internet cable","A type of database"],"correct_index":1},{"question":"What is an IP address for?","options":["Storing passwords","Identifying a machine on a network so data can reach it","Making pages load faster","Encrypting traffic"],"correct_index":1}]'::jsonb),
    (v_m1, 'Domains, DNS, and Web Hosting', 'How a human-friendly domain name gets connected to an actual server, and what web hosting really means when you go to publish your own site.', 'https://www.youtube.com/watch?v=3xC7GdgziV0', 3,
      array['Explain what a domain name is and how it maps to an IP address', 'Describe what DNS does in that process', 'Explain what web hosting provides and why you need it to publish a site'],
      'A domain name like example.com exists because people cannot remember IP addresses. DNS is the system that translates the name into the address — effectively the phone book of the internet. Hosting is separate from the domain: the domain is the address, the host is the actual land and building where your files live. To put a site online you generally need both, plus DNS records pointing your domain at your host. This becomes concrete in Level 8, when you deploy a real project — but it''s worth understanding the three-way relationship now, because it''s the single most common point of confusion for people publishing their first site.',
      'Search for a domain name you might want and check its price at any registrar, then look up what an ''A record'' does in DNS and write a one-sentence explanation.',
      '[{"question":"What does DNS do?","options":["Hosts your website''s files","Translates domain names into IP addresses","Encrypts your traffic","Designs your web pages"],"correct_index":1},{"question":"What is web hosting?","options":["The name people type to reach your site","A service providing the server space where your site''s files actually live","A type of DNS record","The browser you use"],"correct_index":1}]'::jsonb),
    (v_m1, 'How Browsers Render a Web Page', 'What the browser actually does with the HTML, CSS, and JavaScript it receives — and why that order explains a lot of layout bugs.', 'https://www.youtube.com/watch?v=Fe2bWQjJS68', 4,
      array['Describe how the browser parses HTML into the DOM', 'Explain where CSS and JavaScript fit into the rendering process', 'Explain why render order can cause visible layout shifts'],
      'The browser doesn''t just display a file — it builds a page. It parses HTML into the DOM (a tree of every element), parses CSS into rules, combines them to work out what each element should look like, calculates the layout (where everything sits), and finally paints pixels to the screen. JavaScript can change the DOM at any point, forcing parts of that process to run again. This explains real behaviour you''ll notice: why a page sometimes flashes unstyled content, or why elements jump as an image loads late. Later, when you''re optimising a site, this pipeline is what you''re optimising.',
      'Open DevTools'' Elements panel on any site and expand the HTML tree — you''re looking at the DOM the browser built, not the raw file. Find one element and change its text live.',
      '[{"question":"What is the DOM?","options":["A type of server","The tree of elements the browser builds from the HTML","A CSS property","A JavaScript library"],"correct_index":1},{"question":"Why can a page visibly shift while loading?","options":["The browser recalculates layout as more resources arrive","The server is broken","The user''s mouse moved","Pages never shift while loading"],"correct_index":0}]'::jsonb),
    (v_m1, 'HTTP and HTTPS Basics', 'The protocol that carries every request and response — and what the S in HTTPS actually protects.', 'https://www.youtube.com/watch?v=hExRDVZHhig', 5,
      array['Explain what HTTP is and what a request and response contain', 'Explain what HTTPS adds and why it matters', 'Recognise common status codes like 200, 404, and 500'],
      'HTTP is the set of rules browsers and servers use to talk. A request says what you want and how (GET to fetch, POST to send data); a response carries the content plus a status code saying what happened — 200 means success, 404 means not found, 500 means the server itself broke. HTTPS is the same protocol running over an encrypted connection, so nobody in between can read or alter the traffic. Every site you build should use HTTPS: browsers now actively warn users away from sites that don''t, and it''s a prerequisite for handling any login or payment.',
      'In DevTools'' Network tab, click any request and read its status code and whether it went over HTTPS. Then visit a URL you know doesn''t exist on a site and observe the 404.',
      '[{"question":"What does a 404 status code mean?","options":["Success","The requested resource was not found","The server crashed","Permission denied"],"correct_index":1},{"question":"What does HTTPS add over plain HTTP?","options":["Faster loading only","Encryption, so traffic can''t be read or altered in transit","Better graphics","Nothing, they''re identical"],"correct_index":1}]'::jsonb)
  on conflict (module_id, order_number) do nothing;

  insert into public.modules (course_id, level_id, title, description, order_number) values
    (v_course_id, v_level, 'Developer Tools & Workflow', 'Set up the tools every web developer uses daily — a code editor, browser dev tools, the terminal, and version control with Git and GitHub.', v_module_offset + 2)
  returning id into v_m2;

  insert into public.lessons (module_id, title, description, youtube_url, order_number, learning_objectives, notes, practice_activity, knowledge_check) values
    (v_m2, 'Installing and Setting Up VS Code', 'Install Visual Studio Code and configure it for web development — the editor you''ll write nearly every line of code in.', 'https://www.youtube.com/watch?v=fnPhJHN0jTE', 1,
      array['Install VS Code on your operating system', 'Navigate the editor: explorer, tabs, and the integrated terminal', 'Install a useful extension and understand what extensions do'],
      'VS Code is a free code editor from Microsoft and the most widely used tool in web development. Beyond just typing text, it gives you syntax highlighting (colouring code so mistakes stand out), autocomplete, an integrated terminal so you never leave the window, and an extension marketplace that adds language support and helper tools. Getting comfortable moving around it early pays off constantly, because it''s where the rest of this Learning Path happens.',
      'Install VS Code, create a folder called `my-first-site`, open it in VS Code, and create an empty `index.html` file inside it.',
      '[{"question":"What is VS Code?","options":["A web browser","A code editor for writing and managing code","A programming language","A web hosting service"],"correct_index":1},{"question":"What do VS Code extensions do?","options":["Nothing, they''re decorative","Add extra features like language support and helper tools","Make the computer faster","Replace the need for a browser"],"correct_index":1}]'::jsonb),
    (v_m2, 'Browser Developer Tools (Chrome DevTools)', 'Open the browser''s built-in developer tools to inspect any page''s HTML, edit CSS live, and read errors in the console.', 'https://www.youtube.com/watch?v=gTVpBbFWry8', 2,
      array['Open DevTools and inspect an element on any live web page', 'Edit CSS in the Elements panel and see changes instantly', 'Read errors and log messages in the Console panel'],
      'Every modern browser ships with developer tools built in — press F12 or right-click and choose Inspect. The Elements panel shows the live HTML and CSS of any page, and you can edit both temporarily to test ideas without touching your files. The Console panel shows JavaScript errors and messages, which is where you''ll spend a lot of debugging time later. DevTools is also the fastest way to learn from other sites: open any page you admire and look at exactly how it''s built.',
      'Open any website, press F12, use the Elements panel to change a heading''s colour, then check the Console panel for any errors on that page.',
      '[{"question":"What does the Elements panel in DevTools show?","options":["Your computer''s files","The live HTML and CSS of the current page","Your browsing history","Installed extensions"],"correct_index":1},{"question":"Where do JavaScript errors appear in DevTools?","options":["The Console panel","The Elements panel","The Network panel","They don''t appear anywhere"],"correct_index":0}]'::jsonb),
    (v_m2, 'Command Line and Terminal Basics', 'Learn the handful of terminal commands that web development actually requires — navigating folders, creating files, and running tools.', 'https://www.youtube.com/watch?v=mABpAI-pCw0', 3,
      array['Navigate the file system using cd, ls/dir, and pwd', 'Create folders and files from the command line', 'Explain why developers use the terminal instead of only a file explorer'],
      'The terminal is a text interface for controlling your computer, and web development leans on it constantly: installing packages, running a local server, and using Git all happen there. You only need a few commands to start — `pwd` shows where you are, `ls` (macOS/Linux) or `dir` (Windows) lists what''s there, `cd` moves between folders, and `mkdir` makes a new folder. It feels slower than clicking at first, but it''s far faster once the commands are in your fingers, and many developer tools have no graphical interface at all.',
      'Open your terminal, use `cd` to navigate to your Desktop, create a folder with `mkdir practice-folder`, move into it, and confirm your location with `pwd`.',
      '[{"question":"Which command shows your current location in the file system?","options":["ls","pwd","mkdir","cd"],"correct_index":1},{"question":"Why do web developers use the terminal?","options":["It looks more professional","Many essential developer tools only run from the command line","It''s the only way to open files","It makes the internet faster"],"correct_index":1}]'::jsonb),
    (v_m2, 'Git Basics: Tracking Your Changes', 'Use Git to save snapshots of your project so you can always go back — the safety net every developer relies on.', 'https://www.youtube.com/watch?v=8JJ101D3knE', 4,
      array['Explain what version control is and why it matters', 'Initialise a repository and make your first commit', 'Use git status and git log to see what''s changed'],
      'Git is a version control system: it records snapshots of your project over time so you can review history, undo mistakes, and work on changes safely. The basic cycle is small and repeats forever — `git init` starts tracking a project, `git add` stages the changes you want to record, and `git commit -m "message"` saves that snapshot with a description. `git status` tells you where things stand, and `git log` shows past commits. Learning this early means you never lose work again, and it''s assumed knowledge in every development job.',
      'In your practice folder, run `git init`, create a file, then run `git add .` and `git commit -m "first commit"`. Check the result with `git log`.',
      '[{"question":"What does `git commit` do?","options":["Uploads your code to the internet","Saves a snapshot of your staged changes with a message","Deletes your project history","Installs a package"],"correct_index":1},{"question":"What is version control for?","options":["Making code run faster","Recording project history so you can review and undo changes","Designing web pages","Hosting websites"],"correct_index":1}]'::jsonb),
    (v_m2, 'GitHub Basics: Repositories, Push, and Pull', 'Put your Git projects online with GitHub — where developers back up code, show their work, and collaborate.', 'https://www.youtube.com/watch?v=yxvqLBHZfXk', 5,
      array['Create a repository on GitHub and connect it to a local project', 'Push local commits to GitHub and pull changes back down', 'Explain how GitHub differs from Git itself'],
      'Git runs on your computer; GitHub is a website that hosts Git repositories online. Connecting the two lets you back up your work, access it from anywhere, and share it publicly. `git push` sends your local commits up to GitHub, and `git pull` brings down changes made elsewhere. For someone learning, GitHub matters for a second reason too: it becomes a public record of what you''ve built, and it''s often the first thing a potential client or employer looks at.',
      'Create a free GitHub account, make a new repository, and push your practice folder to it. Confirm your files appear on the GitHub website.',
      '[{"question":"What is the difference between Git and GitHub?","options":["They are the same thing","Git runs locally; GitHub hosts repositories online","GitHub runs locally; Git is a website","Git is for HTML, GitHub is for CSS"],"correct_index":1},{"question":"What does `git push` do?","options":["Deletes a repository","Sends your local commits up to the remote repository","Downloads changes from the remote","Creates a new file"],"correct_index":1}]'::jsonb)
  on conflict (module_id, order_number) do nothing;

  insert into public.modules (course_id, level_id, title, description, order_number) values
    (v_course_id, v_level, 'Thinking Like a Developer', 'The mental models that separate someone copying tutorials from someone who can actually build — how the three core languages fit together, how to read docs, how to debug, and who you''re building for.', v_module_offset + 3)
  returning id into v_m3;

  insert into public.lessons (module_id, title, description, youtube_url, order_number, learning_objectives, notes, practice_activity, knowledge_check) values
    (v_m3, 'HTML, CSS, and JavaScript: What Each One Does', 'The single most important mental model in web development: structure, style, and behaviour as three separate layers.', 'https://www.youtube.com/watch?v=6mbwJ2xhgzM', 1,
      array['Explain the role of HTML, CSS, and JavaScript separately', 'Identify which language is responsible for a given feature on a page', 'Describe how the three work together to make one web page'],
      'Every web page is built from three languages with clearly separate jobs. HTML is the structure — headings, paragraphs, images, buttons — the content and its meaning. CSS is the presentation — colours, spacing, fonts, layout, responsiveness — how that structure looks. JavaScript is the behaviour — what happens when you click, type, or scroll, and anything that changes without reloading the page. A useful analogy: HTML is the skeleton, CSS is the skin and clothes, JavaScript is the muscles. Keeping these roles distinct in your head makes every later lesson easier, because when something breaks you''ll know which of the three to look at.',
      'Open a website you use often and list five things on the page, labelling each as HTML (content), CSS (appearance), or JavaScript (interactive behaviour).',
      '[{"question":"Which language is responsible for the structure and content of a page?","options":["CSS","HTML","JavaScript","Python"],"correct_index":1},{"question":"A dropdown menu that opens when clicked is primarily handled by:","options":["HTML","CSS","JavaScript","The browser''s settings"],"correct_index":2}]'::jsonb),
    (v_m3, 'How to Read Technical Documentation', 'Move beyond tutorials by learning to read official documentation — the skill that lets you solve problems no video covers.', 'https://www.youtube.com/watch?v=s1PLS3SQHQ0', 2,
      array['Find the official documentation for a language or tool', 'Read a documentation entry: syntax, parameters, and examples', 'Explain why documentation beats tutorials for solving specific problems'],
      'Tutorials teach you a path someone else chose; documentation lets you answer your own questions. For web development, MDN Web Docs (developer.mozilla.org) is the standard reference for HTML, CSS, and JavaScript. A typical entry gives a short description, the syntax, the accepted values or parameters, and runnable examples — skim the description and jump straight to examples first, then read details as needed. Every professional developer looks things up constantly; memorising everything was never the goal, and getting comfortable in the docs early is what makes you self-sufficient.',
      'Look up the CSS `flex-direction` property on MDN Web Docs. Note its possible values and try to explain in one sentence what it does.',
      '[{"question":"What is MDN Web Docs?","options":["A social network for developers","The standard reference documentation for HTML, CSS, and JavaScript","A code editor","A web hosting company"],"correct_index":1},{"question":"Why is reading documentation an important skill?","options":["It isn''t — tutorials cover everything","It lets you answer specific questions no tutorial covers","It''s required to install a browser","It makes code run faster"],"correct_index":1}]'::jsonb),
    (v_m3, 'The Debugging Mindset', 'A systematic approach to broken code — how to find the actual cause instead of guessing and changing things at random.', 'https://www.youtube.com/watch?v=NUrV_FbJqWs', 3,
      array['Read an error message and extract the useful information from it', 'Use console.log and browser DevTools to narrow down a bug', 'Apply a systematic process: reproduce, isolate, fix, verify'],
      'Debugging is a process, not a talent. Start by reading the error message properly — it usually names the file, the line, and the problem. Then reproduce the bug reliably, so you know when it''s actually fixed. Isolate it by changing one thing at a time, using `console.log` to check what values actually exist at each step (they''re often not what you assumed). Fix it, then verify by reproducing your original steps. The single biggest beginner mistake is changing several things at once out of frustration, which makes it impossible to tell what actually helped.',
      'Deliberately break something small in a page — misspell a CSS property or a variable name — then use the browser Console to find and fix it.',
      '[{"question":"What should you do first when you hit an error?","options":["Change random code until it works","Read the error message carefully for the file, line, and cause","Delete the file and start over","Restart the computer"],"correct_index":1},{"question":"Why change only one thing at a time while debugging?","options":["It''s a formal rule","So you can tell which change actually fixed the problem","It makes the code shorter","It has no real benefit"],"correct_index":1}]'::jsonb),
    (v_m3, 'Responsive and Mobile-First Design Basics', 'Why most of your users are on phones — and what that means for how you build every page from the start.', 'https://www.youtube.com/watch?v=x4u1yp3Msao', 4,
      array['Explain what responsive design means', 'Describe the mobile-first approach and why it''s recommended', 'Identify how a layout should adapt between phone and desktop'],
      'Responsive design means a single page adapts its layout to whatever screen it''s viewed on, rather than shipping separate mobile and desktop sites. Mobile-first means designing for the smallest screen first, then progressively adding layout for larger ones — this is recommended because it forces you to prioritise essential content, and expanding a simple layout is far easier than cramming a complex one down. This matters especially in Kenya and across Africa, where the large majority of web traffic is on mobile phones: a site that only works well on a laptop is broken for most of your actual audience.',
      'Open any site in your browser, press F12, and use DevTools'' device toolbar to view it at phone width. Note what changes in the layout and what breaks.',
      '[{"question":"What does responsive design mean?","options":["The site loads quickly","One page adapts its layout to different screen sizes","The site replies to emails","Building separate mobile and desktop websites"],"correct_index":1},{"question":"Why is mobile-first recommended?","options":["Phones are more expensive","It forces prioritising essential content, and expanding a simple layout is easier than shrinking a complex one","Desktop users don''t matter","It''s required by browsers"],"correct_index":1}]'::jsonb),
    (v_m3, 'Web Accessibility Basics', 'Build pages that work for people using screen readers, keyboards, and low-bandwidth connections — a professional baseline, not an optional extra.', 'https://www.youtube.com/watch?v=2oiBKSjOOFE', 5,
      array['Explain what web accessibility means and who it affects', 'Identify three practical accessibility basics (alt text, semantic HTML, colour contrast)', 'Test whether a page can be navigated using only the keyboard'],
      'Accessibility means building so that people with disabilities can actually use your site — including those using screen readers, navigating by keyboard, or needing high contrast. The practical basics go a long way: write real alt text on images so screen readers can describe them, use semantic HTML (`<button>`, `<nav>`, `<h1>`) instead of styling generic `<div>`s, and ensure enough colour contrast between text and background. Beyond being the right thing to do, accessible sites tend to rank better in search and are more usable for everyone — captions help in noisy rooms, and good contrast helps in bright sunlight.',
      'Pick any page and try navigating it using only the Tab key. Note whether you can reach every link and button, and whether you can always see what''s focused.',
      '[{"question":"What is alt text used for?","options":["Making images load faster","Describing an image so screen readers can convey it","Changing an image''s colour","Nothing, it''s decorative"],"correct_index":1},{"question":"Why use a semantic `<button>` instead of a styled `<div>`?","options":["It looks better by default","It''s keyboard-accessible and understood by assistive technology automatically","Divs are deprecated","There''s no difference"],"correct_index":1}]'::jsonb)
  on conflict (module_id, order_number) do nothing;

end $$;

-- Only Level 1 of 9 is built, so the curriculum stays draft: hidden from the
-- catalog/sitemap so nobody buys into an unfinished path, while the existing
-- enrollment keeps full access to what is built.
update public.courses set curriculum_status = 'draft'
  where id = '1ad74fd3-6a25-452c-a4b1-668f8e3be8e6';
