-- Auto-generated by scripts/curriculum/build-level-sql.mjs -- do not
-- hand-edit the lesson content below; regenerate from the source plan
-- JSON instead if something needs to change.

do $$
declare
  v_course_id uuid := '74b4b41c-2bc6-4e05-8ab5-ee22f89a5278';
  v_level uuid;
  -- modules.order_number is unique per COURSE, not per level (a course's
  -- modules are numbered continuously across all its levels) -- so this
  -- can't just start at 1 for a level beyond the first. Computed here
  -- instead of hardcoded so this script works correctly regardless of how
  -- many modules the course already has.
  v_module_offset int;
  v_m1 uuid;
  v_m2 uuid;
begin
  -- Appending to a level that already exists. Looked up rather than
  -- inserted, so this adds to the learner's current Level 1 instead of
  -- creating a duplicate one, and no existing module is re-parented.
  select id into v_level from public.levels
    where course_id = v_course_id and order_number = 1;

  if v_level is null then
    raise exception 'Level % not found for course % -- refusing to guess', 1, v_course_id;
  end if;

  -- The new modules must sit INSIDE this level, not at the end of the
  -- course. getOrderedLessons() builds the learner's lesson sequence from
  -- modules.order_number alone and ignores level, so a module appended at
  -- the course's max order would put beginner content after the final
  -- level's material. Insert straight after this level's last module and
  -- shift everything below it down instead.
  select coalesce(max(order_number), 0) into v_module_offset
    from public.modules where level_id = v_level;

  -- Two-phase shift: (course_id, order_number) is unique, and a single
  -- "+ N" update can trip that constraint mid-statement, so park the rows
  -- out of range first and bring them back afterwards.
  update public.modules set order_number = order_number + 1000
   where course_id = v_course_id and order_number > v_module_offset;

  insert into public.modules (course_id, level_id, title, description, order_number) values
    (v_course_id, v_level, 'Colour and Type', 'The two choices that decide whether a design works before anyone reads a word of it — which colours you put together, and which letterforms you set them in.', v_module_offset + 1)
  returning id into v_m1;

  insert into public.lessons (module_id, title, description, youtube_url, order_number, learning_objectives, notes, practice_activity, knowledge_check) values
    (v_m1, 'Colour Theory for Designers', 'Hue, saturation and value, and how to build a palette that holds together instead of fighting itself.', 'https://www.youtube.com/watch?v=_2LLXnUdUIc', 1,
      array['Describe a colour using hue, saturation and value', 'Build a monochromatic and an analogous colour scheme', 'Recognise the colour mistakes beginners most often make'],
      'This one is tool-agnostic — no software on screen, just the principles, which is exactly right for a first pass.

Every colour breaks down into three things: **hue** (which colour it is), **saturation** (how intense) and **value** (how light or dark). Almost every "my design looks wrong but I don''t know why" moment comes from value: two colours at the same value sit on top of each other and the design goes flat, no matter how nice the hues are.

A scheme is a rule for picking colours that relate to each other. Monochromatic uses one hue at different values and is almost impossible to get wrong — a genuinely good default when you''re starting. Analogous uses neighbours on the wheel and feels calm. The discipline that matters more than any scheme: **use fewer colours than you want to.** Two plus a neutral will carry most work.',
      'Pick one hue and build a monochromatic palette of five values from it, then design a simple social post using only those. Then rebuild the same post with five unrelated colours and put them side by side.',
      '[{"question":"Which property most often explains a design looking flat?","options":["Hue","Value — two colours at the same lightness don''t separate","Saturation","The file format"],"correct_index":1},{"question":"What is a monochromatic scheme?","options":["Black and white only","One hue used at different saturations and values","Opposite colours on the wheel","Any three colours"],"correct_index":1}]'::jsonb),
    (v_m1, 'Colour Combinations and Readability', 'How colours relate on the wheel — complementary, analogous, triadic — and what that does to legibility.', 'https://www.youtube.com/watch?v=g7ql43Q2OsY', 2,
      array['Identify complementary, analogous, triadic and monochromatic relationships', 'Explain how a colour pairing affects legibility', 'Choose a text-and-background pair that stays readable'],
      'A note before you watch: this is from Adobe''s series, so the demonstration is in Illustrator while you are most likely in Canva. Ignore the software and watch the *relationships* — those are the same everywhere, and Canva''s colour picker will do all of it.

Complementary colours sit opposite each other and create maximum contrast, which is why they grab attention and why they are exhausting in large blocks. Analogous colours are neighbours and feel harmonious. Triadic gives three evenly spaced hues with variety that still holds together.

The practical test is contrast: **dark text on a light background, or light on dark, and check it at arm''s length on a phone.** If you have to lean in, the pairing has failed regardless of how good it looks on your laptop. Two saturated complementary colours directly against each other vibrate unpleasantly and are almost never right for text.

**One addition from me, since no video covers it well:** colour *meaning* is far more culturally specific than most design advice admits. Associations that hold in one market do not travel — white means purity in some places and mourning in others, and red carries very different weight across contexts. Know your actual audience rather than trusting a chart.',
      'Take a headline and set it in three colour pairings — complementary, analogous, and dark-on-light. View each on your phone at arm''s length and note which you can still read comfortably.',
      '[{"question":"Where do complementary colours sit on the colour wheel?","options":["Next to each other","Opposite each other","Evenly spaced in threes","In the same family"],"correct_index":1},{"question":"What is the practical test for a text and background pairing?","options":["Whether it looks modern","Whether it stays readable on a phone at arm''s length","Whether it uses brand colours","Whether it is complementary"],"correct_index":1}]'::jsonb),
    (v_m1, 'Typography Basics', 'Choosing and combining fonts, and the vocabulary — hierarchy, leading, tracking, kerning — that lets you say what''s wrong.', 'https://www.youtube.com/watch?v=sByzHoiYFX0', 3,
      array['Use the terms hierarchy, leading, tracking and kerning correctly', 'Pair two fonts without them competing', 'Recognise fonts to avoid in professional work'],
      'Also tool-agnostic. Type is the single fastest way to make work look amateur or professional, and the difference is mostly restraint.

The vocabulary is worth learning properly because it turns "this looks off" into a fixable observation: **leading** is the space between lines, **tracking** the spacing across a run of text, **kerning** the space between two specific letters. Loose leading in body text is one of the cheapest readability wins available.

On pairing: **two fonts is plenty**, and the reliable trick is contrast in role, not similarity — a distinctive display font for headings, a plain workhorse for body. Two fonts that are nearly alike read as a mistake rather than a choice. And the fonts to avoid are avoidable for a reason: they carry so much cultural baggage that the reader notices the font instead of the message.',
      'Set a poster with one display font for the heading and one plain font for the body. Then increase the body leading by half a line and compare readability. Then try it with two very similar fonts and see how muddled it looks.',
      '[{"question":"What is leading?","options":["Space between two specific letters","Space between lines of text","The font weight","The heading size"],"correct_index":1},{"question":"What makes two fonts pair well?","options":["Being as similar as possible","Clear contrast in role — a display face with a plain body face","Both being decorative","Using the same size"],"correct_index":1}]'::jsonb)
  on conflict (module_id, order_number) do nothing;

  insert into public.modules (course_id, level_id, title, description, order_number) values
    (v_course_id, v_level, 'Layout and Composition', 'Where things go on the page and why. The principles here are what separate a design that communicates from one that was merely assembled.', v_module_offset + 2)
  returning id into v_m2;

  insert into public.lessons (module_id, title, description, youtube_url, order_number, learning_objectives, notes, practice_activity, knowledge_check) values
    (v_m2, 'Layout and Composition Principles', 'Proximity, alignment, contrast, repetition and white space — the five ideas underneath every layout that works.', 'https://www.youtube.com/watch?v=a5KYlHNKQB8', 1,
      array['Group related items using proximity', 'Align elements deliberately rather than by eye', 'Apply contrast and repetition to give a layout structure'],
      'Five minutes, tool-agnostic, and probably the highest value-per-minute lesson in this level.

**Proximity**: things that belong together go together — a caption near its image, not floating between two. **Alignment**: nothing should be placed arbitrarily; every element should line up with something else, and a single strong left edge beats a page of centred text. **Contrast**: if two things are different, make them clearly different, because slightly different reads as an accident. **Repetition**: reusing a colour, size or spacing across a design is what makes it feel like one piece. **White space** is not wasted space — it is what gives everything else room to be seen.

When a design feels wrong and you can''t name why, walk these five in order. It is almost always one of them, usually alignment.',
      'Take a flyer you''ve made or found and mark every alignment edge with a ruler or guides. Fix anything that lines up with nothing. Then group related items closer together and pull unrelated ones apart, without changing any colour or font.',
      '[{"question":"What does the proximity principle say?","options":["Keep everything evenly spaced","Items that belong together should be grouped close together","Put the logo near the top","Use small margins"],"correct_index":1},{"question":"Why does ''slightly different'' fail?","options":["It costs more to print","It reads as a mistake rather than a deliberate choice","It is harder to align","It uses more colours"],"correct_index":1}]'::jsonb),
    (v_m2, 'Negative Space and Scale', 'Using empty space as a material, and using size differences to build hierarchy and pull attention.', 'https://www.youtube.com/watch?v=gl48K9X69BU', 2,
      array['Explain what negative space is and how it strengthens a layout', 'Use scale to establish what a viewer sees first', 'Create hierarchy without adding more elements'],
      'Adobe''s series again, so it''s demonstrated in Illustrator — watch the thinking, not the toolbar. Everything here is achievable in Canva.

Negative space is the empty area around and between your elements, and treating it as a deliberate choice rather than leftover is one of the clearest markers of experience. Beginners fill space because it feels wasteful; the result is a design with nowhere for the eye to rest.

**Scale** is the most direct hierarchy tool you have. Make the most important thing genuinely, obviously bigger — not slightly bigger. A viewer decides what to look at first in well under a second, and size is what decides it for them. If everything on your design is roughly the same size, you have not told the viewer anything about what matters.',
      'Take a design where everything is a similar size. Pick the one message that matters most, make it dramatically larger, and shrink everything else. Then increase the margins substantially. Compare against the original.',
      '[{"question":"What is negative space?","options":["A design mistake","The empty area around and between elements, used deliberately","Dark backgrounds","Space outside the printable area"],"correct_index":1},{"question":"How does scale create hierarchy?","options":["It doesn''t","Size differences tell the viewer what to look at first","By adding more elements","By using brighter colours"],"correct_index":1}]'::jsonb),
    (v_m2, 'Using Grids', 'The invisible structure professionals build layouts on, and how to make a flexible one.', 'https://www.youtube.com/watch?v=M8afKKlwJAk', 3,
      array['Explain what a grid is and why layouts use one', 'Build a simple flexible grid', 'Place elements consistently against grid lines'],
      'Adobe again, Illustrator on screen — but Canva has guides and rulers that do the same job, and its templates are already built on grids whether you notice or not.

A grid is a set of invisible columns and margins that everything aligns to. It is the reason professional layouts feel calm: alignment stops being a per-element decision and becomes automatic. It is also what makes a *set* of designs look related — same grid, different content, and a series holds together with no extra effort.

Grids are a tool, not a cage. Deliberately breaking the grid for one element is a genuine technique for drawing attention — but it only reads as deliberate if the rest of the design obeys the grid. Break it everywhere and you just have a mess.

This video covers grids specifically; the white-space side of the same story is in the two previous lessons.',
      'Set up a three-column grid with equal margins and lay out a simple poster on it. Then create a second poster on the same grid with different content, and see how obviously they read as a pair.',
      '[{"question":"What is a grid in layout?","options":["A visible table","Invisible columns and margins that elements align to","A Canva template","A colour system"],"correct_index":1},{"question":"When does breaking the grid work?","options":["Always","For one element, when the rest of the design obeys the grid","Never","Only in print"],"correct_index":1}]'::jsonb)
  on conflict (module_id, order_number) do nothing;

  -- Bring the shifted modules back, now sitting after the 2 new one(s).
  update public.modules set order_number = order_number - 1000 + 2
   where course_id = v_course_id and order_number > 1000;

end $$;
