-- Auto-generated by scripts/curriculum/build-level-sql.mjs -- do not
-- hand-edit the lesson content below; regenerate from the source plan
-- JSON instead if something needs to change.

do $$
declare
  v_course_id uuid := '664ea25b-6ce5-4dd5-974f-15d20dc02b1c';
  v_level uuid;
  -- modules.order_number is unique per COURSE, not per level (a course's
  -- modules are numbered continuously across all its levels) -- so this
  -- can't just start at 1 for a level beyond the first. Computed here
  -- instead of hardcoded so this script works correctly regardless of how
  -- many modules the course already has.
  v_module_offset int;
  v_m1 uuid;
  v_m2 uuid;
begin
  -- Appending to a level that already exists. Looked up rather than
  -- inserted, so this adds to the learner's current Level 1 instead of
  -- creating a duplicate one, and no existing module is re-parented.
  select id into v_level from public.levels
    where course_id = v_course_id and order_number = 1;

  if v_level is null then
    raise exception 'Level % not found for course % -- refusing to guess', 1, v_course_id;
  end if;

  -- The new modules must sit INSIDE this level, not at the end of the
  -- course. getOrderedLessons() builds the learner's lesson sequence from
  -- modules.order_number alone and ignores level, so a module appended at
  -- the course's max order would put beginner content after the final
  -- level's material. Insert straight after this level's last module and
  -- shift everything below it down instead.
  select coalesce(max(order_number), 0) into v_module_offset
    from public.modules where level_id = v_level;

  -- Two-phase shift: (course_id, order_number) is unique, and a single
  -- "+ N" update can trip that constraint mid-statement, so park the rows
  -- out of range first and bring them back afterwards.
  update public.modules set order_number = order_number + 1000
   where course_id = v_course_id and order_number > v_module_offset;

  insert into public.modules (course_id, level_id, title, description, order_number) values
    (v_course_id, v_level, 'Structure Before Slides', 'Decide what the presentation is actually for before you open any software. Most bad presentations are bad here, not in the design.', v_module_offset + 1)
  returning id into v_m1;

  insert into public.lessons (module_id, title, description, youtube_url, order_number, learning_objectives, notes, practice_activity, knowledge_check) values
    (v_m1, 'Deciding Your Core Message', 'The single idea you want people to leave with — and why one is the right number.', 'https://www.youtube.com/watch?v=-FOCpMAww28', 1,
      array['State the one idea your presentation exists to convey', 'Give the audience a reason to care early', 'Build an idea from concepts your audience already holds'],
      'Chris Anderson runs TED, so he has watched more presentations than almost anyone alive, and his advice is blunt: your job is to get **one** idea into the audience''s head. Not five. One.

His four rules are worth writing down. Limit yourself to one major idea. Give people a reason to care before you explain anything — curiosity first, content second. Build the idea out of things your audience already understands, because a new idea assembled from unfamiliar parts lands nowhere. And make it worth sharing, which is a useful test: if nobody would repeat this to a colleague tomorrow, it probably isn''t the idea.

Do this before you open PowerPoint or Canva. A deck built on a clear single message almost designs itself; a deck built on "I need to cover these eight topics" fights you the whole way.',
      'Take a presentation you need to give and write its one idea in a single sentence, out loud, without notes. If you can''t get it under one sentence, you have more than one presentation.',
      '[{"question":"How many major ideas should a presentation carry?","options":["As many as fit","One","Three to five","One per slide"],"correct_index":1},{"question":"Why build a new idea from concepts the audience already has?","options":["It saves time","An idea assembled from unfamiliar parts has nothing to attach to","It looks more professional","It reduces slide count"],"correct_index":1}]'::jsonb),
    (v_m1, 'Your Throughline: The Thread That Holds a Talk Together', 'The connective idea that runs from your first sentence to your last, and stops a talk becoming a list.', 'https://www.youtube.com/watch?v=btWlBHE0pe4', 2,
      array['Define a throughline for a presentation', 'Use it to decide what stays in and what gets cut', 'Explain why a talk without one feels like a list'],
      'A throughline is the spine. Every section should connect back to it, and anything that doesn''t connect is a candidate for deletion no matter how much you like it.

This is the practical follow-on from the last lesson: once you know your one idea, the throughline is how that idea travels through the whole talk rather than sitting in the introduction and being abandoned. It doubles as a roadmap for the audience — they can tell where they are and why this section exists.

The usual failure it prevents: a presentation that is really six mini-presentations stapled together. That version has no shape, so the audience can''t tell what matters, and they remember none of it. If you cannot say how a slide serves your throughline, cut the slide.',
      'Write your throughline in one sentence. Then list your planned sections and, next to each, write how it serves that sentence. Delete anything where you can''t answer.',
      '[{"question":"What is a throughline?","options":["The opening line","The connecting idea running from the start of a talk to the end","A slide transition","The summary slide"],"correct_index":1},{"question":"What should you do with a section that doesn''t connect to your throughline?","options":["Move it to the end","Cut it","Make it shorter","Put it in an appendix slide"],"correct_index":1}]'::jsonb),
    (v_m1, 'Decide How You''ll Deliver Before You Build', 'Scripted, memorised, or unscripted — choosing your approach before you make a single slide.', 'https://www.youtube.com/watch?v=1sOgYNgq88E', 3,
      array['Choose between a scripted, memorised, and unscripted delivery', 'Write and mark up a script for emphasis', 'Explain why the delivery choice shapes the slides'],
      'This decision comes before design because it changes what the slides need to do. If you''re speaking unscripted, your slides may need to carry more structure as prompts. If you''re working from a script, the slides can be sparse and visual because your words are doing the work.

The script markup technique here is genuinely useful and almost nobody does it: underline the two or three words in each sentence that actually matter, and let those be where your emphasis falls. Emphasis decided in advance sounds deliberate; emphasis improvised under nerves usually lands on the wrong word.

**An honest note on this lesson.** The original plan here was paper storyboarding — sketching your slides before building them, which is a genuinely valuable habit. The best video on it could not have its uploading channel confirmed, so rather than attach a source we can''t stand behind, this lesson covers the adjacent and equally important decision. Storyboarding is still worth doing: sticky notes, one idea per note, rearrange until the order feels right, then build.',
      'Pick your delivery approach for a real upcoming presentation and write it down. If scripted, write one paragraph of it and underline the two or three words per sentence you want to land on.',
      '[{"question":"Why decide your delivery approach before building slides?","options":["It doesn''t matter","It changes what the slides need to do — prompts versus sparse visuals","It sets the file format","It determines the colour scheme"],"correct_index":1},{"question":"What does marking up a script achieve?","options":["Shortens it","Decides emphasis in advance rather than improvising it under nerves","Makes it easier to memorise","Adds slide breaks"],"correct_index":1}]'::jsonb)
  on conflict (module_id, order_number) do nothing;

  insert into public.modules (course_id, level_id, title, description, order_number) values
    (v_course_id, v_level, 'Designing and Delivering Slides', 'Slides that support you instead of competing with you — then getting through the actual talk without your nerves running it.', v_module_offset + 2)
  returning id into v_m2;

  insert into public.lessons (module_id, title, description, youtube_url, order_number, learning_objectives, notes, practice_activity, knowledge_check) values
    (v_m2, 'One Message Per Slide', 'Five evidence-backed fixes for the crowded, unreadable slides almost everyone starts out making.', 'https://www.youtube.com/watch?v=Iwpi1Lm6dFo', 1,
      array['Limit each slide to a single message', 'Explain the redundancy effect and why reading your slides aloud fails', 'Use size and contrast to direct the audience''s eye'],
      'The most useful twenty minutes in this level. Five rules, each with a reason behind it rather than taste.

**One message per slide.** If a slide makes two points, it is two slides. **Don''t put your script on the slide and then read it** — this is the redundancy effect, and it actively harms comprehension because people cannot read and listen at the same time. Your audience will read ahead, finish before you, and stop listening. **Make the most important element the biggest**, because size is how the eye decides what to look at first. **Use contrast** to point at what matters. **Never more than about six objects on a slide**, which is roughly the limit of what working memory holds at once.

The closing line is the one to keep: you are the presentation, the software is a visual aid. A slide that can be understood without you is a document, and should have been emailed.',
      'Take your most crowded slide and split it until each slide carries one message. Count the objects on each — if more than six, cut. Then remove every sentence you were planning to read aloud.',
      '[{"question":"What is the redundancy effect?","options":["Repeating a slide","Putting your script on the slide and reading it harms comprehension, because people can''t read and listen at once","Using two fonts","Duplicating the agenda"],"correct_index":1},{"question":"Roughly how many objects should a slide hold at most?","options":["Two","About six","Twelve","No limit"],"correct_index":1}]'::jsonb),
    (v_m2, 'Choosing and Pairing Type for Slides', 'Readable typefaces, sensible pairings, and the vocabulary for saying what''s wrong.', 'https://www.youtube.com/watch?v=sByzHoiYFX0', 2,
      array['Choose a typeface that stays readable when projected', 'Pair two fonts by contrast in role', 'Use hierarchy, leading, tracking and kerning correctly'],
      'A general typography lesson rather than a slide-specific one — the principles are the same, and slides are simply the least forgiving place to get them wrong, because your reader is far away and cannot go back.

Two fonts is plenty: a distinctive face for headings, a plain workhorse for body text. Contrast in role is what makes a pairing work; two nearly-identical fonts read as a mistake. **Leading** is the space between lines, **tracking** the spacing across a run of text, **kerning** the gap between two specific letters.

For slides specifically, add one rule the video doesn''t: **size up more than feels right.** Text that looks generous on your laptop is often unreadable from the back of a room or on a phone screen. If in doubt, make it bigger and put less on the slide.',
      'Set a slide with one display font for the heading and one plain font for the body. Then stand back three metres from your screen — or view it on a phone at arm''s length — and cut anything you can''t read comfortably.',
      '[{"question":"What makes two fonts pair well?","options":["Being as similar as possible","Clear contrast in role — a display face with a plain body face","Both being bold","Matching colours"],"correct_index":1},{"question":"What is leading?","options":["The heading font","The space between lines of text","The gap between two letters","The slide margin"],"correct_index":1}]'::jsonb),
    (v_m2, 'Handling Nerves', 'Why stage fright happens physically, and the countermeasures that actually work.', 'https://www.youtube.com/watch?v=K93fMnFKwfI', 3,
      array['Explain the physical mechanism behind stage fright', 'Apply rehearsal and breathing techniques before presenting', 'Reframe nerves as a normal physical response rather than a personal failing'],
      'Four minutes, and worth it for the reframe alone. Stage fright is your fight-or-flight system reading an audience as a threat and flooding you with adrenaline. That is a physiological event, not evidence that you are bad at this — which matters, because most people interpret the racing heart as proof they will fail and then get more nervous.

The countermeasures are unglamorous and effective: **rehearse until the material is automatic**, so the part of your brain that panics isn''t also trying to remember what comes next. **Practise in the actual room** if you can. Exercise beforehand burns off some adrenaline; slow deep breathing tells your nervous system the threat is not real. And visualising it going well is not wishful thinking — it is rehearsal your body responds to.

Rehearsal is the one that does the most work. Nearly every presenter who seems calm has simply run it more times than you''d guess.',
      'Rehearse your opening two minutes out loud, standing, five times. Notice how much less you need the notes by the fifth. Then try slow breathing — four counts in, six out — for a minute beforehand.',
      '[{"question":"What causes stage fright physically?","options":["Poor preparation only","The fight-or-flight response reading an audience as a threat","Low blood sugar","Bad slides"],"correct_index":1},{"question":"Which countermeasure does the most work?","options":["Visualising success","Rehearsing until the material is automatic","Drinking water","Arriving early"],"correct_index":1}]'::jsonb),
    (v_m2, 'Voice, Pacing and Presence', 'Using your voice and body deliberately so the meaning lands, not just the words.', 'https://www.youtube.com/watch?v=PJKeLD-vMvo', 4,
      array['Vary pace and pause to give words weight', 'Use body language that supports rather than distracts', 'Speak in a way that sounds like you rather than performed'],
      'The final piece: you have a clear message, a throughline, and slides that don''t fight you. This is how the delivery carries it.

The most underused tool is the **pause**. Silence before or after an important sentence makes the audience pay attention to it, and nervous presenters skip pauses entirely because silence feels much longer on stage than it does in the room. Pace matters similarly — everything delivered at one speed flattens out and stops signalling what''s important.

On authenticity: the goal is not to perform a presenter persona but to be a slightly clearer, slightly slower version of yourself. Copied mannerisms read as false, and an audience notices that faster than they notice a design flaw.',
      'Record yourself delivering two minutes on your phone. Listen back for pace — is it all one speed? Then deliver it again, deliberately pausing for two full seconds after your most important sentence, and compare.',
      '[{"question":"What does a pause achieve?","options":["Fills time","Draws attention to the sentence before or after it","Hides nerves","Signals the end"],"correct_index":1},{"question":"Why does copying another presenter''s mannerisms tend to fail?","options":["It''s harder to remember","It reads as false, and audiences notice that quickly","It takes longer","It needs more rehearsal"],"correct_index":1}]'::jsonb)
  on conflict (module_id, order_number) do nothing;

  -- Bring the shifted modules back, now sitting after the 2 new one(s).
  update public.modules set order_number = order_number - 1000 + 2
   where course_id = v_course_id and order_number > 1000;

end $$;
