-- Auto-generated by scripts/curriculum/build-level-sql.mjs -- do not
-- hand-edit the lesson content below; regenerate from the source plan
-- JSON instead if something needs to change.

do $$
declare
  v_course_id uuid := '762b82fb-fbfc-45d7-8aff-d29f3143358f';
  v_level uuid;
  -- modules.order_number is unique per COURSE, not per level (a course's
  -- modules are numbered continuously across all its levels) -- so this
  -- can't just start at 1 for a level beyond the first. Computed here
  -- instead of hardcoded so this script works correctly regardless of how
  -- many modules the course already has.
  v_module_offset int;
  v_m1 uuid;
  v_m2 uuid;
begin
  -- Appending to a level that already exists. Looked up rather than
  -- inserted, so this adds to the learner's current Level 1 instead of
  -- creating a duplicate one, and no existing module is re-parented.
  select id into v_level from public.levels
    where course_id = v_course_id and order_number = 1;

  if v_level is null then
    raise exception 'Level % not found for course % -- refusing to guess', 1, v_course_id;
  end if;

  -- The new modules must sit INSIDE this level, not at the end of the
  -- course. getOrderedLessons() builds the learner's lesson sequence from
  -- modules.order_number alone and ignores level, so a module appended at
  -- the course's max order would put beginner content after the final
  -- level's material. Insert straight after this level's last module and
  -- shift everything below it down instead.
  select coalesce(max(order_number), 0) into v_module_offset
    from public.modules where level_id = v_level;

  -- Two-phase shift: (course_id, order_number) is unique, and a single
  -- "+ N" update can trip that constraint mid-statement, so park the rows
  -- out of range first and bring them back afterwards.
  update public.modules set order_number = order_number + 1000
   where course_id = v_course_id and order_number > v_module_offset;

  insert into public.modules (course_id, level_id, title, description, order_number) values
    (v_course_id, v_level, 'Designing for the User, Not the Tool', 'The existing lessons teach Figma. This one teaches the UX half of UI/UX — finding out what people actually need before you draw a single screen.', v_module_offset + 1)
  returning id into v_m1;

  insert into public.lessons (module_id, title, description, youtube_url, order_number, learning_objectives, notes, practice_activity, knowledge_check) values
    (v_m1, 'What User Research Actually Is', 'The Nielsen Norman Group — the people who largely defined the field — on what user research means and why designs built without it fail. Under 4 minutes.', 'https://www.youtube.com/watch?v=0MLwuhpwRiE', 1,
      array['Explain why your own preferences are not evidence of what users need', 'Tell the difference between what people say they do and what they actually do', 'Run a small, cheap piece of research before committing to a design'],
      'The job title is UI/UX Design, and almost everyone learns only the UI half. This module is the other half, and it is the one clients actually pay for.

Here is the uncomfortable premise: YOU ARE NOT YOUR USER. You know where every button is because you put it there. You understand the jargon because you chose it. Your sense of "this is obvious" was destroyed the moment you started building the thing. Every designer has this problem permanently, and research is the only way around it.

Two kinds of research, and beginners conflate them:

WHAT PEOPLE SAY — interviews, surveys, feedback forms. Useful for understanding goals, frustrations and context. Unreliable for predicting behaviour: people report what they think they should do, misremember, and are polite to whoever is asking.

WHAT PEOPLE DO — watching someone use the thing, analytics, session recordings. This is where the surprises are. Someone will tell you the checkout was fine and you will watch them hunt for the button for forty seconds.

When the two disagree, believe what they DO.

The cheapest useful research, and you can do it this week: give five people a real task on whatever exists now — your site, a competitor''s, a paper sketch — and WATCH THEM WITHOUT HELPING. That last part is the whole discipline. The instant you say "it''s the button on the right", you have destroyed the finding. Sit on your hands and write down where they hesitate.

Five people is not a statistically valid sample and does not need to be. You are looking for problems, not measuring them, and five people will surface most of the serious ones.',
      'Pick any app or website you did not build — a bank app, a government portal, an online shop. Write down one realistic task, like "find out how much delivery costs to Kisumu". Ask one person to do it while you watch in silence, and write down every place they pause, backtrack, or say "hmm". Then ask what they expected to happen at that moment. Doing this once, in silence, teaches more about UX than a week of reading.',
      '[{"question":"A user tells you the signup form was easy, but you watched them get stuck twice. Which do you believe?","options":["What they did — observed behaviour beats reported opinion","What they said, since they experienced it directly","Neither; you need a larger survey first","Whichever matches your original design"],"correct_index":0},{"question":"Why is watching in silence the hard part of a usability test?","options":["Helping the person destroys the very finding you are there to collect","Talking makes the recording unusable","It is considered rude to speak during research","The user will copy your accent"],"correct_index":0}]'::jsonb),
    (v_m1, 'User Flows Before Screens', 'Nielsen Norman Group on user journeys versus user flows, when each is the right tool, and why mapping the path comes before designing the pages. Under 4 minutes.', 'https://www.youtube.com/watch?v=dsviXwJwslI', 2,
      array['Map the steps a user takes to complete a goal, before designing any screen', 'Distinguish a user journey from a user flow and know when each applies', 'Spot a missing screen or dead end on paper rather than in Figma'],
      'Beginners open Figma and start drawing a home page. Professionals work out the PATH first, because a beautiful screen in the wrong sequence is worthless.

A USER FLOW is the concrete step-by-step route through a product to finish one task: land on page → search → view result → add to cart → checkout → confirmation. It is narrow, specific, and made of screens and decisions.

A USER JOURNEY is wider. It covers the person''s whole experience around the goal, including things that happen outside your product — seeing an advert, asking a friend, receiving a delivery, needing a refund three weeks later. It captures how they feel at each stage, not just what they click.

Use a flow when you are designing a feature. Use a journey when you are trying to understand where the experience is failing overall.

What makes flows worth the effort is that they expose the screens you forgot. Sketch a signup flow honestly and you will immediately notice you have no design for: the email already exists, the password is too weak, the verification email never arrived, the user closes the tab halfway through. Those states are most of the real work, and they are invisible if you go straight to drawing a pretty home page.

Draw the flow with boxes and arrows on paper or a whiteboard. Deliberately not in Figma — the point is to think in ten minutes without being seduced into choosing fonts.

The question to ask at every box: what happens if this goes wrong?',
      'Take one task from an app you use — booking a ride, sending money, buying airtime. Draw the flow as boxes and arrows on paper, one box per screen. Then go back and add a box for every failure you can think of: no network, wrong PIN, insufficient balance, session timeout. Count how many boxes you added on the second pass. That ratio is why flows come before screens.',
      '[{"question":"What does sketching a user flow most reliably reveal?","options":["The error and edge-case screens you had not thought to design","Which fonts will suit the brand","How much the project should cost","Which colours users prefer"],"correct_index":0},{"question":"You want to understand why customers abandon you weeks after signing up. Which tool fits?","options":["A user journey, because it covers experience beyond the product itself","A user flow, because it lists the screens","A wireframe of the home page","A component library"],"correct_index":0}]'::jsonb)
  on conflict (module_id, order_number) do nothing;

  insert into public.modules (course_id, level_id, title, description, order_number) values
    (v_course_id, v_level, 'Layout That Scales: Auto Layout and Components', 'The two Figma features that separate a hobby file from a professional one. Both taught here by Figma itself.', v_module_offset + 2)
  returning id into v_m2;

  insert into public.lessons (module_id, title, description, youtube_url, order_number, learning_objectives, notes, practice_activity, knowledge_check) values
    (v_m2, 'Auto Layout — Designs That Resize Themselves', 'Figma''s own guide to Auto Layout: best practices, tips and tricks. About 23 minutes, and the single most useful feature in the tool.', 'https://www.youtube.com/watch?v=1odqpkfkDL8', 1,
      array['Build a frame that resizes itself when its content changes', 'Control spacing, padding and alignment without nudging anything by hand', 'Recognise when a design should be an Auto Layout rather than loose shapes'],
      'If you have only ever placed shapes by dragging them, Auto Layout will feel like the moment the tool starts working for you instead of against you.

Without it, a button is a rectangle with text sitting on top. Change the label from "Buy" to "Add to basket" and the text overflows the rectangle, so you resize the rectangle, then re-centre the text, then nudge everything below it down. Multiply by fifty screens and this is why people hate design revisions.

WITH Auto Layout, that button is a container that holds its text. Change the label and the button grows to fit, keeping its padding. Everything below shifts automatically.

The three controls that do most of the work:

DIRECTION — does content stack vertically or run horizontally.
SPACING BETWEEN ITEMS — the gap, set once, applied consistently, rather than eyeballed per item.
PADDING — the breathing room between the content and the container edge.

Then RESIZING behaviour per element: HUG contents (shrink to fit what''s inside), FILL container (stretch to whatever space is available), or FIXED. Getting hug-versus-fill right is most of Auto Layout.

Auto Layout nests, and that is where it becomes powerful: a horizontal row inside a vertical card inside a vertical page. Build it that way and the whole screen reflows correctly when any one piece changes.

This also happens to be how CSS flexbox works, so learning it here teaches you how developers will actually build your design. That shared model is why handoff goes smoothly for designers who use it and badly for those who do not.',
      'Rebuild a card you have already designed — a product card, a profile card — using Auto Layout instead of free-floating shapes. Then test it properly: change the title to something three times longer, and swap the button label for a much longer one. If the card grows sensibly and nothing overlaps, you have it right. If you have to nudge anything by hand, something is still fixed that should hug or fill.',
      '[{"question":"You set an element to \"hug contents\". What does that mean?","options":["It shrinks or grows to exactly fit what is inside it","It stretches to fill all available space","Its size is locked and never changes","It centres itself in the parent frame"],"correct_index":0},{"question":"Why does Auto Layout make developer handoff easier?","options":["It mirrors how CSS flexbox lays out real pages","It exports the code automatically","It removes the need for developers entirely","It compresses the file size"],"correct_index":0}]'::jsonb),
    (v_m2, 'Components and Variants — Change Once, Update Everywhere', 'Figma''s own tutorial on variants: grouping the states of a component so one button handles default, hover, pressed and disabled. About 14 minutes.', 'https://www.youtube.com/watch?v=y29Xwt9dET0', 2,
      array['Create a component and reuse it as instances across a file', 'Group related states into variants instead of separate copies', 'Explain why copy-pasting elements makes a file unmaintainable'],
      'A COMPONENT is a master element you define once. Every copy you place is an INSTANCE that stays linked to it. Change the master and every instance updates.

This matters more than it sounds. Copy-paste a button forty times across twelve screens, then have the client ask for slightly rounder corners, and you have forty manual edits and you will miss three of them. Nobody notices until a developer builds it and asks which of the three is correct. With components it is one edit.

VARIANTS take this further. A button is not one thing — it is default, hover, pressed, disabled, loading, and maybe small/medium/large on top of that. Kept as separate components, that is a sprawling mess with names like "button-blue-small-hover-2-FINAL". As VARIANTS they are one component with properties you switch, exactly the way a developer will implement it.

Instances can be overridden — change one instance''s text or icon and it keeps every other property linked to the master. This is the point: shared structure, local content.

The habit worth building early is NAMING. Figma builds a component''s organisation from its name, and slashes create groups: `Button/Primary/Large`. Name things carelessly for a week and the assets panel becomes unusable. Name them consistently and the file organises itself.

Components plus Auto Layout together are what a design system is made of, and a design system is what makes you employable rather than merely competent with the software.',
      'Take a button you have already drawn and turn it into a component. Add variants for at least three states — default, disabled, and one more. Place four instances across a screen, then change the master''s corner radius and colour, and watch all four update. Finally, override the text on just one instance and confirm the others are unaffected. That last check is the concept landing.',
      '[{"question":"Why use variants rather than separate components for a button''s states?","options":["They group the states into one component with switchable properties, matching how developers build it","Variants render faster in the browser","Separate components cannot be renamed","Variants automatically write the CSS"],"correct_index":0},{"question":"What happens when you override the text on one instance of a component?","options":["Only that instance changes; it stays linked to the master for everything else","Every instance changes to the new text","The instance is detached from the master permanently","The master component is updated"],"correct_index":0}]'::jsonb)
  on conflict (module_id, order_number) do nothing;

  -- Bring the shifted modules back, now sitting after the 2 new one(s).
  update public.modules set order_number = order_number - 1000 + 2
   where course_id = v_course_id and order_number > 1000;

end $$;
