-- Auto-generated by scripts/curriculum/build-level-sql.mjs -- do not
-- hand-edit the lesson content below; regenerate from the source plan
-- JSON instead if something needs to change.

do $$
declare
  v_course_id uuid := 'd2c1698b-e25a-47b5-8d0e-58a8a661acad';
  v_level uuid;
  -- modules.order_number is unique per COURSE, not per level (a course's
  -- modules are numbered continuously across all its levels) -- so this
  -- can't just start at 1 for a level beyond the first. Computed here
  -- instead of hardcoded so this script works correctly regardless of how
  -- many modules the course already has.
  v_module_offset int;
  v_m1 uuid;
  v_m2 uuid;
begin
  -- Appending to a level that already exists. Looked up rather than
  -- inserted, so this adds to the learner's current Level 1 instead of
  -- creating a duplicate one, and no existing module is re-parented.
  select id into v_level from public.levels
    where course_id = v_course_id and order_number = 1;

  if v_level is null then
    raise exception 'Level % not found for course % -- refusing to guess', 1, v_course_id;
  end if;

  -- The new modules must sit INSIDE this level, not at the end of the
  -- course. getOrderedLessons() builds the learner's lesson sequence from
  -- modules.order_number alone and ignores level, so a module appended at
  -- the course's max order would put beginner content after the final
  -- level's material. Insert straight after this level's last module and
  -- shift everything below it down instead.
  select coalesce(max(order_number), 0) into v_module_offset
    from public.modules where level_id = v_level;

  -- Two-phase shift: (course_id, order_number) is unique, and a single
  -- "+ N" update can trip that constraint mid-statement, so park the rows
  -- out of range first and bring them back afterwards.
  update public.modules set order_number = order_number + 1000
   where course_id = v_course_id and order_number > v_module_offset;

  insert into public.modules (course_id, level_id, title, description, order_number) values
    (v_course_id, v_level, 'Budgets, Bidding and Not Wasting Money', 'The existing lessons show you how to build a campaign. This one is about the part that costs real money if you get it wrong — and unlike most skills in this catalogue, mistakes here are billed to you daily.', v_module_offset + 1)
  returning id into v_m1;

  insert into public.lessons (module_id, title, description, youtube_url, order_number, learning_objectives, notes, practice_activity, knowledge_check) values
    (v_m1, 'How Your Daily Budget Is Actually Spent', 'Google Ads'' own explanation of budget pacing — why daily spend varies and what the real ceiling is. About 4 minutes.', 'https://www.youtube.com/watch?v=Qul_St1XhJI', 1,
      array['Explain why daily spend can exceed your daily budget on any given day', 'Work out what a campaign can cost you over a month', 'Set a budget you can genuinely afford to lose while learning'],
      'This is the lesson that protects your money, so read it before you switch anything on.

THE DAILY BUDGET IS NOT A DAILY CAP. Google can spend more than it on a day when there is extra useful traffic, and less on a quiet day. It balances out over the billing period, and there is a defined limit on how far it will overspend on a single day. If you set 500 shillings a day and see 700 on Tuesday, nothing is broken — but you need to understand the monthly figure, not the daily one.

THINK IN MONTHS. Your daily budget multiplied by roughly 30.4 is the realistic monthly ceiling. Set 500/day and you are committing to roughly 15,000 shillings a month. Decide the monthly number you can afford first, then divide backwards. Working the other way round is how people get a bill that shocks them.

THE BEGINNER''S RULE: start at an amount you would be genuinely willing to lose entirely, because while you are learning, some of it will be lost. Ads are not a savings account. Your first campaign is tuition.

WHAT ACTUALLY BURNS MONEY FASTEST, in order:

- BROAD MATCH KEYWORDS with no negative keywords. You bid on "shoes" and pay for "how to draw shoes", "shoe museum", "free shoes". Negative keywords are the single highest-value thing a beginner can add.
- Sending clicks to a HOME PAGE instead of a page about the thing advertised. You paid for the visit and then made them hunt.
- Leaving a campaign running unattended over a weekend before you have any conversion data.
- Bidding on your own brand name when you already rank first organically — paying for a click you were getting free.

Check a new campaign daily for the first week. Not because it needs constant fiddling, but because that is when a mistake is cheapest to catch.',
      'Before spending anything, write down the monthly figure you can genuinely afford to lose, then divide by 30.4 to get your daily budget. Then open the search terms report on any existing campaign — or think through your main keyword — and write down five searches you do NOT want to pay for. Those are your first negative keywords, and adding them is usually the biggest single saving available to a beginner.',
      '[{"question":"You set a daily budget of 500 and Google spends 700 one day. What is happening?","options":["Normal pacing — Google spends more on high-traffic days and balances out over the billing period","Your account has been hacked","You have been charged twice by mistake","Your budget setting failed to save"],"correct_index":0},{"question":"Which single addition most reliably stops a beginner wasting money?","options":["Negative keywords, so you stop paying for irrelevant searches","A larger daily budget","More ad variations","Bidding on your own brand name"],"correct_index":0}]'::jsonb),
    (v_m1, 'Bidding Strategies and Where the Money Goes', 'Google Ads on budgets, bidding and automated campaigns, and how to choose between the strategies. About 24 minutes — the longest lesson here, so watch it in parts if data is tight.', 'https://www.youtube.com/watch?v=rI5ZmVloHo8', 2,
      array['Tell the difference between manual and automated bidding', 'Choose a bidding strategy appropriate to how much data you have', 'Explain why automated bidding needs conversion tracking to work at all'],
      'A bidding strategy is you telling Google what you want it to optimise for. Choose wrong and you can spend a full budget efficiently achieving something worthless.

THE CRUCIAL DISTINCTION: some strategies optimise for CLICKS, others for CONVERSIONS. Maximise Clicks will happily buy you a thousand visitors who do nothing. That is not Google misbehaving — it is doing exactly what you asked. If what you want is enquiries or sales, you must say so, and that means Google has to know what a conversion is, which is the next module.

Roughly what the options do:

MANUAL CPC — you set the maximum per keyword. Most control, most work. Useful early because it forces you to look at what things cost.

MAXIMISE CLICKS — most traffic for the budget. Fine for a brand new campaign gathering data, dangerous as a permanent setting.

MAXIMISE CONVERSIONS — the most enquiries or sales for your budget. Requires conversion tracking and enough history to learn from.

TARGET CPA — aim for a set cost per acquisition. Genuinely useful once you know what a customer is worth to you.

TARGET ROAS — aim for a return on ad spend. E-commerce, with revenue data flowing back in.

THE SEQUENCE THAT WORKS: start manual or maximise-clicks while you gather data, set up conversion tracking properly, then move to a conversion-based strategy once you have enough conversions for the system to learn from. Switching to Target CPA on day one with zero conversion history gives the algorithm nothing to optimise against.

This is a long video. The budget and bidding fundamentals come early; the AI-powered campaign material is useful later but not needed to run your first campaign.',
      'Look at any campaign you have, or one you plan, and answer two questions in writing. First: what is the single action on your site that means the ad worked — a form, a call, a purchase? Second: what is one of those actually worth to you in shillings? You cannot sensibly choose a bidding strategy without both answers, and most beginners have never written either one down.',
      '[{"question":"You choose Maximise Clicks and get 2,000 visitors but no enquiries. What went wrong?","options":["You asked Google to optimise for clicks, and it did exactly that","Google mis-spent your budget","Your daily budget was too low","The keywords were too specific"],"correct_index":0},{"question":"Why does automated bidding need conversion tracking?","options":["Without it the system has no signal telling it which clicks were valuable","It is required to activate the account","It reduces the cost per click","It makes ads load faster"],"correct_index":0}]'::jsonb)
  on conflict (module_id, order_number) do nothing;

  insert into public.modules (course_id, level_id, title, description, order_number) values
    (v_course_id, v_level, 'Did It Work? Conversion Tracking', 'Without this, you know what you spent and nothing about what you got. It is the difference between advertising and gambling.', v_module_offset + 2)
  returning id into v_m2;

  insert into public.lessons (module_id, title, description, youtube_url, order_number, learning_objectives, notes, practice_activity, knowledge_check) values
    (v_m2, 'Setting Up Conversion Tracking, Part 1', 'Google Ads'' official walkthrough of defining a conversion and creating the action in your account. Under 3 minutes.', 'https://www.youtube.com/watch?v=49bdV-OspYU', 1,
      array['Decide which action on your site counts as a conversion', 'Create a conversion action in Google Ads', 'Explain why clicks alone cannot tell you whether advertising worked'],
      'A CONVERSION is the thing you actually wanted — a form submitted, a call placed, a purchase, a WhatsApp click. Not a visit. A visit is somebody arriving; a conversion is somebody doing the thing.

WHY THIS IS THE MOST IMPORTANT SETUP STEP IN THE WHOLE COURSE: without it, your reports show spend, clicks and cost per click, and none of those tell you whether the money worked. Two campaigns can have identical click costs while one produces customers and the other produces nothing. Without conversion tracking they look the same, so you have no basis for deciding which to keep funding — and you will optimise toward whichever happens to be cheaper, which is often the worthless one.

CHOOSING WHAT TO COUNT. Pick actions with real business meaning: a completed contact form, a phone call over 30 seconds, a purchase, a booking. Avoid counting page views or time on site as conversions; they inflate your numbers and teach the bidding system to chase the wrong thing.

COUNT PRIMARY ACTIONS ONCE PER PERSON, per campaign, when it is a lead. Otherwise one enthusiastic person submitting a form three times looks like three customers.

A SECOND, QUIETER BENEFIT: once conversion data flows, the whole automated bidding layer becomes available. Every strategy worth using depends on this being in place first. Set it up before you spend meaningfully, not after.',
      'Write down the single action on your site that would make you say the advert worked. Just one, and be specific — "submits the quote form", not "gets interested". Then create that conversion action in Google Ads. If you have no site yet, write down what it would be for a business you know; the discipline of naming one specific action is most of the value.',
      '[{"question":"Why can''t clicks alone tell you whether a campaign worked?","options":["Two campaigns can cost the same per click while only one produces customers","Click counts are frequently inaccurate","Google hides click data from beginners","Clicks are only reported monthly"],"correct_index":0},{"question":"Which makes a good primary conversion action?","options":["A completed contact form or a purchase","A page view","Time spent on the site","An ad impression"],"correct_index":0}]'::jsonb),
    (v_m2, 'Setting Up Conversion Tracking, Part 2', 'The second half of Google Ads'' official walkthrough — getting the tag onto your site and confirming it actually fires. About 4 minutes.', 'https://www.youtube.com/watch?v=RHpP07zREM8', 2,
      array['Install the conversion tag on your site', 'Verify that a conversion records before you rely on the data', 'Recognise the signs that tracking is silently broken'],
      'Defining a conversion does nothing until the tag is on your site and firing. This half is where most setups quietly fail.

THE TAG has two parts: a global site tag on every page, and an event snippet on the moment the conversion happens — usually a thank-you page, or a click on a button. If you use a site builder or a tag manager, there is normally a field to paste this into rather than editing code.

VERIFY IT, DO NOT ASSUME IT. This is the step people skip and then regret. Complete the conversion yourself — fill in your own form, make the test purchase — and confirm it appears in Google Ads. It can take a few hours to show, so note the time you tested.

SIGNS TRACKING IS BROKEN, and every one of them looks like something else:

- ZERO CONVERSIONS after meaningful spend and traffic. Occasionally the campaign really is that bad. Far more often the tag is not firing, and you are about to "fix" a campaign that was working.
- A CONVERSION COUNT THAT MATCHES YOUR CLICK COUNT almost exactly. The tag is probably on every page rather than only the thank-you page, counting every visit.
- CONVERSIONS THAT STOPPED SUDDENLY on a date. Something changed on the site — a redesign, a plugin update, a new form — and dropped the tag.

GET THIS RIGHT BEFORE YOU SPEND SERIOUSLY. Broken tracking is worse than no tracking, because no tracking leaves you knowingly uncertain, while broken tracking leaves you confidently wrong — and the automated bidding system will optimise hard toward whatever nonsense it is being fed.',
      'Install the tag and then test it properly: complete the conversion yourself and check it records in Google Ads. Note the time you tested and check back a few hours later. If nothing appears, work through the three failure signs above before changing anything about the campaign itself — the campaign is almost certainly not the problem.',
      '[{"question":"Your conversion count is almost exactly equal to your click count. What is the likely cause?","options":["The event snippet is on every page rather than only the completion page","Your campaign is performing exceptionally well","Google is double-counting clicks","Your budget is set too high"],"correct_index":0},{"question":"Why is broken tracking worse than no tracking at all?","options":["It makes you confidently wrong, and automated bidding optimises toward the bad data","It costs more per click","It disables the account","It slows the website down"],"correct_index":0}]'::jsonb)
  on conflict (module_id, order_number) do nothing;

  -- Bring the shifted modules back, now sitting after the 2 new one(s).
  update public.modules set order_number = order_number - 1000 + 2
   where course_id = v_course_id and order_number > 1000;

end $$;
