-- Auto-generated by scripts/curriculum/build-level-sql.mjs -- do not
-- hand-edit the lesson content below; regenerate from the source plan
-- JSON instead if something needs to change.

do $$
declare
  v_course_id uuid := '89135a1d-1c9f-480a-8f26-50904226cdb1';
  v_level uuid;
  -- modules.order_number is unique per COURSE, not per level (a course's
  -- modules are numbered continuously across all its levels) -- so this
  -- can't just start at 1 for a level beyond the first. Computed here
  -- instead of hardcoded so this script works correctly regardless of how
  -- many modules the course already has.
  v_module_offset int;
  v_m1 uuid;
  v_m2 uuid;
begin
  -- Appending to a level that already exists. Looked up rather than
  -- inserted, so this adds to the learner's current Level 1 instead of
  -- creating a duplicate one, and no existing module is re-parented.
  select id into v_level from public.levels
    where course_id = v_course_id and order_number = 1;

  if v_level is null then
    raise exception 'Level % not found for course % -- refusing to guess', 1, v_course_id;
  end if;

  -- The new modules must sit INSIDE this level, not at the end of the
  -- course. getOrderedLessons() builds the learner's lesson sequence from
  -- modules.order_number alone and ignores level, so a module appended at
  -- the course's max order would put beginner content after the final
  -- level's material. Insert straight after this level's last module and
  -- shift everything below it down instead.
  select coalesce(max(order_number), 0) into v_module_offset
    from public.modules where level_id = v_level;

  -- Two-phase shift: (course_id, order_number) is unique, and a single
  -- "+ N" update can trip that constraint mid-statement, so park the rows
  -- out of range first and bring them back afterwards.
  update public.modules set order_number = order_number + 1000
   where course_id = v_course_id and order_number > v_module_offset;

  insert into public.modules (course_id, level_id, title, description, order_number) values
    (v_course_id, v_level, 'Deciding What to Post', 'The existing lessons cover what the job is and how to drive the scheduling tool. This one is about the harder question the tool cannot answer for you: what goes in it.', v_module_offset + 1)
  returning id into v_m1;

  insert into public.lessons (module_id, title, description, youtube_url, order_number, learning_objectives, notes, practice_activity, knowledge_check) values
    (v_m1, 'Building a Content Calendar', 'HubSpot on planning a month of social content in advance — what a calendar contains and how to fill it without staring at a blank page. Under 7 minutes.', 'https://www.youtube.com/watch?v=6Qj6MN4ig44', 1,
      array['Plan a month of posts in advance rather than deciding each morning', 'Use content pillars so you never start from a blank page', 'Explain why consistency beats occasional brilliance'],
      'The reason most social accounts go quiet is not laziness. It is that deciding what to post, every single day, while doing everything else, is exhausting. A calendar removes the daily decision.

CONTENT PILLARS are the trick that makes this manageable. Pick three to five recurring themes and rotate them. For a small business that might be: the product, a customer story, something useful about the industry, and something behind the scenes. Now you are never choosing from infinity — you are choosing from four, and each one has a familiar shape.

BATCHING is the second half. Sit down once and make two weeks of posts, rather than making one every day. Making ten posts takes far less than ten times making one, because the setup — the mindset, the tools, the photo session — happens once. Then schedule them and stop thinking about it.

WHAT A USABLE CALENDAR HAS, per row: date and time, platform, the actual copy, the image or video, any link, and whether it is drafted, scheduled or published. A spreadsheet is genuinely fine. The scheduling tool is where posts go once decided, not where you decide them.

CONSISTENCY BEATS BRILLIANCE. Three ordinary posts a week for a year outperforms a burst of excellent ones followed by two months of silence, because algorithms and audiences both reward showing up. Pick a cadence you can sustain on your worst week, not your best one.

AND LEAVE ROOM. Plan about 80% of the calendar and keep the rest open for whatever actually happens — a customer''s photo, a question worth answering, something topical. A fully-booked calendar makes you rigid; an empty one makes you silent.',
      'Write down three to five content pillars for one real account — yours or a business you know. Then fill a two-week calendar in a spreadsheet, rotating the pillars, with the actual caption text written out, not just a topic. Notice how much easier post nine is than post one. That drop in effort is the entire argument for batching.',
      '[{"question":"What problem do content pillars actually solve?","options":["You choose from three to five familiar themes instead of from infinity","They increase the algorithm''s reach","They remove the need for images","They let you post less often"],"correct_index":0},{"question":"Which posting pattern performs better over a year?","options":["Three ordinary posts a week, sustained","A burst of excellent posts, then two months of silence","One post a day for a month, then stopping","Posting only when something newsworthy happens"],"correct_index":0}]'::jsonb),
    (v_m1, 'Automating the Calendar So It Runs Itself', 'HubSpot on connecting your calendar to scheduling so planned posts actually go out without you pressing publish each time. About 8 minutes.', 'https://www.youtube.com/watch?v=CU_dWCB7k0s', 2,
      array['Move a planned calendar into a scheduler so posts publish on their own', 'Decide what should be automated and what must stay manual', 'Build a repeatable weekly routine rather than daily firefighting'],
      'Scheduling is where the calendar stops being a document and starts being a system. The existing Hootsuite lessons cover one tool''s buttons; this is about the workflow the buttons serve.

THE WEEKLY ROUTINE that most working social managers actually run:
- One planning block: fill next week''s calendar rows
- One production block: write the copy and make the images, all at once
- One scheduling block: load everything into the tool
- Short daily check-ins: reply to comments and messages

That is roughly half a day plus a few minutes daily, and it replaces the constant low-level anxiety of "I should post something".

WHAT TO AUTOMATE: the publishing. Evergreen posts, planned campaigns, recurring formats. Anything where the timing is a decision you have already made.

WHAT MUST STAY MANUAL, and this is the part automation guides skip:

REPLIES. Comments and DMs are where social media actually earns anything. An account that posts perfectly and never replies is a billboard. Automated replies read as automated and do damage.

ANYTHING TOPICAL OR SENSITIVE. Scheduled posts have no judgement. A cheerful promotional post going out automatically during a national tragedy or a company crisis is a well-documented way to embarrass a client. Whenever something serious happens, your first action is to pause the queue.

CLIENT-FACING CLAIMS. Prices, offers, dates — check them before they go out, not after.

THE RULE: automate the publishing, never the listening. Automation buys you the time to do the part that needs a human.',
      'Take the two-week calendar you built and schedule the first week into a real tool — Hootsuite, Buffer, Meta Business Suite, whichever you have. Then practise the thing that matters: find the pause or queue-stop control and use it. Knowing where that button is BEFORE you need it is the difference between a fast recovery and a scheduled post you cannot stop.',
      '[{"question":"Which part of social media management should never be automated?","options":["Replying to comments and messages","Publishing evergreen posts","Scheduling a planned campaign","Posting at a set time each week"],"correct_index":0},{"question":"Something serious happens in the news. What is your first action?","options":["Pause the scheduled queue before anything tone-deaf publishes","Post a comment about it immediately","Increase posting frequency","Nothing — scheduled posts adapt automatically"],"correct_index":0}]'::jsonb)
  on conflict (module_id, order_number) do nothing;

  insert into public.modules (course_id, level_id, title, description, order_number) values
    (v_course_id, v_level, 'Proving It Worked', 'The part that decides whether you keep the client. Posting is the work; showing what the work achieved is the job.', v_module_offset + 2)
  returning id into v_m2;

  insert into public.lessons (module_id, title, description, youtube_url, order_number, learning_objectives, notes, practice_activity, knowledge_check) values
    (v_m2, 'Reading Social Media Analytics', 'Google''s Digital Marketing programme on social media analytics and reporting — what the numbers mean and how to turn them into a report. About 27 minutes, so watch it in two sittings if data is tight.', 'https://www.youtube.com/watch?v=aEsWltLmPfc', 1,
      array['Tell a vanity metric from one that reflects business results', 'Read the standard analytics available on every platform', 'Connect a social metric to something the client actually cares about'],
      'Every platform hands you a wall of numbers. Most of them do not matter, and knowing which is most of the skill.

VANITY METRICS look impressive and change nothing. Follower count is the classic: ten thousand followers who never buy anything is worth less than two hundred who do. Impressions and likes are similar — pleasant, but they do not pay anyone.

METRICS THAT REFLECT SOMETHING REAL:
- ENGAGEMENT RATE — interactions divided by reach. Are the people who see it responding? Unlike raw likes, this is comparable across accounts of different sizes.
- SAVES AND SHARES — the strongest organic signals there are. A save means useful; a share means someone attached their own reputation to it.
- CLICK-THROUGHS — people leaving the platform for your site. The first step toward money.
- CONVERSIONS — enquiries, orders, bookings that came from social. The only number that ends the argument.
- FOLLOWER GROWTH RATE rather than total, because it shows direction.

THE CHAIN YOU ARE TRYING TO SHOW: posts get reach, reach produces engagement, engagement produces clicks, clicks produce customers. Any report that stops at the first link is describing activity rather than results.

BENCHMARK AGAINST YOURSELF. Industry averages are near-useless because they lump wildly different accounts together. Compare this month to last month, on the same account. That is the only fair comparison you have.

A NOTE THIS VIDEO DOES NOT COVER: much of Kenyan social commerce ends in a WhatsApp conversation, where no analytics dashboard follows. Ask new customers where they found you, and record the answer. That one question closes the gap between what your dashboard shows and what actually happened.',
      'Open the analytics on a real account and find five numbers: reach, engagement rate, saves, shares, and clicks. Then sort last month''s posts by engagement rate rather than likes, and look at the top three. Write one sentence on what they have in common. That sentence is worth more than the whole dashboard.',
      '[{"question":"Why is follower count considered a vanity metric?","options":["A large audience that never acts is worth less than a small one that does","It is difficult to measure accurately","Platforms report it incorrectly","It only counts for new accounts"],"correct_index":0},{"question":"What is the fairest benchmark for an account''s performance?","options":["The same account''s own previous months","Published industry averages","The largest competitor in the category","The platform''s global average"],"correct_index":0}]'::jsonb),
    (v_m2, 'Reporting to a Client So They Keep Paying', 'Sprout Social on the metrics worth tracking and how to package them into a report a client understands. About 9 minutes.', 'https://www.youtube.com/watch?v=GfqCod61qGA', 2,
      array['Choose the handful of metrics a specific client actually cares about', 'Write a report that explains rather than just lists numbers', 'Handle a month where results were poor'],
      'Clients do not renew because your engagement rate rose. They renew because they understand what they got. Reporting is not admin — it is the part of the job that keeps you employed.

START FROM THEIR GOAL, not from the dashboard. A restaurant wants bookings. A shop wants orders. A consultant wants enquiries. Pick the three to five metrics that connect to that, and leave the rest out. A report with forty numbers communicates less than one with five, because nobody knows which to look at.

THE SHAPE THAT WORKS:
1. One line at the top: what happened this month, in plain language
2. The three to five numbers, each with last month beside it
3. What worked — the two or three best posts and, crucially, WHY
4. What did not, honestly
5. What you will do differently next month

Section 3 is where you demonstrate skill. "Engagement was up 40%" is a fact. "Engagement was up 40%, driven by the customer-story posts, so I am doubling those next month" is a professional making decisions — and that is what they are paying for.

HANDLE BAD MONTHS DIRECTLY. Results fluctuate; everyone knows it. Say what happened, say what you think caused it, say what you are changing. A freelancer who reports a bad month honestly and with a plan is more trustworthy than one whose numbers only ever rise. The client will find out anyway.

BE CONSISTENT AND ON TIME. Same format, same day each month. Predictability reads as competence, and it means they never have to chase you — which is, quietly, one of the most common reasons clients leave.

AND KEEP THEM. Your own reports across several clients become the portfolio that wins the next one.',
      'Write one month''s report for a real or imagined client, in the five-section shape above, on a single page. Force yourself to pick only four metrics, chosen from what that specific client wants rather than what is easy to measure. Then include one honest negative and what you would change. Read it back as if you were the client paying the invoice.',
      '[{"question":"Which section of a client report best demonstrates your skill?","options":["Explaining WHY the best posts worked and what you will do about it","The complete list of every metric available","The total follower count","A screenshot of the dashboard"],"correct_index":0},{"question":"Results were poor this month. What is the professional move?","options":["Report it honestly with your read on the cause and what you will change","Emphasise the metrics that did rise and omit the rest","Skip the report this month","Extend the date range until the numbers look better"],"correct_index":0}]'::jsonb)
  on conflict (module_id, order_number) do nothing;

  -- Bring the shifted modules back, now sitting after the 2 new one(s).
  update public.modules set order_number = order_number - 1000 + 2
   where course_id = v_course_id and order_number > 1000;

end $$;
