-- Auto-generated by scripts/curriculum/build-level-sql.mjs -- do not
-- hand-edit the lesson content below; regenerate from the source plan
-- JSON instead if something needs to change.

do $$
declare
  v_course_id uuid := '9fc81ee6-12bf-4000-8495-07ad815fbdb4';
  v_level uuid;
  -- modules.order_number is unique per COURSE, not per level (a course's
  -- modules are numbered continuously across all its levels) -- so this
  -- can't just start at 1 for a level beyond the first. Computed here
  -- instead of hardcoded so this script works correctly regardless of how
  -- many modules the course already has.
  v_module_offset int;
  v_m1 uuid;
  v_m2 uuid;
begin
  -- Appending to a level that already exists. Looked up rather than
  -- inserted, so this adds to the learner's current Level 1 instead of
  -- creating a duplicate one, and no existing module is re-parented.
  select id into v_level from public.levels
    where course_id = v_course_id and order_number = 1;

  if v_level is null then
    raise exception 'Level % not found for course % -- refusing to guess', 1, v_course_id;
  end if;

  -- The new modules must sit INSIDE this level, not at the end of the
  -- course. getOrderedLessons() builds the learner's lesson sequence from
  -- modules.order_number alone and ignores level, so a module appended at
  -- the course's max order would put beginner content after the final
  -- level's material. Insert straight after this level's last module and
  -- shift everything below it down instead.
  select coalesce(max(order_number), 0) into v_module_offset
    from public.modules where level_id = v_level;

  -- Two-phase shift: (course_id, order_number) is unique, and a single
  -- "+ N" update can trip that constraint mid-statement, so park the rows
  -- out of range first and bring them back afterwards.
  update public.modules set order_number = order_number + 1000
   where course_id = v_course_id and order_number > v_module_offset;

  insert into public.modules (course_id, level_id, title, description, order_number) values
    (v_course_id, v_level, 'Making Decisions and Holding Data', 'The existing lessons cover setup, variables and loops. A program that cannot make a decision or hold a collection of things is not yet a program — these are the two pieces that were missing.', v_module_offset + 1)
  returning id into v_m1;

  insert into public.lessons (module_id, title, description, youtube_url, order_number, learning_objectives, notes, practice_activity, knowledge_check) values
    (v_m1, 'if, elif and else — Making the Program Choose', 'Microsoft''s own Python for Beginners series on conditional logic: how a program takes one path or another. Under 5 minutes.', 'https://www.youtube.com/watch?v=5pPKYWqkoek', 1,
      array['Write an if / elif / else block that runs the right branch', 'Compare values correctly, including the == versus = trap', 'Combine conditions with and, or and not'],
      'Variables store things and loops repeat things. Conditionals are how a program decides — and almost every useful program is mostly decisions.

THE SHAPE:

    age = 20
    if age >= 18:
        print("Adult")
    elif age >= 13:
        print("Teenager")
    else:
        print("Child")

Python runs the FIRST branch whose condition is true and skips the rest. That is why order matters: put the most specific condition first, or a broader one above it will catch everything.

THE MISTAKE EVERY BEGINNER MAKES: one equals sign assigns, two compare.
- `age = 18` means "set age to 18"
- `age == 18` means "is age equal to 18?"
Use `=` where you meant `==` and Python raises a syntax error inside an if — which is a mercy, because in some other languages it silently does the wrong thing.

THE COMPARISONS: `==` equal, `!=` not equal, `<` `>` `<=` `>=`. On text, `==` is case-sensitive: `"Yes" == "yes"` is False. Comparing user input almost always wants `.lower()` first.

COMBINING CONDITIONS with `and` (both must be true), `or` (either), `not` (flips it):

    if balance >= price and item_in_stock:
        print("Sale complete")

INDENTATION IS THE SYNTAX. In most languages braces mark the block; in Python the indentation IS the block, and getting it wrong changes what the program does rather than merely looking untidy. Four spaces, consistently. Let your editor insert them.

AND WATCH FOR THE COLON at the end of the `if` line. A missing colon is the single most common beginner error message you will see.',
      'Write a short program that asks for a number with `input()`, converts it with `int()`, and prints whether it is negative, zero, or positive — three branches. Then extend it: print "big" if the number is positive AND over 100. Finally, deliberately swap one `==` for `=` and read the error message carefully, so you recognise it instantly when it happens for real.',
      '[{"question":"What does `==` do that `=` does not?","options":["It compares two values; a single = assigns a value to a variable","It assigns a value; == only works on numbers","They are interchangeable in Python","It converts text to a number before comparing"],"correct_index":0},{"question":"In an if / elif / else chain, which branch runs?","options":["The first one whose condition is true; the rest are skipped","Every branch whose condition is true","The last one whose condition is true","Only the else branch if nothing matches earlier"],"correct_index":0}]'::jsonb),
    (v_m1, 'Lists and Dictionaries — Holding More Than One Thing', 'Microsoft''s Python for Beginners on collections: storing many values in one variable and getting them back out. About 11 minutes.', 'https://www.youtube.com/watch?v=beA8IsY3mQs', 2,
      array['Create a list, read an item by index, and add or remove items', 'Use a dictionary to store labelled values instead of positions', 'Loop over a collection to do something with every item'],
      'One variable per value stops working the moment you have thirty students or a hundred prices. Collections are how real programs hold data.

A LIST is an ordered sequence:

    prices = [50, 120, 75]
    prices.append(200)     # add to the end
    print(prices[0])       # 50 — the FIRST item
    print(len(prices))     # 4

INDEXES START AT ZERO. `prices[0]` is the first item and `prices[3]` is the fourth. Asking for `prices[4]` on a four-item list raises IndexError — the classic off-by-one, and you will meet it today.

A DICTIONARY stores values under names instead of positions:

    student = {"name": "Amina", "score": 82}
    print(student["name"])           # Amina
    student["score"] = 90            # change it
    print(student.get("age", "unknown"))   # safe: no crash if absent

Use `.get()` when a key might be missing. `student["age"]` raises KeyError and stops your program; `.get()` hands back a default instead.

WHICH TO USE: a list when order matters and the items are the same kind of thing (all the prices, all the names). A dictionary when each value means something different (name, score, phone). Real data is usually both — a LIST of DICTIONARIES is the single most common shape you will handle:

    students = [
        {"name": "Amina", "score": 82},
        {"name": "Otieno", "score": 75},
    ]
    for s in students:
        print(s["name"], s["score"])

That loop is where lists, dictionaries and the loops from the earlier lesson finally click together. Once this pattern is comfortable, you can process a spreadsheet, an API response, or a database result — they all arrive looking like this.',
      'Build a list of at least four dictionaries, one per person, each with a name and a score. Loop over it and print each name with its score. Then add two things: print only the people scoring above 70, and print the average of all scores. Finally, ask for a key that does not exist to see KeyError, then rewrite that line with `.get()` and a default.',
      '[{"question":"`prices = [50, 120, 75]`. What does `prices[1]` return?","options":["120 — indexes start at 0, so [1] is the second item","50, the first item","75, counting from the end","An IndexError"],"correct_index":0},{"question":"Why use `student.get(\"age\", \"unknown\")` instead of `student[\"age\"]`?","options":["It returns a default instead of raising KeyError when the key is missing","It is faster on large dictionaries","It allows the key to be changed later","It converts the value to text"],"correct_index":0}]'::jsonb)
  on conflict (module_id, order_number) do nothing;

  insert into public.modules (course_id, level_id, title, description, order_number) values
    (v_course_id, v_level, 'Functions, and Code That Survives Bad Input', 'How to stop repeating yourself, and how to keep a program running when something goes wrong — which, with real users and real files, it will.', v_module_offset + 2)
  returning id into v_m2;

  insert into public.lessons (module_id, title, description, youtube_url, order_number, learning_objectives, notes, practice_activity, knowledge_check) values
    (v_m2, 'Writing Your Own Functions', 'Microsoft''s Python for Beginners on functions: naming a piece of work once and calling it wherever you need it. About 10 minutes.', 'https://www.youtube.com/watch?v=nrCAxXfRU28', 1,
      array['Define a function and call it from elsewhere in your program', 'Pass values in as parameters and return a result', 'Recognise repeated code as a signal to write a function'],
      'A function is a named piece of work you can run whenever you want. It is the first real step from writing scripts to writing programs.

    def greet(name):
        return "Habari, " + name + "!"

    print(greet("Amina"))

FOUR PARTS: `def`, a name, parameters in brackets, and the indented body. `return` hands a value back to whoever called it.

RETURN IS NOT PRINT, and this confuses almost everyone at first. `print` shows something on the screen and the value is then gone. `return` hands the value back so your code can use it — store it, compare it, put it in a list. A function that prints instead of returning is a dead end; you cannot do anything further with the result. Write functions that RETURN, and print at the point where you actually want to show something.

PARAMETERS versus ARGUMENTS: `name` in the definition is the parameter; `"Amina"` at the call is the argument. Same idea, different sides of the line.

A function with no `return` gives back `None`, which is Python''s word for nothing. If your function seems to "return None" unexpectedly, you almost certainly forgot the return.

WHEN TO WRITE ONE: the moment you copy and paste code for the second time. Two copies means two places to fix a bug, and you will fix one and forget the other. A function means one place.

GOOD FUNCTIONS DO ONE THING and are named for what they produce — `calculate_total`, `is_valid_email`, `format_phone_number`. A verb plus a noun. If you struggle to name it, it probably does more than one thing and should be two functions.

AND KEEP THEM SHORT. If a function no longer fits on your screen, it is asking to be split.',
      'Take a script you have already written and pull out one piece into a function that takes a parameter and RETURNS a result — not one that prints. Call it twice with different inputs. Then write a second function, `average(numbers)`, that takes a list and returns the mean, and use it on the list of scores from the earlier lesson. Confirm you can store the result in a variable — that is the proof it returned rather than printed.',
      '[{"question":"What is the practical difference between return and print?","options":["return hands the value back so your code can use it; print only displays it and discards it","They do the same thing, print is shorthand","return only works with numbers","print is faster inside functions"],"correct_index":0},{"question":"What is the clearest signal that you should write a function?","options":["You are copying and pasting the same code a second time","Your file is over 50 lines","You are using a loop","You have more than three variables"],"correct_index":0}]'::jsonb),
    (v_m2, 'Handling Errors Instead of Crashing', 'Microsoft''s Python for Beginners on error handling — try, except, and what to do when something fails. About 13 minutes.', 'https://www.youtube.com/watch?v=HQqqNBZosn8', 2,
      array['Wrap risky code in try / except so a failure does not stop the program', 'Catch the specific error you expect rather than everything', 'Read a traceback and find the line that actually broke'],
      'Every program that touches a user, a file or a network will be handed something it did not expect. Error handling is the difference between a program that copes and one that dies.

    try:
        age = int(input("Your age: "))
        print("Next year you will be", age + 1)
    except ValueError:
        print("Please type a number, like 25.")

Without the try, someone typing "twenty" crashes the whole thing with a wall of red text. With it, they get a sentence they can act on.

CATCH THE SPECIFIC ERROR. A bare `except:` catches everything — including your own typos and bugs — and hides them, so the program carries on quietly doing the wrong thing. That is worse than crashing, because a crash at least tells you where it broke. Name the error you actually expect: ValueError, KeyError, FileNotFoundError, ZeroDivisionError.

READ THE TRACEBACK FROM THE BOTTOM. Python prints the chain of calls, and beginners read the top and panic. The LAST line names the error type and message; the line just above it points at the file and line number where it happened. Those two lines answer most questions immediately.

THE ERRORS YOU WILL ACTUALLY MEET:
- ValueError — `int("twenty")`, converting something unconvertible
- TypeError — `"5" + 5`, mixing text and numbers
- IndexError — reading past the end of a list
- KeyError — a dictionary key that is not there
- FileNotFoundError — the path is wrong, and it usually is

DO NOT WRAP EVERYTHING. Handle errors where you can genuinely do something about them — retry, use a default, tell the user what to fix. An error you cannot act on should be allowed to crash loudly during development; that is how you find out about it.

AN ERROR MESSAGE IS A GIFT. It names the problem and the line. Read it before searching the internet — most of the time it already told you the answer.',
      'Write a small program that keeps asking for a number until it gets a valid one, using a loop with try / except ValueError inside. Then deliberately trigger three different errors: divide by zero, read a list index that does not exist, and open a file that is not there. For each, read the traceback and write down the last line and the line number. That habit will save you more time than any other in this course.',
      '[{"question":"Why is a bare `except:` a bad idea?","options":["It hides your own bugs and typos, so the program continues doing the wrong thing silently","It is slower than naming the error","It only works inside functions","Python does not allow it"],"correct_index":0},{"question":"Where in a traceback is the most useful information?","options":["The last line — the error type and message — and the line just above it, which gives file and line number","The first line, which names the program","The middle of the stack, which shows Python internals","Tracebacks do not indicate where the error occurred"],"correct_index":0}]'::jsonb)
  on conflict (module_id, order_number) do nothing;

  -- Bring the shifted modules back, now sitting after the 2 new one(s).
  update public.modules set order_number = order_number - 1000 + 2
   where course_id = v_course_id and order_number > 1000;

end $$;
