-- Auto-generated by scripts/curriculum/build-level-sql.mjs -- do not
-- hand-edit the lesson content below; regenerate from the source plan
-- JSON instead if something needs to change.

do $$
declare
  v_course_id uuid := '34b18a07-cbf0-48d6-82be-bbbc9033b7e5';
  v_level uuid;
  -- modules.order_number is unique per COURSE, not per level (a course's
  -- modules are numbered continuously across all its levels) -- so this
  -- can't just start at 1 for a level beyond the first. Computed here
  -- instead of hardcoded so this script works correctly regardless of how
  -- many modules the course already has.
  v_module_offset int;
  v_m1 uuid;
  v_m2 uuid;
begin
  -- Appending to a level that already exists. Looked up rather than
  -- inserted, so this adds to the learner's current Level 1 instead of
  -- creating a duplicate one, and no existing module is re-parented.
  select id into v_level from public.levels
    where course_id = v_course_id and order_number = 1;

  if v_level is null then
    raise exception 'Level % not found for course % -- refusing to guess', 1, v_course_id;
  end if;

  -- The new modules must sit INSIDE this level, not at the end of the
  -- course. getOrderedLessons() builds the learner's lesson sequence from
  -- modules.order_number alone and ignores level, so a module appended at
  -- the course's max order would put beginner content after the final
  -- level's material. Insert straight after this level's last module and
  -- shift everything below it down instead.
  select coalesce(max(order_number), 0) into v_module_offset
    from public.modules where level_id = v_level;

  -- Two-phase shift: (course_id, order_number) is unique, and a single
  -- "+ N" update can trip that constraint mid-statement, so park the rows
  -- out of range first and bring them back afterwards.
  update public.modules set order_number = order_number + 1000
   where course_id = v_course_id and order_number > v_module_offset;

  insert into public.modules (course_id, level_id, title, description, order_number) values
    (v_course_id, v_level, 'The Operating System, Which Is Most of the Job', 'The existing lessons cover what the role is and what hardware is inside a machine. Almost every ticket you will ever handle, though, is a software problem — so this is the operating system, from Google''s own IT Support Certificate.', v_module_offset + 1)
  returning id into v_m1;

  insert into public.lessons (module_id, title, description, youtube_url, order_number, learning_objectives, notes, practice_activity, knowledge_check) values
    (v_m1, 'What an Operating System Actually Does', 'Google''s IT Support Certificate on how an operating system is put together and what it manages. About 36 minutes — long, so plan a sitting for it.', 'https://www.youtube.com/watch?v=7CrfA-ukRe4', 1,
      array['Describe what the kernel, drivers and user space each do', 'Explain how the OS manages memory, processes and hardware', 'Use that model to reason about why a machine is slow or unresponsive'],
      'This lesson runs about 36 minutes and it is worth the data. Everything you will be asked to fix — a slow laptop, a printer that will not print, an application that crashes — is the operating system doing something you can understand once you know how it is built.

A NOTE ON LENGTH before you start: this and the next three lessons come from Google''s IT Support Certificate and each runs half an hour or more. On a mobile bundle that is real money. Download over Wi-Fi where you can, and treat one lesson as one sitting rather than trying to do the module in an evening.

WHAT AN OPERATING SYSTEM IS: the layer between the hardware and everything a person actually uses. It decides which program gets the processor, how memory is shared, how files are stored, and how a keyboard or printer is spoken to.

THE PARTS THAT MATTER FOR SUPPORT WORK:

THE KERNEL is the core. It talks to hardware and allocates resources. When people say a machine has "frozen", something has usually gone wrong between an application and the kernel.

DRIVERS are the translators between the OS and a specific piece of hardware. An enormous share of real support tickets — printers, webcams, Wi-Fi adapters, external monitors — come down to a missing, outdated or wrong driver. Learning to check Device Manager on Windows will resolve more tickets than any other single skill at this level.

PROCESSES are running programs. Task Manager on Windows and Activity Monitor on macOS show them, with what each is using. "The computer is slow" is answered here: one process eating the processor, or memory exhausted and the machine swapping to disk.

MEMORY MANAGEMENT is why a machine with too little RAM slows to a crawl rather than simply refusing — it starts using the disk as overflow, which is dramatically slower.

USER ACCOUNTS AND PERMISSIONS decide who may change what. A great many "it will not let me" tickets are a permissions issue, not a fault.

AND KNOW ALL THREE FAMILIES. Windows dominates offices, macOS shows up in design and media, Linux runs most servers. A Kenyan help desk will mostly be Windows, but the concepts here are the same everywhere, which is exactly why the certificate teaches them this way.',
      'On any computer you can use, open Task Manager (Ctrl+Shift+Esc on Windows) or Activity Monitor. Sort by CPU and note the top three processes; then sort by memory and do the same. Write down what is actually consuming the machine. Then open Device Manager (Windows) or System Information (macOS) and find one device and its driver. Being able to reach both screens without hunting is a real, employable skill.',
      '[{"question":"A user says their printer stopped working after a Windows update. What is the most likely cause at this level?","options":["A driver problem — the translator between the OS and that hardware","The printer''s power supply has failed","The kernel has been corrupted","The user''s account was deleted"],"correct_index":0},{"question":"Why does a machine with too little RAM become extremely slow rather than simply stopping?","options":["The OS starts using the disk as overflow memory, which is far slower","The processor reduces its speed to protect itself","The kernel shuts down background drivers","The network adapter throttles the connection"],"correct_index":0}]'::jsonb),
    (v_m1, 'The Command Line, and Why Support Staff Use It', 'Google''s IT Support Certificate on using the command line — the tool that separates someone who clicks around from someone who fixes things quickly. About 33 minutes.', 'https://www.youtube.com/watch?v=xg_1UjZqMdQ', 2,
      array['Navigate the filesystem and manage files from a terminal', 'Explain why the command line is faster and more reliable for support tasks', 'Read a command someone gives you before running it'],
      'About 33 minutes, and the single most employable half hour in this course. Everyone applying for a help-desk job says they are "good with computers". Being comfortable at a command line is what makes that claim checkable.

WHY IT MATTERS IN SUPPORT, concretely:
- It works over a remote connection when a desktop is too slow to use
- It does the same thing to two hundred machines through a script
- It reaches diagnostics that have no window — network configuration, running services, system logs
- It is exactly what the person senior to you will tell you to type

THE IDEAS THAT TRANSFER between Windows and Linux even though the commands differ: you are always somewhere in the filesystem; commands take options that change their behaviour; and output can be piped from one command into another.

COMMANDS WORTH KNOWING ON DAY ONE. On Windows: `ipconfig` for network settings, `ping` to test whether something is reachable, `tasklist` for running processes, `sfc /scannow` to check system files. On Linux and macOS: `ls`, `cd`, `pwd`, `cat`, `ping`, `top`, and `df -h` for disk space full.

THE HABIT THAT MATTERS MOST, and it is a safety habit: READ A COMMAND BEFORE YOU RUN IT. The command line does exactly what you say, immediately, with no confirmation dialogue and no undo. Deleting the wrong directory is instant and permanent. Never paste a command from a forum or a chatbot into a production machine without understanding each part of it — this is how real damage gets done by well-meaning junior staff, and it is also the difference between being trusted with access and not.

BE ESPECIALLY CAREFUL with anything containing a wildcard, anything run with administrator or `sudo` rights, and anything that formats or deletes. If you are unsure, ask. Nobody has ever been sacked for asking; people have been sacked for the other thing.

AND WRITE DOWN WHAT YOU RAN. When a fix works, the command you used is worth more than the memory of it — that note becomes your own runbook, and a support person with a runbook is fast.',
      'Open Command Prompt or Terminal and do five things: find where you are, list what is there, move into another folder, check your network settings (`ipconfig` or `ifconfig`), and ping a website to see whether it responds. Write each command and its result in a notes file. That file is the beginning of the runbook you will use in an actual job.',
      '[{"question":"Why is reading a command before running it a safety habit rather than a preference?","options":["The command line executes immediately, with no confirmation and no undo","Commands are logged and reviewed by employers","Typing errors damage the keyboard buffer","The terminal cannot display long commands"],"correct_index":0},{"question":"Why does a support technician use the command line when a desktop interface exists?","options":["It works remotely, scales to many machines and reaches diagnostics that have no window","It uses less electricity","Desktop interfaces cannot manage files","It is the only way to install software"],"correct_index":0}]'::jsonb)
  on conflict (module_id, order_number) do nothing;

  insert into public.modules (course_id, level_id, title, description, order_number) values
    (v_course_id, v_level, 'How Devices Talk to Each Other', 'The other half of the tickets. "The internet is down" is the most common support call there is, and answering it well needs a model of what is actually happening.', v_module_offset + 2)
  returning id into v_m2;

  insert into public.lessons (module_id, title, description, youtube_url, order_number, learning_objectives, notes, practice_activity, knowledge_check) values
    (v_m2, 'How Computers Communicate in a Network', 'Google''s IT Support Certificate on networking fundamentals — how one machine reaches another. About 41 minutes; plan a full sitting.', 'https://www.youtube.com/watch?v=Z_hU2zm4_S8', 1,
      array['Explain what an IP address, a MAC address and a port are for', 'Describe the path a request takes from a computer to a server', 'Work through a connectivity problem in a sensible order'],
      'About 41 minutes. Networking is the subject that intimidates beginners most and it is mostly a small number of ideas repeated.

THE ADDRESSES, and why there are several:
- A MAC ADDRESS identifies a physical network adapter. It does not change and it only matters on the local network.
- An IP ADDRESS identifies a machine on a network and can change. Your laptop has a private one on the office network and shares a public one with everyone else behind that router.
- A PORT identifies which service on that machine — web traffic on 80 and 443, email on others. One address, many doors.

WHAT HAPPENS WHEN YOU OPEN A WEBSITE, in order, because this order IS your troubleshooting order: your machine looks up the name through DNS to get an address; it sends the request to your router; the router forwards it out through your provider; it crosses the internet to the server; the reply comes back the same way.

SO WHEN SOMEONE SAYS "THE INTERNET IS DOWN", work along that path rather than guessing:
1. Is the cable in, or is Wi-Fi actually connected?
2. Does the machine have a sensible IP address? An address starting 169.254 means it never got one from the router — that is a DHCP problem, and it is a common answer.
3. Can you ping the router?
4. Can you ping an outside address, like 8.8.8.8? If that works but names do not resolve, it is DNS — which is by far the most common cause of "the internet is broken" while the connection is fine.
5. Is it one machine or everyone? That single question separates a device problem from a network problem, and asking it first saves an hour.

THIS ORDERED APPROACH IS THE ACTUAL SKILL, and it is worth stating plainly because the video teaches the concepts rather than the method: identify the problem, ask what changed, form one theory, test that theory, then fix it and write down what it was. Changing five things at once and finding it works teaches you nothing and is not repeatable.

A KENYAN NOTE THE COURSE DOES NOT COVER: on a mobile-data or router-shared connection, "slow internet" is often a bundle that has run out or been throttled rather than a fault. Check the data balance before you rebuild anyone''s network settings.',
      'On your own machine, find your IP address, your router''s address (the default gateway) and your DNS servers. Then walk the path deliberately: ping your router, ping 8.8.8.8, then ping a website by name. Note which succeed. Finally, do it once while deliberately disconnected, and watch exactly which step fails first — that is what a real fault looks like.',
      '[{"question":"A machine can ping 8.8.8.8 but cannot open any website by name. What is the problem?","options":["DNS — the connection works but names are not resolving to addresses","The network cable is unplugged","The router has failed","The machine has no IP address"],"correct_index":0},{"question":"What is the most useful first question when someone reports the internet is down?","options":["Is it just this machine, or is everyone affected?","Which browser are you using?","When did you last restart?","What is your password?"],"correct_index":0}]'::jsonb),
    (v_m2, 'How Devices Connect to the Internet', 'Google''s IT Support Certificate on the connection itself — routers, providers and what sits between a device and the wider internet. About 47 minutes, so watch it in two parts.', 'https://www.youtube.com/watch?v=JgxUD5X_Pe4', 2,
      array['Describe the equipment between a device and the internet and what each does', 'Explain what a router does that a switch does not', 'Diagnose whether a fault is inside the building or with the provider'],
      'This one runs about 47 minutes — longer than any other lesson here. WATCH IT IN TWO SITTINGS, and download it over Wi-Fi if you can, because on a mobile bundle a video this long is a real cost.

THE EQUIPMENT, and what each piece actually does:
- A SWITCH connects devices within one local network and passes traffic between them.
- A ROUTER connects one network to another — in practice, your network to the internet. It is the boundary, which is why so much troubleshooting happens at it.
- A MODEM converts between the signal your provider sends and something the network understands. In most homes and small offices these are one box, which is why people call the whole thing "the router".
- AN ACCESS POINT is the Wi-Fi radio. Often the same box again.

NAT AND PRIVATE ADDRESSES: everything inside your network has a private address, and the router translates them to share one public address. This is why every device in the building appears to the outside world as the same address, and why you cannot reach a machine inside a network directly from outside without deliberately configuring it.

WHERE IS THE FAULT — inside or outside? This is the question your employer actually needs answered, because one you fix and the other you report:
- Can devices reach each other on the local network, but nothing external? The problem is at the router or beyond.
- Is it only Wi-Fi devices, while a cabled machine works? The access point or the wireless configuration.
- Do the router''s own status lights indicate no service? That is the provider, and the correct action is to log it, not to reconfigure anything.

WI-FI PROBLEMS ARE OFTEN PHYSICS, not configuration. Distance, walls, and a neighbourhood full of routers on the same channel all degrade a connection that is set up perfectly. Moving the access point higher and away from metal and microwaves genuinely helps.

AND FOR THE KENYAN CONTEXT: many small offices run on a router with a SIM, or share a connection over a mobile hotspot, and power cuts are a real and frequent cause of "the network is down" — the equipment has restarted and something did not come back. Check power and check the provider''s status before you touch a setting. Writing down the working configuration BEFORE a power cut is a small habit that saves whole mornings.',
      'Find the router on any network you are allowed to look at. Note its make, its address, and what its status lights indicate. Then answer three questions in writing: can two devices on this network reach each other, can they reach the internet, and does anything change when you use a cable instead of Wi-Fi? That three-step check is the shape of a real diagnosis, and it tells you whether you are fixing this or phoning the provider.',
      '[{"question":"What does a router do that a switch does not?","options":["Connect one network to another — it is the boundary between your network and the internet","Provide Wi-Fi to wireless devices","Assign MAC addresses to devices","Convert electrical signals into light"],"correct_index":0},{"question":"Devices on the local network can reach each other but nothing outside. Where is the fault?","options":["At the router or beyond it, with the provider","On each individual device","In the network switch","In the DNS settings of one machine"],"correct_index":0}]'::jsonb)
  on conflict (module_id, order_number) do nothing;

  -- Bring the shifted modules back, now sitting after the 2 new one(s).
  update public.modules set order_number = order_number - 1000 + 2
   where course_id = v_course_id and order_number > 1000;

end $$;
