-- Auto-generated by scripts/curriculum/build-level-sql.mjs -- do not
-- hand-edit the lesson content below; regenerate from the source plan
-- JSON instead if something needs to change.

do $$
declare
  v_course_id uuid := '7f18ca03-8566-4b29-bb46-6ed9a392e175';
  v_level uuid;
  -- modules.order_number is unique per COURSE, not per level (a course's
  -- modules are numbered continuously across all its levels) -- so this
  -- can't just start at 1 for a level beyond the first. Computed here
  -- instead of hardcoded so this script works correctly regardless of how
  -- many modules the course already has.
  v_module_offset int;
  v_m1 uuid;
  v_m2 uuid;
begin
  -- Appending to a level that already exists. Looked up rather than
  -- inserted, so this adds to the learner's current Level 1 instead of
  -- creating a duplicate one, and no existing module is re-parented.
  select id into v_level from public.levels
    where course_id = v_course_id and order_number = 1;

  if v_level is null then
    raise exception 'Level % not found for course % -- refusing to guess', 1, v_course_id;
  end if;

  -- The new modules must sit INSIDE this level, not at the end of the
  -- course. getOrderedLessons() builds the learner's lesson sequence from
  -- modules.order_number alone and ignores level, so a module appended at
  -- the course's max order would put beginner content after the final
  -- level's material. Insert straight after this level's last module and
  -- shift everything below it down instead.
  select coalesce(max(order_number), 0) into v_module_offset
    from public.modules where level_id = v_level;

  -- Two-phase shift: (course_id, order_number) is unique, and a single
  -- "+ N" update can trip that constraint mid-statement, so park the rows
  -- out of range first and bring them back afterwards.
  update public.modules set order_number = order_number + 1000
   where course_id = v_course_id and order_number > v_module_offset;

  insert into public.modules (course_id, level_id, title, description, order_number) values
    (v_course_id, v_level, 'Having Something Worth Saying', 'The existing lessons deal with nerves and body language — how you appear. This one is about what you actually say, which is the part that decides whether anyone remembers it.', v_module_offset + 1)
  returning id into v_m1;

  insert into public.lessons (module_id, title, description, youtube_url, order_number, learning_objectives, notes, practice_activity, knowledge_check) values
    (v_m1, 'Building a Talk Around One Idea', 'Chris Anderson, who runs TED, on what every good talk has in common. Under 8 minutes.', 'https://www.youtube.com/watch?v=-FOCpMAww28', 1,
      array['Reduce a talk to one idea a listener can carry away', 'Build that idea step by step from what your audience already knows', 'Recognise the four styles that make a talk fail'],
      'This is a talk rather than a tutorial, so the work of turning it into a method is here in the notes.

THE CENTRAL CLAIM: your only real job is to build ONE idea inside the listener''s mind. Not to impress them, not to cover everything you know — one idea, constructed piece by piece out of things they already understand.

HOW TO FIND YOUR ONE IDEA: finish this sentence in fifteen words or fewer — "If they remember nothing else, they should remember that...". If you cannot, you are not ready to speak yet. Everything in the talk either builds that sentence or comes out.

BUILD FROM WHAT THEY KNOW. You cannot install an idea directly; you assemble it from parts the listener already has. Start with something familiar, then move one step at a time. Every unexplained term is a listener left behind, and once someone is lost they stay lost — they do not catch up, they disengage.

CURIOSITY IS WHAT KEEPS THEM WITH YOU. Open a question in their mind before you answer it. "Last year I lost a client over one sentence in an email" earns you the next ninety seconds far better than "Today I will discuss client communication".

THE FOUR WAYS TALKS FAIL, and they are all recognisable:
- THE SALES PITCH. The moment an audience senses they are being sold to, goodwill collapses.
- THE RAMBLE, with no destination, where everyone quietly checks their phone.
- THE ORGANISATION SPEECH — a talk about your company rather than an idea. Nobody outside it cares.
- PERFORMANCE FOR ITS OWN SAKE, impressive and empty.

STRUCTURE THAT WORKS for almost any short talk: the situation, the problem or turning point, what you learned, and what the listener should do with it. Four parts, and it fits five minutes or twenty.

AND CUT RUTHLESSLY. Almost every first draft is twice as long as it should be. The talk that lands is the one where everything not serving the one idea has been removed — including the good bits you are proud of.

FOR A KENYAN AUDIENCE SPECIFICALLY: think about which examples actually land. A comparison drawn from M-Pesa, matatu routes or a local business connects instantly where a Silicon Valley story asks the listener to do extra work before they can follow you.',
      'Take a talk you might genuinely give — at work, at a community group, in a pitch — and write your one idea in fifteen words or fewer. Then list everything you were planning to say and cross out every item that does not build that sentence. Count what you cut. Finally, write the first two sentences so that they open a question rather than announce a topic.',
      '[{"question":"What is the speaker''s only real job, according to this talk?","options":["To build one idea in the listener''s mind, out of things they already understand","To cover the topic comprehensively","To appear confident and authoritative","To entertain the audience for the full time slot"],"correct_index":0},{"question":"Why does an unexplained technical term cost you more than it seems?","options":["A listener who gets lost does not catch up — they disengage","It makes the talk run longer","Audiences find it rude","It reduces the number of questions afterwards"],"correct_index":0}]'::jsonb),
    (v_m1, 'Telling a Story That Holds Attention', 'TED on the structure of a story that works in under a minute — the shape that makes people stay. About 4 minutes.', 'https://www.youtube.com/watch?v=ZmNpeXTj2c4', 2,
      array['Open in a way that earns the next thirty seconds', 'Structure a short story with tension and a payoff', 'Use a specific example instead of a general claim'],
      'Attention is the whole game, and it is decided in the first few seconds — in a meeting, a pitch, a WhatsApp voice note or on stage.

START IN THE MIDDLE OF SOMETHING. "I want to talk about the importance of follow-up" loses. "The client had already signed with someone else by the time I replied" wins, because the listener immediately wants to know what happened.

TENSION IS WHAT KEEPS PEOPLE LISTENING. Something is wrong, at risk, or unresolved. Resolve it too early and attention leaves with it — which is why "let me tell you the answer first" is usually a mistake in a story, even though it is right in an email.

SPECIFIC BEATS GENERAL, always. "We improved customer service" is forgettable. "A customer waited eleven days for a reply, and we now answer within two hours" is a thing a person can picture. Numbers, names and small concrete details are what make a story stick, and they are also what makes it credible.

ONE STORY, ONE POINT. If your story could support three different lessons, the listener will pick the wrong one. Say the point plainly at the end — the story earns the attention, the sentence delivers the meaning.

CUT THE SET-UP. Beginners spend forty per cent of a short story on background nobody needs. The listener does not need to know what day it was or how you got there. Start as late in the story as you possibly can.

AND USE YOUR OWN MATERIAL. A story that happened to you is one you can tell without notes, with real detail, and nobody can accuse you of borrowing it. Your ordinary working life contains more usable stories than you think: the job that went wrong, the customer who taught you something, the first time you charged properly.

A WARNING WORTH TAKING SERIOUSLY: do not invent stories, and do not tell someone else''s as your own. Audiences detect it more often than speakers expect, and recovering from that is far harder than being unremarkable.',
      'Write a story from your own experience in under 60 seconds of speech — roughly 150 words. Start as late as possible, keep one clear point, and include at least two specific details a listener could picture. Then say it out loud and time it. If it runs over, cut set-up rather than detail. Finish with one sentence that states the point.',
      '[{"question":"Where should a short story begin?","options":["As late as possible — in the middle of something, skipping the set-up","At the beginning, with the necessary background","With a statement of the lesson it will teach","With an apology for taking up time"],"correct_index":0},{"question":"Why does a specific detail beat a general claim?","options":["It is something the listener can picture, which makes it memorable and credible","It makes the story longer","General claims are considered dishonest","Specific details are easier to remember for the speaker"],"correct_index":0}]'::jsonb)
  on conflict (module_id, order_number) do nothing;

  insert into public.modules (course_id, level_id, title, description, order_number) values
    (v_course_id, v_level, 'How You Sound, and How You Listen', 'The course promises communication skills, and half of communication is the part where you are not talking. This module covers your voice, and the conversation skill that gets people hired and promoted.', v_module_offset + 2)
  returning id into v_m2;

  insert into public.lessons (module_id, title, description, youtube_url, order_number, learning_objectives, notes, practice_activity, knowledge_check) values
    (v_m2, 'Making People Want to Listen to You', 'Julian Treasure on the habits that make people stop listening, and the vocal tools that make them stay. Under 10 minutes.', 'https://www.youtube.com/watch?v=eIho2S0ZahI', 1,
      array['Name the habits that cost you a listener''s attention', 'Use pace, pitch, volume and silence deliberately', 'Speak so that what you say is trusted, not just heard'],
      'Two halves here: what to stop doing, and what your voice can do.

THE HABITS THAT LOSE PEOPLE — gossip, judging, negativity, complaining, excuses, exaggeration and dogmatism. Read that list against your last week honestly. Most people find two or three they do regularly, and each one quietly teaches listeners that your words are worth less. Exaggeration is the most expensive: overstate a few times and everything you say gets mentally discounted, which is fatal if you sell anything.

WHAT TO REPLACE THEM WITH: honesty, authenticity, integrity — saying what you mean, being yourself rather than a performance, and doing what you said you would. This sounds like moralising until you notice it is entirely practical: these are the things that make a listener treat your next sentence as reliable.

THEN THE VOICE ITSELF, which most people never think about and which is trainable:

PACE — speed conveys excitement, slowness conveys weight. Nerves make everyone speed up, so deliberate slowing is the single most useful correction available to a nervous speaker.

PITCH — a voice that drops at the end of a sentence sounds certain. One that rises turns statements into questions and undercuts everything you just said. This one habit, corrected, changes how competent you seem.

VOLUME, used for emphasis. Going QUIETER pulls people in more reliably than going louder.

SILENCE, which is the most underused tool there is. A two-second pause before your key sentence does more than any adjective. Beginners fill every gap; confident speakers let gaps sit.

TIMBRE — the warmth of the voice. Breathing from the belly rather than the chest is most of it, and it is why nervous speakers sound thin.

WARM UP IF IT MATTERS. Thirty seconds of humming and a few deep breaths before a presentation or an important call genuinely changes how you sound.

AND A NOTE ON SPEAKING ENGLISH IN THIS REGION: a Kenyan accent is not something to correct. Clarity is worth working on — pace, articulation, finishing your words — but chasing a foreign accent makes people sound less authentic, not more professional, and listeners hear the difference.',
      'Record two minutes of yourself explaining something you know, using your phone. Listen back for three things: are you rushing, does your pitch rise at the ends of sentences, and where could a pause have gone? Then record it again applying one deliberate change — probably slowing down — and compare. Also review your last week against the seven habits and pick one to stop.',
      '[{"question":"Why does exaggeration cost a speaker so much?","options":["Once listeners discount what you say, everything afterwards is worth less","It makes talks run over time","It is difficult to remember what you exaggerated","Audiences prefer understatement stylistically"],"correct_index":0},{"question":"What does letting your pitch drop at the end of a sentence do?","options":["Makes the statement sound certain, rather than turning it into a question","Makes you sound quieter and less confident","Signals that you have finished speaking entirely","Has no measurable effect on listeners"],"correct_index":0}]'::jsonb),
    (v_m2, 'Having a Conversation Worth Having', 'Celeste Headlee on ten practical rules for conversation — the half of communication that is not talking. About 12 minutes.', 'https://www.youtube.com/watch?v=R1vskiVDwl4', 2,
      array['Listen in a way that changes what you say next', 'Ask open questions instead of leading ones', 'Say you do not know rather than filling the gap'],
      'Public speaking gets the attention; conversation gets the work. Client calls, interviews, negotiations, and the moment a colleague tells you something is wrong — all of it is this skill, and almost nobody is taught it.

THE PREMISE: most people do not listen with the intention to understand, they listen with the intention to reply. You can feel it — the other person is visibly loading their next sentence. Everyone can tell when it is happening to them, and everyone does it.

THE RULES THAT ACTUALLY CHANGE THINGS:

DO NOT MULTITASK. Be in the conversation or leave it. A call taken while reading email is obvious to the other person and worse than one rescheduled.

ASK OPEN QUESTIONS — who, what, when, where, why, how. "Was that frustrating?" gets a yes. "What was that like?" gets you something you did not know. In client work this is the difference between a brief you guessed at and one you understood.

GO WITH THE FLOW. Thoughts will arrive while they speak. Let them go. Holding a clever point in your head means you stop listening in order to keep it.

IF YOU DO NOT KNOW, SAY SO. Bluffing is discovered eventually, and it costs more than the admission would have. "I have not done that before, but here is how I would approach it" is a strong professional answer, not a weak one.

DO NOT EQUATE YOUR EXPERIENCE WITH THEIRS. Someone describes a problem and the reflex is to describe your version of it. That moves the conversation to you. Their experience is theirs; ask about it instead.

DO NOT REPEAT YOURSELF. Restating a point in different words is condescending and it eats the time.

STAY OUT OF THE WEEDS. Nobody needs the exact date or the name of the street. Details are for you, not for them.

LISTEN, which is the one that contains all the others. As the talk puts it: if your mouth is open, you are not learning.

BE BRIEF. Especially in a first client conversation, where the temptation to prove yourself makes people talk far too much.

THE ONE THAT MATTERS MOST FOR EARNING A LIVING: a client who feels genuinely heard hires you over someone more qualified who talked at them. Ask what they actually need, write it down, and read it back. That is most of what "good communication" means in practice, and it is very rare.',
      'In your next real conversation, do two things deliberately: ask only open questions for the first five minutes, and when a clever reply occurs to you, let it go and keep listening. Afterwards write down one thing you learned that you would have missed. Then, in your next client or work conversation, read their need back to them in your own words and watch what it does.',
      '[{"question":"What is the practical problem with holding onto a clever point while someone is speaking?","options":["You stop listening in order to keep hold of it","You are likely to interrupt them","The point usually turns out to be wrong","It makes the conversation run longer"],"correct_index":0},{"question":"A client describes a problem you have also had. What is the better response?","options":["Ask more about theirs — equating it with yours moves the conversation to you","Describe your version so they know you understand","Offer your solution immediately","Say nothing until they finish and then change the subject"],"correct_index":0}]'::jsonb)
  on conflict (module_id, order_number) do nothing;

  -- Bring the shifted modules back, now sitting after the 2 new one(s).
  update public.modules set order_number = order_number - 1000 + 2
   where course_id = v_course_id and order_number > 1000;

end $$;
