-- Auto-generated by scripts/curriculum/build-level-sql.mjs -- do not
-- hand-edit the lesson content below; regenerate from the source plan
-- JSON instead if something needs to change.

do $$
declare
  v_course_id uuid := '1b4f9561-ff39-4606-8569-a4d8d0fe8171';
  v_level uuid;
  -- modules.order_number is unique per COURSE, not per level (a course's
  -- modules are numbered continuously across all its levels) -- so this
  -- can't just start at 1 for a level beyond the first. Computed here
  -- instead of hardcoded so this script works correctly regardless of how
  -- many modules the course already has.
  v_module_offset int;
  v_m1 uuid;
  v_m2 uuid;
begin
  -- Appending to a level that already exists. Looked up rather than
  -- inserted, so this adds to the learner's current Level 1 instead of
  -- creating a duplicate one, and no existing module is re-parented.
  select id into v_level from public.levels
    where course_id = v_course_id and order_number = 1;

  if v_level is null then
    raise exception 'Level % not found for course % -- refusing to guess', 1, v_course_id;
  end if;

  -- The new modules must sit INSIDE this level, not at the end of the
  -- course. getOrderedLessons() builds the learner's lesson sequence from
  -- modules.order_number alone and ignores level, so a module appended at
  -- the course's max order would put beginner content after the final
  -- level's material. Insert straight after this level's last module and
  -- shift everything below it down instead.
  select coalesce(max(order_number), 0) into v_module_offset
    from public.modules where level_id = v_level;

  -- Two-phase shift: (course_id, order_number) is unique, and a single
  -- "+ N" update can trip that constraint mid-statement, so park the rows
  -- out of range first and bring them back afterwards.
  update public.modules set order_number = order_number + 1000
   where course_id = v_course_id and order_number > v_module_offset;

  insert into public.modules (course_id, level_id, title, description, order_number) values
    (v_course_id, v_level, 'Procreate, Taught by Procreate', 'The existing lessons are a single beginner tour of each app. This module is Procreate''s own two-part foundation series — the same ground covered properly, by the people who make it.', v_module_offset + 1)
  returning id into v_m1;

  insert into public.lessons (module_id, title, description, youtube_url, order_number, learning_objectives, notes, practice_activity, knowledge_check) values
    (v_m1, 'The Fundamentals: Gallery, Canvas and Gestures', 'Part one of Procreate''s own beginners series — setting up a canvas, moving around, and the gestures the whole app is built on. About 16 minutes.', 'https://www.youtube.com/watch?v=Vn8bj0YpZg4', 1,
      array['Create a canvas at the right size for what you are making', 'Use the core gestures for undo, redo, zoom and clearing a layer', 'Understand why canvas size and layer limits are linked'],
      'This is longer and more thorough than the tour in the previous module, and it comes from Procreate itself. If the two disagree on anything, trust this one.

CANVAS SIZE IS A DECISION YOU CANNOT EASILY UNDO, and beginners get it wrong constantly. Procreate limits how many LAYERS you get based on canvas size and your iPad''s memory — a huge canvas can leave you with very few layers, and you discover this halfway through a piece. Start from the output: a social post needs far less than something being printed. For print, 300 DPI at the physical size; for screen, the pixel dimensions of where it will appear.

THE GESTURES ARE THE INTERFACE. Learn these four now and everything speeds up: two-finger tap to undo, three-finger tap to redo, pinch to zoom, and three-finger scrub to clear a layer. Nobody who uses Procreate well is reaching for menus to undo.

QUICKMENU AND CUSTOM GESTURES are worth setting up once you are past the first week — Actions > Prefs > Gesture Controls. Small investment, permanent payoff.

THE INTERFACE IS DELIBERATELY EMPTY. Procreate hides almost everything so the canvas dominates. That is a feature on a tablet screen, and it means the tools are behind the small icons at the top and the sidebar at the left. Nothing is missing; it is tucked away.

A PRACTICAL NOTE FOR THIS AUDIENCE: Procreate runs only on iPad and requires an Apple Pencil for real work, which is a significant cost. If that is out of reach, the concepts here transfer almost completely to free alternatives — Krita and Autodesk Sketchbook on a tablet, and Adobe Fresco, which the previous lesson covers and which has a free tier. Learn the ideas — layers, brushes, selections — and the specific app becomes a detail.

AND SAVE YOUR WORK AS YOU GO by duplicating the artwork in the Gallery at milestones. Procreate has no version history; if you flatten something and keep painting, the earlier state is gone.',
      'Create three canvases at different sizes — one for an Instagram post, one for an A4 print at 300 DPI, and one deliberately enormous. Look at the layer limit Procreate gives each. Then on the smallest, practise the four core gestures until you do not have to think: undo, redo, zoom, and clear the layer. Duplicate the file in the Gallery so you have a copy before you paint anything.',
      '[{"question":"Why does canvas size matter so much in Procreate?","options":["The layer limit depends on it — a huge canvas can leave you with very few layers","Larger canvases cannot be exported","It determines which brushes are available","Small canvases disable gestures"],"correct_index":0},{"question":"How do you undo in Procreate?","options":["Two-finger tap on the canvas","Shake the iPad","Press and hold the layer thumbnail","Swipe down with one finger"],"correct_index":0}]'::jsonb),
    (v_m1, 'Painting Tools: Brushes, Colour and Layers', 'Part two of Procreate''s own series — the brush library, colour, and how layers work while you paint. About 18 minutes.', 'https://www.youtube.com/watch?v=e5F7em-hGwc', 2,
      array['Choose and adjust a brush rather than accepting the default', 'Build an illustration in layers so parts stay editable', 'Use alpha lock and clipping masks to colour inside a shape'],
      'This is where illustration actually happens, and where the difference between a beginner and someone employable shows up.

BRUSHES: Procreate ships with a large library and beginners try all of them. Pick three and learn them properly — one sketching pencil, one inking brush, one soft painting brush. Every professional you admire uses a small set. The brush settings panel, reached by tapping the brush again, lets you change size behaviour, opacity response and streamline, which smooths shaky lines and is the single most flattering setting for a new artist.

LAYERS ARE THE SAME IDEA AS PHOTOSHOP: transparent sheets stacked over each other, editable independently. The working habit is sketch on one layer, ink on another above it, colour on layers BELOW the ink, and effects on top. Then changing the colour never touches the lines.

ALPHA LOCK locks the transparent parts of a layer so you can only paint on what is already there — perfect for shading a shape you have already filled. CLIPPING MASKS do the same job on a separate layer, which is better because you can throw the mask away without damaging the art underneath. Learn both; use clipping masks more.

COLOUR: tap and hold on the canvas to pick up a colour already there. Build a small palette before you start rather than choosing colours one at a time — this is the single fastest way to make work look coherent, and it is also what the Graphic Design path teaches about colour theory, which is worth reading alongside this.

OPACITY AND BLEND MODES on a layer change how it interacts with what is below. Multiply for shadows, Add or Screen for light. You do not need to memorise them; you need to know they exist and try two.

AND NAME YOUR LAYERS once there are more than about six. Sketch, Lines, Flats, Shadow, Light. Untitled layers are how a file becomes unworkable, and it happens faster than you expect.',
      'Make one simple illustration using at least four named layers: sketch, lines, flat colour, and shading. Put the colour layers BELOW the lines. Use a clipping mask for the shading rather than painting directly on the flats. Then change one flat colour completely and confirm your line work is untouched — that is the proof the layer structure is right.',
      '[{"question":"Why is a clipping mask usually better than alpha lock for shading?","options":["It sits on a separate layer, so you can discard it without damaging the art underneath","It allows more colours","Alpha lock does not work on flat colour","It uses fewer layers"],"correct_index":0},{"question":"Where should colour layers sit relative to line work?","options":["Below the lines, so changing colour never touches the line work","Above the lines, so the colour is visible","On the same layer as the lines","It makes no difference"],"correct_index":0}]'::jsonb)
  on conflict (module_id, order_number) do nothing;

  insert into public.modules (course_id, level_id, title, description, order_number) values
    (v_course_id, v_level, 'Editing, and Fixing What You Drew', 'The part that separates finishing a piece from abandoning it — adjusting, selecting and moving things after they are down.', v_module_offset + 2)
  returning id into v_m2;

  insert into public.lessons (module_id, title, description, youtube_url, order_number, learning_objectives, notes, practice_activity, knowledge_check) values
    (v_m2, 'Editing Tools: Adjustments, Selections and Transform', 'Part three of Procreate''s own series — the adjustment and selection tools that let you change work you have already made. About 19 minutes.', 'https://www.youtube.com/watch?v=EqQjjxcNd1o', 1,
      array['Adjust colour, brightness and blur on a finished layer', 'Select part of an illustration and move or scale it', 'Use liquify and warp to fix proportion mistakes without redrawing'],
      'Beginners redraw. People who finish work edit. This lesson is the difference.

ADJUSTMENTS — hue, saturation, brightness, curves, blur — apply to a whole layer or a selection. Two things worth knowing: they are destructive in Procreate, unlike Photoshop''s adjustment layers, so duplicate the layer first if you might change your mind. And Gaussian blur applied to a duplicated, darkened silhouette layer is how most soft shadows get made.

SELECTIONS are how you change one part without affecting the rest. Freehand for irregular shapes, automatic for filled areas, rectangle and ellipse for the obvious. The critical habit: DESELECT when you are done. A forgotten active selection means your brush mysteriously stops working outside it, and this confuses every beginner for at least one evening.

TRANSFORM moves, scales and rotates a selection or layer. Uniform keeps the proportions; Freeform does not, and squashing a face by accident is easy. Distort and Warp bend things — Warp especially is how you fit artwork onto a curved surface or fix a shape that is subtly wrong.

LIQUIFY is the fix nobody expects to need and everybody uses. It pushes pixels around, which repairs proportion errors — an eye slightly too low, a jaw too wide — without redrawing the piece. Use it gently and at low pressure; heavy liquify looks smeared.

A WORKFLOW WARNING: every transform slightly degrades the pixels, because the image is being resampled. Scaling something up repeatedly turns it soft. Do your transforms in as few moves as possible, and where you can, draw large and scale down rather than the reverse.

AND KEEP A FLATTENED COPY of a piece you are happy with before doing anything drastic. Gallery, swipe left, Duplicate. Procreate will not save you from yourself otherwise.',
      'Take an illustration you have made and do four things to it without redrawing: select one element and move it, scale something using Uniform, use Liquify gently to fix one proportion that has been bothering you, and apply a Gaussian blur to a duplicated dark shape to make a soft shadow. Duplicate the file first. Compare before and after.',
      '[{"question":"Your brush suddenly only paints in part of the canvas. What has probably happened?","options":["A selection is still active and needs deselecting","The layer is alpha locked","The brush opacity is too low","The canvas has run out of layers"],"correct_index":0},{"question":"Why should you minimise how many times you transform a layer?","options":["Each transform resamples the pixels and softens the image","Procreate limits the number of transforms per file","It permanently merges the layer below","Transforms cannot be undone"],"correct_index":0}]'::jsonb),
    (v_m2, 'Layer Select: Working Fast in a Busy File', 'Procreate''s own short guide to Layer Select — jumping straight to the layer holding the thing you tapped. About 3 minutes.', 'https://www.youtube.com/watch?v=8DIkyEjXp4s', 2,
      array['Find the layer containing a specific element without hunting', 'Keep a complex file navigable', 'Build habits that make a twenty-layer illustration manageable'],
      'A short one, and it solves a problem that becomes serious the moment your illustrations get complicated.

THE PROBLEM: in a file with twenty layers you tap something you want to change and then spend a minute opening and closing layers to find which one it lives on. Multiply that by every edit and it is a real share of your working time.

LAYER SELECT jumps you straight to the layer holding whatever you touched. Once it is a habit, navigating a complex file stops being a chore. Set it up under Actions > Prefs > Gesture Controls, where you can assign it to a gesture that suits how you hold the iPad.

THE HABITS THAT MAKE THIS UNNECESSARY MOST OF THE TIME, and which matter more than the feature itself:

NAME LAYERS as you create them, not later. Later never comes.

GROUP RELATED LAYERS. Procreate lets you combine layers into a group — all the character layers in one, background in another. A file with five groups is navigable; one with twenty-five loose layers is not.

WORK TOP TO BOTTOM in a consistent order, every time: effects, lines, shading, flats, background. When the order is always the same you stop searching, because you already know roughly where something is.

MERGE WHEN YOU ARE CERTAIN, and not before — remembering that Procreate has no version history, so merging is permanent. If you might reconsider, duplicate the file in the Gallery first.

AND IF YOU ARE HITTING THE LAYER LIMIT, that is your canvas size and your iPad''s memory talking, not a mistake. Flatten what is genuinely finished, keep a duplicate of the unflattened file, and carry on.',
      'Open your most complicated file, or build one with at least ten layers. Name every layer and put them into at least two groups. Then set up Layer Select in Gesture Controls and use it to reach five different elements without opening the layers panel. Time yourself before and after — the gap is what this saves you on every piece from now on.',
      '[{"question":"What does Layer Select do?","options":["Jumps straight to the layer containing whatever you tapped on the canvas","Selects all layers at once for transforming","Locks a layer so it cannot be edited","Merges the selected layers together"],"correct_index":0},{"question":"Why duplicate a file in the Gallery before merging layers?","options":["Procreate has no version history, so a merge is permanent","Merging reduces the export quality","Duplicates are needed to use Layer Select","It frees up additional layers"],"correct_index":0}]'::jsonb)
  on conflict (module_id, order_number) do nothing;

  -- Bring the shifted modules back, now sitting after the 2 new one(s).
  update public.modules set order_number = order_number - 1000 + 2
   where course_id = v_course_id and order_number > 1000;

end $$;
