-- Level 1 deepening: Copywriting & Content Writing, and Bookkeeping &
-- QuickBooks. Breadth-first sweep, additive only -- no existing module is
-- deleted, re-parented or renumbered except by the shift that keeps the
-- new modules INSIDE Level 1.
--
-- COPYWRITING taught the craft and skipped the reader. Its four Level 1
-- lessons cover what copywriting is, headlines and body copy, and never
-- ask who the copy is for. It gains "Knowing Who You Are Writing For"
-- (HubSpot Marketing on audience research, then building a persona from
-- that research rather than from imagination) and "Writing So People
-- Actually Read It" (Nielsen Norman Group on defining the reader before
-- writing, then on plain language). The F-pattern eyetracking finding and
-- the 4 S's of link text are folded into notes and labelled as additions
-- beyond the video -- both NN/g videos on those run under three minutes,
-- so neither could carry a lesson of its own.
--
-- An Ahrefs "Content Writing for SEO" lesson was considered and dropped:
-- seo-search-engine-optimization already teaches keyword research and
-- on-page optimisation, so it would have duplicated a course on sale.
--
-- BOOKKEEPING never mentioned invoicing anywhere across its twelve
-- lessons -- the single most common task a client asks for. It gains
-- "Money In, Money Out: Invoices and Bills" and "Letting the Bank Feed Do
-- the Typing", all four videos from Intuit QuickBooks, the vendor's own
-- channel. Categorising transactions sits in Level 1 deliberately: Level
-- 2 already teaches bank RULES, which automate a decision you have to be
-- able to make by hand first.
--
-- Written into the notes rather than discovered by the learner after
-- paying: QuickBooks Payments is not available in Kenya, and most Kenyan
-- banks have no direct bank feed. The lessons teach the CSV-import route
-- as the normal path and explain why the feature is still worth learning
-- -- much paid remote bookkeeping is for businesses in countries where
-- the feed does work.
--
-- Every id confirmed through the YouTube Data API for channel, exact
-- title, duration and embeddability before any lesson was written.
-- Rejected on duration: Intuit's "How to track expenses" (17 seconds, a
-- promo clip) and "How to track what customers owe you" (2:38).
--
-- Researched and dropped this firing for want of an authoritative source:
-- FREELANCING (pricing and contracts are its real gap; neither Upwork nor
-- Fiverr publishes teaching content, and every candidate was an
-- individual creator) and INSTAGRAM & TIKTOK GROWTH (no official Meta,
-- Instagram or TikTok teaching channel surfaces at all). Video Editing
-- was skipped again -- its gap is still audio, still unsourceable.
--
-- All eight new lessons carry objectives, notes, a practice activity and
-- a knowledge check, so the 438-lesson bare backlog does not grow.

-- ============ Copywriting & Content Writing ============
-- Auto-generated by scripts/curriculum/build-level-sql.mjs -- do not
-- hand-edit the lesson content below; regenerate from the source plan
-- JSON instead if something needs to change.

do $$
declare
  v_course_id uuid := 'b4445076-7261-419e-a401-98f30417862a';
  v_level uuid;
  -- modules.order_number is unique per COURSE, not per level (a course's
  -- modules are numbered continuously across all its levels) -- so this
  -- can't just start at 1 for a level beyond the first. Computed here
  -- instead of hardcoded so this script works correctly regardless of how
  -- many modules the course already has.
  v_module_offset int;
  v_m1 uuid;
  v_m2 uuid;
begin
  -- Appending to a level that already exists. Looked up rather than
  -- inserted, so this adds to the learner's current Level 1 instead of
  -- creating a duplicate one, and no existing module is re-parented.
  select id into v_level from public.levels
    where course_id = v_course_id and order_number = 1;

  if v_level is null then
    raise exception 'Level % not found for course % -- refusing to guess', 1, v_course_id;
  end if;

  -- The new modules must sit INSIDE this level, not at the end of the
  -- course. getOrderedLessons() builds the learner's lesson sequence from
  -- modules.order_number alone and ignores level, so a module appended at
  -- the course's max order would put beginner content after the final
  -- level's material. Insert straight after this level's last module and
  -- shift everything below it down instead.
  select coalesce(max(order_number), 0) into v_module_offset
    from public.modules where level_id = v_level;

  -- Two-phase shift: (course_id, order_number) is unique, and a single
  -- "+ N" update can trip that constraint mid-statement, so park the rows
  -- out of range first and bring them back afterwards.
  update public.modules set order_number = order_number + 1000
   where course_id = v_course_id and order_number > v_module_offset;

  insert into public.modules (course_id, level_id, title, description, order_number) values
    (v_course_id, v_level, 'Knowing Who You Are Writing For', 'Every weak piece of copy has the same cause: it was written to nobody in particular. Before you write a headline or a sentence of body copy, you need a specific person in mind. This module is the step the first two modules skipped.', v_module_offset + 1)
  returning id into v_m1;

  insert into public.lessons (module_id, title, description, youtube_url, order_number, learning_objectives, notes, practice_activity, knowledge_check) values
    (v_m1, 'Finding the Person You Are Actually Writing To', 'A six-step framework for working out who your client''s customer really is, using evidence rather than assumption. This is the research that happens before any writing, and it is the difference between copy a client pays for twice and copy they quietly rewrite themselves.', 'https://www.youtube.com/watch?v=6mugRyElbd0', 1,
      array['Describe a target audience using evidence — reviews, comments, sales conversations — rather than guesswork', 'Tell the difference between a market (everyone who could buy) and a target audience (who you write to)', 'Collect the exact words customers use, so your copy sounds like their thoughts rather than a brochure'],
      'The single most useful habit in this video is looking at what customers already say in their own words. Reviews, WhatsApp messages, YouTube comments under a competitor''s video, questions in a Facebook group — that is free research, and it hands you phrases you can put straight into copy.

Why it matters commercially: a client can tell within one line whether you understand their customer. Two writers submit a headline; the one who used the customer''s own phrasing gets the repeat work. This is why research is billable time, not preparation you do for free.

ADDITION BEYOND THE VIDEO — doing this in Kenya without paid tools. The video mentions research tools that cost money in dollars. You do not need them to start. Free sources that work: the Questions section on a Jumia or Kilimall product page, replies under a business''s Instagram or TikTok posts, Google''s "People also ask" box, and Facebook groups for the trade you are writing about (matatu owners, salon owners, small farmers). Ten real customer sentences beat any tool.

One warning about personas, which the next lesson builds: a persona is a summary of research, not a substitute for it. Inventing "Mary, 28, likes convenience" without talking to anyone gives you a confident description of a person who does not exist.',
      'Pick any small business you could plausibly write for — a salon, a phone-repair shop, an online clothes seller. Spend twenty minutes collecting TEN real sentences that its customers (or customers of a direct competitor) have written in public: reviews, comments, questions. Copy them into a document word for word, including the spelling and slang. Then write two sentences answering: what does this customer actually want, and what are they afraid of? Keep this document — the next lesson turns it into a persona.',
      '[{"question":"Why is collecting customers'' own words more useful than describing your audience in your own words?","options":["It saves time compared with writing a description yourself","Copy written in the customer''s own language reads as understanding, which is what makes them keep reading and what makes a client rehire you","Search engines rank pages that quote customers more highly","It is the only legal way to describe an audience"],"correct_index":1},{"question":"What is the difference between a market and a target audience?","options":["There is no difference; the terms are interchangeable","A market is online and a target audience is offline","A market is everyone who could conceivably buy; a target audience is the specific group you choose to write to","A market is people who have already bought; a target audience is people who have not"],"correct_index":2}]'::jsonb),
    (v_m1, 'Turning a Vague Audience Into One Named Reader', 'How to build a buyer persona from scratch — a single, specific reader you write every sentence to. Built from the research in the previous lesson, not from imagination.', 'https://www.youtube.com/watch?v=1Un9dvxIBhs', 2,
      array['Build a persona from real research rather than invented detail', 'Identify the persona''s goal and their objection — the two facts that most change what you write', 'Use the persona as a test: read a draft as that person and cut what they would not care about'],
      'A persona is a working tool, not a document to file. The parts that actually change your writing are small: what this person is trying to get done, what they are worried about, and what they would have to believe before they bought. Age, favourite colour and a stock photo change nothing.

How to use it while writing: read your draft aloud as if you were that person. Every sentence that person would skip is a sentence to cut. This one habit does more for a beginner''s copy than any list of persuasion techniques.

ADDITION BEYOND THE VIDEO — the honest limit of personas. Made-up personas are worse than none, because they give you false confidence. If you have not gathered real customer language, you do not have a persona; you have a character. Build it from the ten sentences you collected in the previous lesson, and write down where each claim came from. If you cannot cite a source for a claim, mark it as a guess.

One persona is enough when you start. Agencies build five; a beginner writing a single landing page needs one, clearly.',
      'Using the ten customer sentences you collected, write a one-page persona: a name, what they are trying to get done, what worries them about buying, what they would need to believe before paying, and three phrases they actually use — quoted, with a note of where each came from. Then take any piece of copy you have written before (or the homepage of the business you chose) and read it as that person. Mark every line they would skip. That mark-up is your edit list.',
      '[{"question":"Which parts of a persona actually change what you write?","options":["Age, location and a photograph","Their goal, their worry, and what they would need to believe before buying","Their income bracket and job title alone","Their favourite brands"],"correct_index":1},{"question":"What makes a persona actively harmful rather than merely useless?","options":["Being written on one page instead of five","Having only one persona rather than several","Being invented rather than built from real customer research, so it gives false confidence about a person who does not exist","Giving the persona a name"],"correct_index":2}]'::jsonb)
  on conflict (module_id, order_number) do nothing;

  insert into public.modules (course_id, level_id, title, description, order_number) values
    (v_course_id, v_level, 'Writing So People Actually Read It', 'People do not read online, they scan. This module covers what that means for the way you build a sentence and a page — the craft that sits underneath headlines and body copy, from the research group that has studied how people read on screens for thirty years.', v_module_offset + 2)
  returning id into v_m2;

  insert into public.lessons (module_id, title, description, youtube_url, order_number, learning_objectives, notes, practice_activity, knowledge_check) values
    (v_m2, 'The Mistake That Makes Web Writing Fail', 'Nielsen Norman Group on the error underneath most weak web content: writing before deciding who will read it, what they want, and what the writing is supposed to achieve. Short, and worth watching twice.', 'https://www.youtube.com/watch?v=dHX8RRYPHJI', 1,
      array['State the three things to define before writing any piece of web content', 'Explain why content written to impress a client''s boss usually fails the customer', 'Apply the reader-goal test to a page you have written'],
      'Three questions before writing anything: who reads this, what are they trying to do, and what should be different for them afterwards. Most business web copy fails the second question — it describes the company rather than helping the reader do something.

ADDITION BEYOND THE VIDEO — the F-pattern, and what it means for your first three words. Eye-tracking research from the same group shows people scan web pages in a rough F shape: across the top line, across again a little lower, then down the left edge. The practical consequence is blunt. The first two or three words of every heading and every paragraph do almost all the work, because that left edge is the only part reliably seen. Front-load them. "Free delivery in Nairobi" is read; "We are pleased to announce that we now offer free delivery" is not, because the first four words carry nothing.

This also explains why a wall of text fails even when the writing is good. Short paragraphs, real subheadings and bulleted lists are not decoration — they create more left-edge starting points, which is where the scanning eye actually lands.

A note for this course: this is the principle underneath the headline lesson in module 2. Headlines work because of where the eye goes, not because of a magic formula.',
      'Take the homepage or an About page of any small business website. Write down the first three words of every heading and every paragraph, in order, and nothing else. Read that list. Does it tell you what the business does and what to do next? If it does not, rewrite each of those openings so that it does — front-loading the meaningful word — and compare the two lists.',
      '[{"question":"According to the video, what should you define before writing any piece of web content?","options":["The word count, the deadline and the fee","Who will read it, what their goal is, and what impact the content should have on them","The keywords, the meta description and the title tag","The brand colours and the font"],"correct_index":1},{"question":"What practical rule follows from the F-pattern in reading?","options":["Write longer paragraphs so there is more to read","Centre all text so it is easier to scan","Front-load the first two or three words of each heading and paragraph, because the left edge is what gets scanned","Put the most important information at the bottom of the page"],"correct_index":2}]'::jsonb),
    (v_m2, 'Plain Language Beats Clever Language', 'Why complicated wording slows readers down and costs conversions — and why plain language is a professional skill rather than dumbing down. Nielsen Norman Group.', 'https://www.youtube.com/watch?v=Q8e5VODJ25w', 2,
      array['Explain why complex wording degrades results even for expert readers', 'Rewrite a jargon-heavy sentence into plain language without losing meaning', 'Answer the client objection that plain language sounds unprofessional'],
      'The finding that surprises most beginners: experts prefer plain language too. Simplifying does not insult a specialist reader; it saves them effort. Nobody has ever complained that a sentence was too easy to understand.

The practical moves are few and they always work. Use the word your reader would use, not the industry word. Prefer short sentences with one idea each. Say who does what — "we will call you" rather than "a call will be initiated". Cut words that carry no information: in order to, at this point in time, it should be noted that.

You will meet the client objection: "this sounds too simple, we are a serious company." The answer is that clarity is what looks competent, and that the alternative is a reader who leaves. Where a client insists on a formal register, keep the formality in the vocabulary and still keep the sentences short — those are separate choices.

ADDITION BEYOND THE VIDEO — link text, from the same research group. The words you put in a link matter as much as the words around it, because scanning readers use links as signposts. Good link text is specific, honest, substantial and short: "Download the price list" tells the reader what happens; "Click here" and "Read more" tell them nothing, and a page with six "Read more" links is a page with six identical signposts. Never write a link that promises more than the destination delivers — a reader who is misled once stops trusting the whole page.',
      'Find a paragraph of genuinely dense writing — a bank''s terms page, an insurance product page, a government notice. Rewrite it in plain language, keeping every fact intact. Then count the words in both versions. Aim to lose at least a third without losing a single piece of information. Finally, look at any links in the original and rewrite them so each one says what the reader will get.',
      '[{"question":"What does the research say about expert readers and plain language?","options":["Experts prefer complex language that matches their expertise","Experts also perform better with plain language; simplifying does not insult them","Plain language only helps readers with low literacy","Experts read at the same speed regardless of complexity"],"correct_index":1},{"question":"What makes \"Read more\" poor link text?","options":["It is too short to be clicked easily","It is not a complete sentence","It tells the scanning reader nothing about what is on the other side, so it fails as a signpost","Search engines penalise it"],"correct_index":2}]'::jsonb)
  on conflict (module_id, order_number) do nothing;

  -- Bring the shifted modules back, now sitting after the 2 new one(s).
  update public.modules set order_number = order_number - 1000 + 2
   where course_id = v_course_id and order_number > 1000;

end $$;

-- ============ Bookkeeping & QuickBooks ============
-- Auto-generated by scripts/curriculum/build-level-sql.mjs -- do not
-- hand-edit the lesson content below; regenerate from the source plan
-- JSON instead if something needs to change.

do $$
declare
  v_course_id uuid := 'ebcd254b-df64-476f-b9b4-26232762a2f3';
  v_level uuid;
  -- modules.order_number is unique per COURSE, not per level (a course's
  -- modules are numbered continuously across all its levels) -- so this
  -- can't just start at 1 for a level beyond the first. Computed here
  -- instead of hardcoded so this script works correctly regardless of how
  -- many modules the course already has.
  v_module_offset int;
  v_m1 uuid;
  v_m2 uuid;
begin
  -- Appending to a level that already exists. Looked up rather than
  -- inserted, so this adds to the learner's current Level 1 instead of
  -- creating a duplicate one, and no existing module is re-parented.
  select id into v_level from public.levels
    where course_id = v_course_id and order_number = 1;

  if v_level is null then
    raise exception 'Level % not found for course % -- refusing to guess', 1, v_course_id;
  end if;

  -- The new modules must sit INSIDE this level, not at the end of the
  -- course. getOrderedLessons() builds the learner's lesson sequence from
  -- modules.order_number alone and ignores level, so a module appended at
  -- the course's max order would put beginner content after the final
  -- level's material. Insert straight after this level's last module and
  -- shift everything below it down instead.
  select coalesce(max(order_number), 0) into v_module_offset
    from public.modules where level_id = v_level;

  -- Two-phase shift: (course_id, order_number) is unique, and a single
  -- "+ N" update can trip that constraint mid-statement, so park the rows
  -- out of range first and bring them back afterwards.
  update public.modules set order_number = order_number + 1000
   where course_id = v_course_id and order_number > v_module_offset;

  insert into public.modules (course_id, level_id, title, description, order_number) values
    (v_course_id, v_level, 'Money In, Money Out: Invoices and Bills', 'The two things a small business does in QuickBooks every single week: send invoices so it gets paid, and record bills so it knows what it owes. Neither appeared anywhere in this course until now, and both are taught here by Intuit, the company that makes QuickBooks.', v_module_offset + 1)
  returning id into v_m1;

  insert into public.lessons (module_id, title, description, youtube_url, order_number, learning_objectives, notes, practice_activity, knowledge_check) values
    (v_m1, 'Sending an Invoice That Gets Paid', 'Creating, customising and sending an invoice in QuickBooks Online — the single most common task a bookkeeping client will ask you to do.', 'https://www.youtube.com/watch?v=FZVBoSXSMzc', 1,
      array['Create an invoice in QuickBooks Online and send it to a customer', 'Customise an invoice so it carries the business''s name, logo and payment terms', 'Explain what payment terms mean and why they change when a business gets paid'],
      'An invoice in QuickBooks is not just a document — creating it also records that a customer now owes the business money. That is the part beginners miss. Sending a Word invoice and typing the sale in later gives you two chances to disagree with yourself; raising it in QuickBooks records the sale and the debt in one step.

Payment terms are worth understanding properly. "Due on receipt" means now; "Net 30" means the customer has thirty days. A business that sets Net 30 without meaning to has quietly agreed to wait a month for its money. When you set up a client''s invoicing, ask what terms they actually intend and set that as the default.

ADDITION BEYOND THE VIDEO — invoicing from Kenya. QuickBooks Payments, the pay-by-card button shown in some Intuit videos, is not available in Kenya. What still works everywhere: the invoice itself, the customer record, the outstanding-balance tracking, and emailing a PDF. For collection, most Kenyan businesses put their M-Pesa Paybill or Till number and bank details in the invoice message or a custom field, and then record the payment against the invoice by hand when it arrives. Do that consistently and the books stay correct; the automated card button is a convenience, not the substance.

If you are doing this for overseas clients, ask which currency they invoice in and whether their QuickBooks plan has multicurrency switched on before you raise anything — turning it on later is disruptive.',
      'Open a QuickBooks Online free trial or the sample company Intuit provides. Create one customer and raise an invoice to them for two line items — say a service and a delivery charge. Customise it once: add a business name and set payment terms deliberately rather than accepting the default. Then find where QuickBooks shows that this invoice is unpaid. Write down, in one sentence, where a business owner would look to see everything they are owed.',
      '[{"question":"What does creating an invoice in QuickBooks do beyond producing a document to send?","options":["Nothing else; it is only a document generator","It records the sale and records that the customer now owes the business money","It automatically takes the money from the customer''s account","It files the sale with the tax authority"],"correct_index":1},{"question":"A client''s invoices default to Net 30 but they expect payment immediately. What is the consequence?","options":["None — terms on an invoice are decorative","QuickBooks will refuse to send the invoice","They have told every customer in writing that thirty days is acceptable, so they will wait longer to be paid","The invoice total will be calculated incorrectly"],"correct_index":2}]'::jsonb),
    (v_m1, 'Bills You Owe, and Paying Them On Time', 'The other direction: entering bills from suppliers and paying them in QuickBooks Online, so a business knows what is going out before it goes out.', 'https://www.youtube.com/watch?v=CjcTT4H0cKA', 2,
      array['Enter a supplier bill in QuickBooks Online and record its due date', 'Distinguish a bill (owed now, paid later) from an expense (already paid)', 'Find what the business currently owes and what falls due next'],
      'The distinction that matters: an EXPENSE is money already gone — you paid at the counter. A BILL is money owed but not yet paid, with a due date. Entering both as expenses is one of the most common beginner mistakes, and it makes a business look like it has more cash than it does, because nothing shows what is about to leave.

Once bills are entered properly, QuickBooks can answer the question every small business owner actually asks: what do I owe, and when. That report is often the first thing that makes an owner glad they hired a bookkeeper.

ADDITION BEYOND THE VIDEO — receipts, and why they matter more here than in the US. Intuit also publishes a short guide to capturing receipts by photographing them with the QuickBooks mobile app, which attaches the image to the transaction. Get into this habit early: in a cash-heavy market, the paper receipt is frequently the only evidence a purchase happened, and a faded thermal receipt in a drawer is not evidence at all after six months. Photograph it the day it arrives.

A practical note on the pay-bills step: the online bill-payment features shown in the video are US banking integrations. In Kenya you will usually mark a bill as paid after paying by M-Pesa or bank transfer. The record-keeping is identical; only the button that moves the money is missing.',
      'In the same QuickBooks trial or sample company, enter two supplier bills with different due dates — one due this week, one next month. Then find the report or screen that lists what the business owes and when it falls due. Finally, mark the first bill as paid and watch what changes. Write one sentence explaining what would have been wrong in the books if you had entered both as expenses instead of bills.',
      '[{"question":"What is the difference between a bill and an expense in QuickBooks?","options":["A bill is for services and an expense is for goods","A bill is money owed but not yet paid, with a due date; an expense is money already paid","A bill is over a certain amount; an expense is below it","They are the same thing recorded on different screens"],"correct_index":1},{"question":"Why does recording unpaid bills as expenses mislead a business owner?","options":["It makes the business look like it has more available cash than it does, because nothing shows what is about to leave","It causes QuickBooks to double-count the amount","It prevents invoices from being sent","It changes the business''s payment terms"],"correct_index":0}]'::jsonb)
  on conflict (module_id, order_number) do nothing;

  insert into public.modules (course_id, level_id, title, description, order_number) values
    (v_course_id, v_level, 'Letting the Bank Feed Do the Typing', 'Bookkeeping stops being data entry when the bank sends the transactions to you. This module covers connecting an account and categorising what comes in — the manual judgement that the automation in Level 2 is built on top of.', v_module_offset + 2)
  returning id into v_m2;

  insert into public.lessons (module_id, title, description, youtube_url, order_number, learning_objectives, notes, practice_activity, knowledge_check) values
    (v_m2, 'Connecting a Bank Account, and What to Do If Yours Is Not Supported', 'How QuickBooks Online pulls transactions straight from a bank or credit card account, and the honest position for a learner in Kenya whose bank is not on the list.', 'https://www.youtube.com/watch?v=LMgxbcsWANg', 1,
      array['Connect a bank or credit card account to QuickBooks Online', 'Explain what a bank feed does and does not do to the books', 'Import transactions manually when a bank feed is unavailable'],
      'A bank feed imports transactions; it does not do the bookkeeping. Every imported line still has to be reviewed and categorised — which is the next lesson, and the part clients pay for.

READ THIS BEFORE YOU GET FRUSTRATED — bank feeds and Kenya. QuickBooks'' direct bank feeds cover mostly US, UK, Canadian and Australian institutions. Most Kenyan banks are not on that list, and M-Pesa is not a supported feed at all. Check your own bank in the connect screen; if it is not there, this is a limitation of the product, not something you have done wrong.

What you do instead, and it works perfectly well: download a statement from your bank as CSV, tidy the columns to date, description and amount, and use QuickBooks'' file-upload option to import it. The transactions then behave exactly like a feed — they land in the same review queue and are categorised the same way. Doing this monthly is normal practice for a great many bookkeepers.

Why learn the feature at all if your own bank is unsupported? Because a large share of paid remote bookkeeping work is for businesses in those countries, and the feed is the first thing you will be asked to set up. It is also the reason bookkeeping is one of the more genuinely exportable skills on this platform.',
      'In a QuickBooks trial, open the banking screen and search for your own bank. Write down whether it appears. Then, whichever the answer, practise the manual route: create a small CSV with five made-up transactions (date, description, amount), upload it, and confirm the five lines arrive in the review queue. That manual import is the skill you will actually use most.',
      '[{"question":"What does a bank feed actually do?","options":["It categorises transactions and completes the bookkeeping automatically","It imports transactions into a review queue; each one still needs to be reviewed and categorised","It reconciles the account without any human involvement","It pays bills on the due date"],"correct_index":1},{"question":"Your bank does not appear in QuickBooks'' connect screen. What is the correct next step?","options":["Conclude that QuickBooks cannot be used for this business","Enter every transaction by hand for the rest of the year","Download a statement as CSV and upload it, so transactions land in the same review queue","Create a second QuickBooks account in a supported country"],"correct_index":2}]'::jsonb),
    (v_m2, 'Categorising Transactions Without Guessing', 'Deciding what each imported transaction actually is. This is the judgement work of bookkeeping, and it is what the automated bank rules in Level 2 are built on top of.', 'https://www.youtube.com/watch?v=J6mH0vYLfGk', 2,
      array['Categorise imported transactions to the correct account', 'Recognise which transactions need an owner''s input rather than a guess', 'Explain why a consistent category choice matters more than a perfect one'],
      'Two rules carry most of this work. First, consistency beats perfection: if the same kind of purchase always lands in the same category, the reports are readable and a mistake is easy to correct in bulk later. Scattering similar purchases across four plausible categories produces reports nobody can use. Second, never guess on someone else''s books. A transaction that could be a business cost or the owner''s personal shopping is a question for the owner, not a coin toss. Keep a running list of queries and send it once a week rather than interrupting daily — clients notice both the diligence and the restraint.

How this connects to the rest of the course: Level 2 covers bank rules, which automate categorisation for transactions you have taught QuickBooks to recognise. Rules only work if you already know what the right category is — automating a wrong decision just makes it wrong faster. That is why this lesson sits in Level 1 and the rules lesson sits in Level 2.

ADDITION BEYOND THE VIDEO — the mixed-use problem, which is constant in small businesses here. One M-Pesa line may cover stock for the shop and airtime for the owner''s personal phone. Do not split it from guesswork. Ask, then record it as two lines with the split the owner confirms, and note in the memo field who told you and when. That memo will save you an argument months later.',
      'Using the five transactions you imported in the previous lesson, categorise each one. Deliberately make one of them ambiguous — a payment that could be business or personal. Categorise the four you are sure of, and write the fifth as a client query: one sentence naming the transaction, the date, the amount, and the specific question you would ask the owner. That query note is a real deliverable in paid bookkeeping work.',
      '[{"question":"Why does consistency in categorising matter more than finding the theoretically perfect category?","options":["QuickBooks charges more for additional categories","Consistent categories produce readable reports and let a mistake be corrected in bulk, while scattered ones produce reports nobody can use","Inconsistent categories prevent the account from being reconciled","Consistency is required by law"],"correct_index":1},{"question":"A transaction could be a business cost or the owner''s personal spending. What should a bookkeeper do?","options":["Choose the business category, since it is a business file","Choose the personal category to be cautious","Delete the transaction and reconcile around it","Categorise what is certain, and raise the ambiguous one as a written query for the owner"],"correct_index":3}]'::jsonb)
  on conflict (module_id, order_number) do nothing;

  -- Bring the shifted modules back, now sitting after the 2 new one(s).
  update public.modules set order_number = order_number - 1000 + 2
   where course_id = v_course_id and order_number > 1000;

end $$;
