-- Level 1 deepening: Notion for Work & Business, and Motion Graphics with
-- After Effects. Additive only, one new module per course.
--
-- BOTH ARE DAY-7/8 CURATED COURSES built as 3 levels x 1 module x 2
-- lessons, which makes their Level 1 thinner than the legacy converted
-- courses -- two lessons before the first level ends. Each gains one
-- module of two lessons, taking Level 1 to 2 modules / 4 lessons.
--
-- NOTION: Level 1 explained what Notion is and how sharing works, then
-- Level 2 jumped straight to databases. Nothing covered navigating a
-- workspace or writing a page -- the two things a learner does every day
-- before they ever build a database. Both videos are from Notion's own
-- channel.
--
-- A NOTE ON THE SEARCH THAT FOUND THEM: earlier queries for Notion
-- returned only third-party creators and the conclusion "no official
-- channel" would have been wrong -- day 8 had already used six videos
-- from the "Notion" channel. Verifying against the course's existing
-- lesson ids surfaced the channel that keyword search had missed. Check
-- what a course already uses before concluding a vendor does not publish.
--
-- AFTER EFFECTS: Level 1 covered the interface and keyframes. It gains
-- parenting and null objects -- the concept that separates animation you
-- can edit from animation you have to redo -- and essential compositing.
-- Both from Adobe Video, Adobe's own channel.
--
-- REJECTED ON DURATION this firing, all from vendors' own channels:
-- Notion's "Projects & tasks" (2:56), "Add projects & tasks to your
-- workspace" (2:19) and "Introducing AI Meeting Notes" (1:21). Notion's
-- "AI Meeting Notes" (4:02) cleared the floor but was DROPPED on a
-- different ground: it teaches a paid AI feature, and a learner on the
-- free plan would get nothing actionable from a lesson built on it.
-- Notion's "Workspace & sidebar" (5:36) was dropped as a near-duplicate
-- of "Navigating the sidebar", which is longer and was used instead.
--
-- DEFERRED, not rejected: Notion's "Connecting your projects to tasks &
-- meeting notes" (5:40) is a good video that belongs beside the database
-- material in Level 2, not in Level 1. Logged for the Level 2 pass.
--
-- Every id confirmed through the YouTube Data API for channel, exact
-- title, duration and embeddability. All four run 3:08-7:24.
--
-- All four new lessons carry objectives, notes, a practice activity and a
-- knowledge check, so the 438-lesson bare backlog does not grow.

-- ============ Notion for Work & Business ============
-- Auto-generated by scripts/curriculum/build-level-sql.mjs -- do not
-- hand-edit the lesson content below; regenerate from the source plan
-- JSON instead if something needs to change.

do $$
declare
  v_course_id uuid := 'b186978e-b75b-40bd-baad-1d906e88f197';
  v_level uuid;
  -- modules.order_number is unique per COURSE, not per level (a course's
  -- modules are numbered continuously across all its levels) -- so this
  -- can't just start at 1 for a level beyond the first. Computed here
  -- instead of hardcoded so this script works correctly regardless of how
  -- many modules the course already has.
  v_module_offset int;
  v_m1 uuid;
begin
  -- Appending to a level that already exists. Looked up rather than
  -- inserted, so this adds to the learner's current Level 1 instead of
  -- creating a duplicate one, and no existing module is re-parented.
  select id into v_level from public.levels
    where course_id = v_course_id and order_number = 1;

  if v_level is null then
    raise exception 'Level % not found for course % -- refusing to guess', 1, v_course_id;
  end if;

  -- The new modules must sit INSIDE this level, not at the end of the
  -- course. getOrderedLessons() builds the learner's lesson sequence from
  -- modules.order_number alone and ignores level, so a module appended at
  -- the course's max order would put beginner content after the final
  -- level's material. Insert straight after this level's last module and
  -- shift everything below it down instead.
  select coalesce(max(order_number), 0) into v_module_offset
    from public.modules where level_id = v_level;

  -- Two-phase shift: (course_id, order_number) is unique, and a single
  -- "+ N" update can trip that constraint mid-statement, so park the rows
  -- out of range first and bring them back afterwards.
  update public.modules set order_number = order_number + 1000
   where course_id = v_course_id and order_number > v_module_offset;

  insert into public.modules (course_id, level_id, title, description, order_number) values
    (v_course_id, v_level, 'Using Notion Day to Day', 'Level 1 explained what Notion is and how to share it, then jumped straight to databases. This module fills the gap in between: finding your way around a workspace, and actually writing a page well. Both taught by Notion.', v_module_offset + 1)
  returning id into v_m1;

  insert into public.lessons (module_id, title, description, youtube_url, order_number, learning_objectives, notes, practice_activity, knowledge_check) values
    (v_m1, 'Where Everything Lives: the Sidebar', 'How a Notion workspace is organised and how to move around it — the mental model that stops a workspace turning into a pile of lost pages after three weeks.', 'https://www.youtube.com/watch?v=2aDk-misv58', 1,
      array['Explain the difference between private, shared and teamspace areas of the sidebar', 'Nest pages inside pages, and find a page again when you have forgotten where you put it', 'Use favourites and search rather than scrolling to reach frequent pages'],
      'The idea worth holding onto: in Notion almost everything is a page, and pages nest inside other pages. The sidebar is just a view of that nesting. Once that clicks, the tool stops feeling arbitrary.

The failure everyone hits in month one is a sidebar with forty top-level pages and no idea which is which. The fix is boring and it works: a small number of top-level pages that mean something to you — say Work, Clients, Personal, Archive — with everything else nested underneath. Favourite the three or four you open daily. Use search rather than hunting; Notion''s search is fast and reaches page content, not just titles.

ADDITION BEYOND THE VIDEO — what a paying client sees. If you set Notion up for a client or an employer, the sidebar IS the product as far as they are concerned. Somebody who opens the workspace and cannot find this week''s work will conclude the system does not work, whatever is inside it. Before you hand a workspace over, open it as someone else would (the sharing lesson in module 1 covers how) and check that the first screen answers "where do I start". That single check is the difference between a workspace that gets used and one that gets abandoned.

One practical note on cost: Notion''s free plan is generous for one person and small teams, but guests and some team features are limited. Check what plan a client is on before designing something that needs a paid tier.',
      'Create a workspace with four top-level pages that reflect how you actually think about your work — not a template you copied. Nest at least three pages under one of them. Favourite two. Then close everything, reopen Notion, and time how long it takes you to reach one specific nested page. If it takes more than a few seconds, the structure is wrong, not you: flatten it and try again.',
      '[{"question":"What is the underlying structure the sidebar is showing you?","options":["A folder system separate from your pages","Pages nested inside other pages — in Notion almost everything is a page","A database of files","A list of recently opened documents only"],"correct_index":1},{"question":"Why does the sidebar matter most when you build a workspace for a client?","options":["Because it affects how much Notion charges them","Because the sidebar is what they see first, and a workspace they cannot navigate gets abandoned regardless of what is inside it","Because search does not work on shared workspaces","Because clients cannot nest pages themselves"],"correct_index":1}]'::jsonb),
    (v_m1, 'Writing a Page That Reads Well', 'Document editing in Notion: blocks, formatting, and the small set of shortcuts that make writing fast instead of fiddly.', 'https://www.youtube.com/watch?v=PyXoQVc21cQ', 2,
      array['Build a page from blocks — headings, lists, toggles, callouts, dividers', 'Use the slash command and drag handles instead of hunting through menus', 'Structure a document so a reader can scan it'],
      'Everything on a Notion page is a block, and every block can be dragged, duplicated or turned into a different kind of block. That is the whole editing model. Typing "/" opens the block menu, and learning three or four commands — /h2, /todo, /toggle, /callout — covers most of what you will ever type.

Structure matters more than decoration. A page with real headings, short paragraphs and a toggle hiding the detail is readable; the same content as one long block is not, however nicely coloured. This is the same principle the copywriting path teaches about scanning readers, applied to internal documents: people skim work documents even harder than they skim marketing.

ADDITION BEYOND THE VIDEO — writing for the person who reads this in three months. Most internal documents are read by someone with no memory of why they were written, often the author. Two habits fix that cheaply: put the conclusion or current status at the top rather than the bottom, and date any section that will go stale. A page that opens with "Status as of 4 March: waiting on supplier quote" is worth more than three paragraphs of background above the same fact.

On a slow connection, Notion pages with many images load slowly. Keep images to what the page needs, and prefer a linked file over an embedded preview when the image is reference material rather than the point.',
      'Take something you have already written elsewhere — notes from a meeting, a plan, a list of instructions — and rebuild it as a Notion page using at least four different block types, including one toggle and one callout. Put the conclusion or status in the first line. Then read only the headings and the first line: does that alone tell someone what they need? If not, rewrite the headings until it does.',
      '[{"question":"What is the editing model in Notion?","options":["A word processor with page breaks and margins","Everything is a block, and any block can be moved, duplicated or converted into another type","A spreadsheet grid that accepts text","A markdown file you edit as plain text"],"correct_index":1},{"question":"Why put the conclusion or current status at the top of an internal document?","options":["Notion requires the first block to be a summary","It makes the page load faster","Because readers skim work documents, and the person reading in three months needs the current state before the background","It improves the page''s ranking in search engines"],"correct_index":2}]'::jsonb)
  on conflict (module_id, order_number) do nothing;

  -- Bring the shifted modules back, now sitting after the 1 new one(s).
  update public.modules set order_number = order_number - 1000 + 1
   where course_id = v_course_id and order_number > 1000;

end $$;

-- ============ Motion Graphics with After Effects ============
-- Auto-generated by scripts/curriculum/build-level-sql.mjs -- do not
-- hand-edit the lesson content below; regenerate from the source plan
-- JSON instead if something needs to change.

do $$
declare
  v_course_id uuid := '92455839-190c-4801-8aac-acfa44579671';
  v_level uuid;
  -- modules.order_number is unique per COURSE, not per level (a course's
  -- modules are numbered continuously across all its levels) -- so this
  -- can't just start at 1 for a level beyond the first. Computed here
  -- instead of hardcoded so this script works correctly regardless of how
  -- many modules the course already has.
  v_module_offset int;
  v_m1 uuid;
begin
  -- Appending to a level that already exists. Looked up rather than
  -- inserted, so this adds to the learner's current Level 1 instead of
  -- creating a duplicate one, and no existing module is re-parented.
  select id into v_level from public.levels
    where course_id = v_course_id and order_number = 1;

  if v_level is null then
    raise exception 'Level % not found for course % -- refusing to guess', 1, v_course_id;
  end if;

  -- The new modules must sit INSIDE this level, not at the end of the
  -- course. getOrderedLessons() builds the learner's lesson sequence from
  -- modules.order_number alone and ignores level, so a module appended at
  -- the course's max order would put beginner content after the final
  -- level's material. Insert straight after this level's last module and
  -- shift everything below it down instead.
  select coalesce(max(order_number), 0) into v_module_offset
    from public.modules where level_id = v_level;

  -- Two-phase shift: (course_id, order_number) is unique, and a single
  -- "+ N" update can trip that constraint mid-statement, so park the rows
  -- out of range first and bring them back afterwards.
  update public.modules set order_number = order_number + 1000
   where course_id = v_course_id and order_number > v_module_offset;

  insert into public.modules (course_id, level_id, title, description, order_number) values
    (v_course_id, v_level, 'Making Layers Work Together', 'Level 1 covered the interface and how a keyframe works. This module covers the next thing every real animation needs: getting layers to move in relation to each other, and making separate pieces look like one shot. Both from Adobe''s own video channel.', v_module_offset + 1)
  returning id into v_m1;

  insert into public.lessons (module_id, title, description, youtube_url, order_number, learning_objectives, notes, practice_activity, knowledge_check) values
    (v_m1, 'Parenting and Null Objects', 'How to make one layer follow another, and why a null object — an invisible layer that controls visible ones — is the tool professionals reach for constantly.', 'https://www.youtube.com/watch?v=TP1fEnJkzmQ', 1,
      array['Parent one layer to another so it inherits position, rotation and scale', 'Create a null object and use it to control several layers at once', 'Recognise when parenting is the right fix rather than animating each layer separately'],
      'This is the concept that separates animation you can edit from animation you have to redo. Parent a layer to another and it inherits that layer''s movement — move the parent, the child follows. A null object is an invisible layer that exists purely to be a parent, so you can move, rotate or scale a whole group of things by animating one control instead of six.

The practical test for whether you need it: if changing your mind about a movement means editing keyframes on more than one layer, parent them to a null and animate the null instead. Ten minutes spent rigging saves an hour of re-keying when the client asks for the logo to enter from the left instead.

One thing the video will not spell out: parenting inherits transform properties, not opacity or effects. If you want several layers to fade together, that is a different technique — put them in a pre-composition and fade the composition.

ADDITION BEYOND THE VIDEO — this matters more on a modest machine. After Effects is heavy, and older laptops common in Kenya will struggle with long previews. Rigging with nulls means fewer keyframes to evaluate and fewer full re-renders while you experiment, so a well-rigged composition previews noticeably faster than a badly rigged one doing the same thing. If your previews are still slow, the render lesson in Level 3 covers the settings that help.',
      'Build a simple scene with three shape layers — say a phone, a hand and a shadow. Animate them individually so they move across the screen together, and note how many keyframes you needed. Then undo it, create a null object, parent all three to the null, and animate only the null. Compare the keyframe counts. Finally, change your mind about the direction of travel and see how long each version takes to fix.',
      '[{"question":"What does a layer inherit when you parent it to another layer?","options":["All properties including opacity and effects","Transform properties — position, rotation and scale — but not opacity or effects","Only position","Nothing; parenting is only an organisational label"],"correct_index":1},{"question":"When is a null object the right tool?","options":["When you want a layer to be invisible in the final render","When you need to add a new colour to the composition","When changing your mind about a movement would otherwise mean re-keying several layers, so you animate one control instead","When the composition has more than ten layers"],"correct_index":2}]'::jsonb),
    (v_m1, 'Making Separate Pieces Look Like One Shot', 'Essential compositing techniques from Adobe — the adjustments that stop layered elements looking pasted on top of each other.', 'https://www.youtube.com/watch?v=vJ8X58uknsk', 2,
      array['Name the cues that make a composited element look fake', 'Match a foreground element to its background using colour, grain and light', 'Apply an adjustment layer so a correction affects everything beneath it'],
      'Compositing is the craft of making things that were never together look like they were filmed together. The cues that give it away are consistent and few: the added element is too clean, too sharp, lit from the wrong direction, or slightly the wrong colour temperature. Fixing those in that order fixes most shots.

The single most useful tool here is the adjustment layer — a layer that applies its effects to everything below it in the stack. Grading the whole shot on one adjustment layer, rather than applying the same effect five times, is both faster and the only way to keep it consistent when you change your mind.

A short video like this shows the techniques rather than drilling them. Watch it once for the list, then work through the practice below, then watch it again — the second viewing is where it lands.

ADDITION BEYOND THE VIDEO — where this earns money here. Straight compositing work is rare for a beginner, but the same skills sell constantly in a smaller form: dropping a client''s logo onto footage so it sits in the scene rather than floating over it, replacing a phone screen in a product video, or cleaning a distracting object out of a shot. Those are ordinary paid requests for small businesses and content creators, and they are worth more per job than basic cuts-only editing.',
      'Take any photograph of a room and any cut-out object — a product, a logo, a person. Place the object into the scene. Then work through the four cues in order: add a little blur so it is not sharper than the background, add grain to match, adjust its colour temperature towards the room''s light, and add a soft shadow on the side away from the light. Screenshot before and after. Finally, add an adjustment layer over both and grade the whole thing together.',
      '[{"question":"What does an adjustment layer do?","options":["It adjusts the composition''s frame rate","It applies its effects to every layer beneath it in the stack","It stores a backup copy of the layers below","It converts shape layers into footage"],"correct_index":1},{"question":"Which set of cues most commonly makes a composited element look fake?","options":["The file format and codec of the source image","The number of keyframes used to place it","Being too clean and sharp, lit from the wrong direction, and slightly the wrong colour temperature","The resolution of the composition"],"correct_index":2}]'::jsonb)
  on conflict (module_id, order_number) do nothing;

  -- Bring the shifted modules back, now sitting after the 1 new one(s).
  update public.modules set order_number = order_number - 1000 + 1
   where course_id = v_course_id and order_number > 1000;

end $$;
