-- Level 1 deepening: Print-on-Demand with Printful. ONE course. Additive
-- only, one new module of two lessons, taking Level 1 from 1 module / 2
-- lessons to 2 / 4.
--
-- THE GAP: Level 1 covered how print-on-demand works and how to get set
-- up, then Level 2 jumped to creating products. The step in between --
-- deciding WHO you are selling to, and getting the artwork onto the
-- garment properly -- is the one that decides whether anything sells at
-- all. Both videos from Printful Custom Printing, the vendor's own
-- channel.
--
-- THE METHOD THAT FOUND THIS. Yesterday's Notion finding -- that keyword
-- search missed an official channel the course was already using -- was
-- applied deliberately this firing. Every lesson id in ten previously
-- REJECTED courses was run back through the Data API to read its channel.
-- That surfaced Microsoft Power BI, a genuine vendor channel my keyword
-- searches had never returned, and confirmed there is no hidden vendor
-- behind Online Tutoring, Affiliate Marketing, WhatsApp Business,
-- No-Code App Building or Virtual Assistance -- those rejections stand on
-- better evidence than before.
--
-- POWER BI WAS THEN REJECTED ANYWAY, on the merits: Microsoft's own
-- "Getting started with the Power BI service" runs 2:50, under the floor,
-- and the channel's Power BI material dates to 2018. Guy in a Cube, run
-- by Microsoft's own Power BI team members and already used once in this
-- course, has a good workspaces video -- but at 2019 it shows a Service
-- UI that has since changed substantially. Finding the channel is not the
-- same as finding a usable video.
--
-- ON THE AGE OF THE NICHE VIDEO (2019): niche selection is advice about
-- PEOPLE, not about software, and nothing in it has been invalidated.
-- Printful's Design Maker tour from the same year was rejected on exactly
-- that distinction -- its UI has changed. Staleness of fact, not age of
-- upload.
--
-- Written into the notes rather than left implicit: which niches are
-- realistic for a Kenyan designer given the course's opening warning that
-- Printful ships from the US, EU, Mexico and Japan -- the diaspora, and
-- anything where local knowledge is a genuine advantage over the average
-- competitor.
--
-- Every id confirmed through the YouTube Data API for channel, exact
-- title, duration and embeddability. Both run 7:36-7:38.
--
-- Both new lessons carry objectives, notes, a practice activity and a
-- knowledge check, so the 438-lesson bare backlog does not grow.

-- Auto-generated by scripts/curriculum/build-level-sql.mjs -- do not
-- hand-edit the lesson content below; regenerate from the source plan
-- JSON instead if something needs to change.

do $$
declare
  v_course_id uuid := 'e7f083f8-3f7d-4b1b-865c-651f3d09170a';
  v_level uuid;
  -- modules.order_number is unique per COURSE, not per level (a course's
  -- modules are numbered continuously across all its levels) -- so this
  -- can't just start at 1 for a level beyond the first. Computed here
  -- instead of hardcoded so this script works correctly regardless of how
  -- many modules the course already has.
  v_module_offset int;
  v_m1 uuid;
begin
  -- Appending to a level that already exists. Looked up rather than
  -- inserted, so this adds to the learner's current Level 1 instead of
  -- creating a duplicate one, and no existing module is re-parented.
  select id into v_level from public.levels
    where course_id = v_course_id and order_number = 1;

  if v_level is null then
    raise exception 'Level % not found for course % -- refusing to guess', 1, v_course_id;
  end if;

  -- The new modules must sit INSIDE this level, not at the end of the
  -- course. getOrderedLessons() builds the learner's lesson sequence from
  -- modules.order_number alone and ignores level, so a module appended at
  -- the course's max order would put beginner content after the final
  -- level's material. Insert straight after this level's last module and
  -- shift everything below it down instead.
  select coalesce(max(order_number), 0) into v_module_offset
    from public.modules where level_id = v_level;

  -- Two-phase shift: (course_id, order_number) is unique, and a single
  -- "+ N" update can trip that constraint mid-statement, so park the rows
  -- out of range first and bring them back afterwards.
  update public.modules set order_number = order_number + 1000
   where course_id = v_course_id and order_number > v_module_offset;

  insert into public.modules (course_id, level_id, title, description, order_number) values
    (v_course_id, v_level, 'Deciding What to Sell, and Making It Print Right', 'Level 1 covered how print-on-demand works and how to get set up, then Level 2 jumped to creating products. This module is the step in between, and it is the one that decides whether anything sells: choosing who you are selling to, and getting the artwork onto the garment properly.', v_module_offset + 1)
  returning id into v_m1;

  insert into public.lessons (module_id, title, description, youtube_url, order_number, learning_objectives, notes, practice_activity, knowledge_check) values
    (v_m1, 'Choosing a Niche Instead of Selling to Everybody', 'Why print-on-demand shops that sell ''nice designs'' to nobody in particular fail, and how to pick a group of people specific enough to actually reach. From Printful.', 'https://www.youtube.com/watch?v=lY3c6EW4Iu4', 1,
      array['Explain why a narrow niche outsells a general store in print-on-demand', 'Test whether a niche is large enough to sell to and specific enough to find', 'Judge a niche by whether you can name where its people already gather online'],
      'The whole argument in one line: you are not competing on price or quality, because everyone using print-on-demand has the same blank shirts and similar prices. You compete on being obviously FOR someone. A shirt that a nurse, or a Rift Valley cyclist, or a Kiswahili teacher sees and thinks "that is about me" outsells a well-drawn generic design every time.

The practical test for a niche has two halves, and both must pass. Is it big enough that thousands of people are in it? And can you name the specific places those people already gather — a subreddit, a Facebook group, a hashtag, a YouTube channel with comments? If you cannot name where they are, you cannot advertise to them, and the design will never be seen no matter how good it is.

A note on this video''s age: it was uploaded in 2019. Niche selection is advice about people rather than about software, and none of it has been invalidated — unlike Printful''s interface, which has changed and is covered by newer videos elsewhere in this course.

ADDITION BEYOND THE VIDEO — niches that work from Kenya specifically. Remember the course''s opening warning: Printful ships from the US, EU, Mexico and Japan, so you are selling to customers abroad. That shapes which niches are realistic. Two that suit a Kenyan designer well: the diaspora, who want designs about home and are already abroad where shipping is cheap; and anything where you have genuine knowledge outsiders lack — Swahili wordplay, specific football fan cultures, safari and conservation, African textile motifs done properly rather than as a stereotype. Your advantage is knowing something the average competitor does not. Do not throw that away by making the same generic slogans as everyone else.',
      'Write down three possible niches. For each, answer both halves of the test in writing: roughly how many people are in it, and name at least two specific places online where those people gather — with a link. Then cross out any niche where you could not name a place. If all three are crossed out, they were audiences you imagined rather than found; try again with groups you actually belong to or know well.',
      '[{"question":"Why does a narrow niche outsell a general store in print-on-demand?","options":["Niche products cost less to print","Everyone has the same blanks and similar prices, so you compete on being obviously for someone — a person who sees themselves in a design buys it","Printful gives priority shipping to niche stores","Search engines rank niche shops higher automatically"],"correct_index":1},{"question":"What is the second half of the niche test, after ''is it big enough''?","options":["Whether the designs can be made in under an hour","Whether the niche is trending this month","Whether you can name the specific places those people already gather online — because if you cannot, you cannot reach them","Whether competitors already sell to it"],"correct_index":2}]'::jsonb),
    (v_m1, 'Getting the Print in the Right Place', 'Printful''s design placement guide: sizing, positioning and the file requirements that decide whether a print comes out looking professional or amateur.', 'https://www.youtube.com/watch?v=YnaTmDCSdh0', 2,
      array['Position and size a design on a garment so it looks deliberate rather than accidental', 'Supply artwork at a resolution and format that prints cleanly', 'Account for how placement shifts across garment sizes'],
      'This is the difference between a shirt that looks bought and a shirt that looks homemade, and it is almost entirely mechanical. Get the print too small and it looks lost; too high and it rides up under the collar; too low and it disappears into the belly. The video gives the actual measurements — use them rather than eyeballing it in the mockup.

Resolution is where beginners lose money. A design that looks fine on screen can print blurry, because a screen shows far less detail than a print does. Work at the size and resolution Printful specifies, in a file format that keeps transparency, and never scale a small image up to fit — enlarging adds no detail, it only makes the missing detail bigger.

One thing worth knowing that the video touches on lightly: the SAME placement measurements apply across garment sizes, so a design centred perfectly on a medium will sit slightly differently on a 3XL. For most designs this does not matter. For anything that must line up with a seam or a pocket, check the extremes, not just the middle size.

ADDITION BEYOND THE VIDEO — order a sample of your best-selling design before you push it hard. Printful offers contributor samples at a discount. Yes, shipping to Kenya is slow and expensive, which is exactly why you do this once, for the design you are about to spend advertising money on, rather than for every product. Seeing your own print in your hands catches problems no mockup shows: colours that shifted, a print that is scratchier than expected, a placement that looked right on screen and sits wrong on a body.',
      'Take one design and place it on a t-shirt in Printful three times: once at the recommended size and position, once noticeably too small, and once too high. Generate a mockup of each and put them side by side. Write one sentence on what specifically gives the two wrong ones away. Then check your design file: what is its actual pixel size, and does it meet the requirement without being scaled up?',
      '[{"question":"Why can a design that looks fine on screen still print blurry?","options":["Printers reduce the quality of all uploaded files","A print shows far more detail than a screen does, so a low-resolution file that looks acceptable on a monitor has no detail to print","Transparency is removed during printing","The mockup generator compresses the image"],"correct_index":1},{"question":"Why order a physical sample of your best design despite slow, expensive shipping to Kenya?","options":["Printful requires a sample before a design can be listed","It is cheaper than generating mockups","Because it catches colour shifts, print texture and placement problems that no mockup reveals — and you do it once, for the design you are about to spend advertising money on","Samples arrive faster than customer orders"],"correct_index":2}]'::jsonb)
  on conflict (module_id, order_number) do nothing;

  -- Bring the shifted modules back, now sitting after the 1 new one(s).
  update public.modules set order_number = order_number - 1000 + 1
   where course_id = v_course_id and order_number > 1000;

end $$;
