-- Level 1 deepening: Photo Editing & Retouching (Photoshop). ONE course.
-- Additive only, one new module of two lessons, taking Level 1 from
-- 1 module / 2 lessons to 2 / 4.
--
-- THE GAP, and it was a real hole: Level 1 taught the interface and
-- layers, then Level 2 went straight to masks and retouching. SELECTION
-- -- telling Photoshop which pixels you mean -- is the skill both of
-- those depend on, and the course never taught it. A mask is a selection
-- made permanent; the course was teaching the second thing without the
-- first.
--
-- The 9 September 18:00 firing found Adobe's selection-tools video and
-- recorded that Photoshop was ONE VIDEO SHORT of a module. This firing
-- found the second on a different Adobe channel: "Adobe Creative Cloud",
-- distinct from "Adobe Photoshop", which none of the earlier searches had
-- surfaced. The two pair naturally -- select the thing, then change it --
-- and recolouring a product is the job a beginner is actually paid for.
--
-- REJECTED, and why: Adobe's own "How to Remove Unwanted Objects"
-- (4:57) is good but overlaps Level 2's existing spot-healing and patch
-- lesson. Adobe's "Photoshop CC Overview" runs 1:47 and dates to 2014.
-- "How To Customize Your Photoshop Workspace" runs 2:19. All three from
-- official Adobe channels -- the constraint here was never attribution.
--
-- OVERLAP CHECKED, not assumed: Level 3 teaches Levels and Curves, which
-- adjust the WHOLE image. The new colour lesson is the local version --
-- one object, everything else untouched. The notes say so explicitly and
-- tell the learner which scope a given job needs, so the two read as a
-- progression rather than a repetition.
--
-- Written into the notes rather than left out: that hair and fur defeat
-- quick selection and should be priced as a different job; that hue
-- shifting fails on white, black and grey because there is no hue to
-- shift, so say so before quoting; and that recolouring a product to a
-- colour it does not come in is misrepresentation that costs a seller
-- their reviews.
--
-- Every id confirmed through the YouTube Data API for channel, exact
-- title, duration and embeddability. Both run 4:08 and 5:21.
--
-- Both new lessons carry objectives, notes, a practice activity and a
-- knowledge check, so the 438-lesson bare backlog does not grow.

-- Auto-generated by scripts/curriculum/build-level-sql.mjs -- do not
-- hand-edit the lesson content below; regenerate from the source plan
-- JSON instead if something needs to change.

do $$
declare
  v_course_id uuid := 'b7d42222-30d1-4966-8f60-a5e348d88053';
  v_level uuid;
  -- modules.order_number is unique per COURSE, not per level (a course's
  -- modules are numbered continuously across all its levels) -- so this
  -- can't just start at 1 for a level beyond the first. Computed here
  -- instead of hardcoded so this script works correctly regardless of how
  -- many modules the course already has.
  v_module_offset int;
  v_m1 uuid;
begin
  -- Appending to a level that already exists. Looked up rather than
  -- inserted, so this adds to the learner's current Level 1 instead of
  -- creating a duplicate one, and no existing module is re-parented.
  select id into v_level from public.levels
    where course_id = v_course_id and order_number = 1;

  if v_level is null then
    raise exception 'Level % not found for course % -- refusing to guess', 1, v_course_id;
  end if;

  -- The new modules must sit INSIDE this level, not at the end of the
  -- course. getOrderedLessons() builds the learner's lesson sequence from
  -- modules.order_number alone and ignores level, so a module appended at
  -- the course's max order would put beginner content after the final
  -- level's material. Insert straight after this level's last module and
  -- shift everything below it down instead.
  select coalesce(max(order_number), 0) into v_module_offset
    from public.modules where level_id = v_level;

  -- Two-phase shift: (course_id, order_number) is unique, and a single
  -- "+ N" update can trip that constraint mid-statement, so park the rows
  -- out of range first and bring them back afterwards.
  update public.modules set order_number = order_number + 1000
   where course_id = v_course_id and order_number > v_module_offset;

  insert into public.modules (course_id, level_id, title, description, order_number) values
    (v_course_id, v_level, 'Choosing What to Change', 'Level 1 taught the interface and layers, then Level 2 went straight to masks and retouching. Selection — telling Photoshop which part of the picture you mean — is the skill both of those depend on, and it was missing. This module adds it, and then puts it to work on the job clients ask for most.', v_module_offset + 1)
  returning id into v_m1;

  insert into public.lessons (module_id, title, description, youtube_url, order_number, learning_objectives, notes, practice_activity, knowledge_check) values
    (v_m1, 'Selection Tools: Telling Photoshop What You Mean', 'The selection tools and when each one is the right choice. From Adobe.', 'https://www.youtube.com/watch?v=PQtDXAQs37U', 1,
      array['Choose between the object, quick, lasso and marquee selection tools for a given subject', 'Refine a rough selection rather than restarting it', 'Explain why a selection is the foundation of masking and local adjustments'],
      'A selection is just Photoshop''s way of knowing which pixels you are talking about. Almost everything precise you will ever do — cutting a product out of its background, brightening one face, recolouring a shirt — starts here. The masking lesson in Level 2 is selections made permanent and editable; that is all a mask is.

Which tool, quickly. Object selection when the subject is distinct and Photoshop can find it for you — start here, because it is often right and costs seconds. Quick selection when you want to paint the area roughly and let it snap to edges. Lasso when the shape is irregular and you will do it by hand. Marquee when you genuinely want a rectangle or an ellipse.

The habit that separates fast work from slow: do not restart a selection when it comes out imperfect. Hold Shift to add to it and Alt (Option on a Mac) to subtract. Nearly every real selection is built up in three or four passes rather than captured in one.

ADDITION BEYOND THE VIDEO — hair, and when to stop. Hair, fur and motion blur defeat every quick tool, and the honest answer for a beginner is not to fight them: Select and Mask with Refine Edge exists for this, and even with it, hair on a busy background can take twenty minutes. Price accordingly. When a client sends you a product shot on a plain white background, that is a five-minute job; when they send a person with curly hair against a tree, it is not the same job and should not be the same price.',
      'Take one photo with a clear subject and select it three ways: with the object selection tool, with quick selection, and with the lasso. Time each. Then deliberately make a bad selection and repair it using Shift to add and Alt to subtract rather than starting again. Finally, put the selection on a new layer so you can see exactly what you captured — the edges will tell you the truth that the marching ants hide.',
      '[{"question":"What is the relationship between a selection and a layer mask?","options":["They are unrelated features","A mask is a selection made permanent and editable — which is why selection is the foundation of masking","A mask can only be made from a rectangular selection","A selection replaces the need for a mask"],"correct_index":1},{"question":"Your selection comes out imperfect. What should you do?","options":["Start again with a different tool","Accept it and fix the result later with the eraser","Add to it with Shift and subtract with Alt — most real selections are built in several passes","Increase the image resolution and retry"],"correct_index":2}]'::jsonb),
    (v_m1, 'Changing the Colour of One Thing', 'Recolouring a specific object — a shirt, a product, a logo — without touching the rest of the picture. From Adobe.', 'https://www.youtube.com/watch?v=4jG77DO8Jcw', 2,
      array['Recolour a selected object using a targeted adjustment rather than painting over it', 'Keep the object''s shadows and texture intact while changing its hue', 'Explain why this is a non-destructive adjustment and not a paint job'],
      'This is the request a beginner gets paid for more than any other: the client likes the photo but wants the shirt in blue, or the packaging in the new brand colour, or six colourways of one product from a single shoot.

The method that works keeps the original pixels. You select the object, then add a Hue/Saturation adjustment clipped to that selection, and shift the hue. Because the adjustment only changes colour values and leaves lightness alone, the folds, shadows and texture survive — which is exactly what painting over the object with the brush destroys, and why painted recolours look like stickers.

One limit worth knowing before you promise a client anything: hue shifting works beautifully on saturated colours and poorly on white, black and grey, because there is no hue there to shift. Turning a white shirt red is a different and harder job than turning a red shirt blue. Say so before quoting.

HOW THIS RELATES TO THE REST OF THE COURSE: Level 3 covers Levels and Curves, which adjust exposure and colour across the WHOLE image. This lesson is the local version — one object, everything else untouched. Same idea, different scope, and knowing which one a job needs is most of the skill.

ADDITION BEYOND THE VIDEO — a warning about honesty in product work. Recolouring a product photo to a colour the product does not come in is misrepresentation, and a customer who receives the wrong colour will say so publicly. Use this to show real variants, not imaginary ones. If you sell on Jumia, Instagram or WhatsApp, that review is the whole business.',
      'Find a photo of something with a strong, saturated colour — a jacket, a bag, a painted wall. Select it, add a clipped Hue/Saturation adjustment, and produce three different colourways. Check each at full size: do the shadows and creases still read, or has it gone flat? Then try the same technique on something white and write one sentence on what happened and why.',
      '[{"question":"Why use a clipped Hue/Saturation adjustment rather than painting the new colour on with a brush?","options":["It uses less memory","It changes colour values while leaving lightness alone, so folds, shadows and texture survive — painting over them destroys those and looks like a sticker","Brushes cannot produce accurate colours","Adjustment layers export faster"],"correct_index":1},{"question":"Why is recolouring a white object harder than recolouring a red one?","options":["White objects are usually larger in the frame","Photoshop cannot select white objects","Hue shifting moves an existing hue, and white has no hue to shift","White reflects more light so the file is bigger"],"correct_index":2}]'::jsonb)
  on conflict (module_id, order_number) do nothing;

  -- Bring the shifted modules back, now sitting after the 1 new one(s).
  update public.modules set order_number = order_number - 1000 + 1
   where course_id = v_course_id and order_number > 1000;

end $$;
