-- Level 1 deepening: Online Tutoring & Course Creation. ONE course.
-- Additive only, one new module of two lessons, taking Level 1 from
-- 1 module / 2 lessons to 2 / 4.
--
-- THE GAP: the course went from "what online tutoring is" straight to
-- "recording your first lesson". There was no planning step at all --
-- which is the order most people actually work in, and the reason most
-- first courses are abandoned halfway through. It gains deciding what the
-- course is for, and scripting.
--
-- SOURCE: Thinkific, a course-hosting platform, whose own channel carries
-- a real course-design series. Found by applying the several-channels-
-- per-vendor lesson to course platforms rather than to the subject --
-- earlier searches for "online course creation" returned only individual
-- creators. The two lessons chosen are CRAFT, not a product tour: the
-- advice transfers to Udemy, Preply, a YouTube channel or a WhatsApp
-- group, and the notes say so.
--
-- REJECTED: Thinkific's "Introduction to Your First Course" (2:32), under
-- the floor. "How to Create Your First Course" (5:29) and "How to Design
-- and Brand Your Online Course" (16:55) clear it but are closer to
-- platform walkthroughs -- logged as leads for Level 2, where the course
-- already teaches Udemy and Preply mechanics.
--
-- ON THE 2016 SCRIPTING VIDEO: scripting is craft about speaking and
-- planning, not about software, so nothing in it has been overtaken. Same
-- test applied to Printful's niche video and the Indeed interview set --
-- staleness of fact, not age of upload.
--
-- ZAPIER IS NOW CLOSED. Its newest beginner video, "New to Zapier? Build
-- Your First Lead Automation", runs 22 seconds. With the 15s and 19s
-- finds from 8 September, the channel is Shorts-only and
-- workflow-automation-zapier cannot be deepened from the vendor at any
-- floor this project would accept.
--
-- Every id confirmed through the YouTube Data API for channel, exact
-- title, duration and embeddability. Both run 3:34 and 4:53.
--
-- Both new lessons carry objectives, notes, a practice activity and a
-- knowledge check, so the 438-lesson bare backlog does not grow.

-- Auto-generated by scripts/curriculum/build-level-sql.mjs -- do not
-- hand-edit the lesson content below; regenerate from the source plan
-- JSON instead if something needs to change.

do $$
declare
  v_course_id uuid := '77eae361-a386-4ebb-b130-cb43b73e3421';
  v_level uuid;
  -- modules.order_number is unique per COURSE, not per level (a course's
  -- modules are numbered continuously across all its levels) -- so this
  -- can't just start at 1 for a level beyond the first. Computed here
  -- instead of hardcoded so this script works correctly regardless of how
  -- many modules the course already has.
  v_module_offset int;
  v_m1 uuid;
begin
  -- Appending to a level that already exists. Looked up rather than
  -- inserted, so this adds to the learner's current Level 1 instead of
  -- creating a duplicate one, and no existing module is re-parented.
  select id into v_level from public.levels
    where course_id = v_course_id and order_number = 1;

  if v_level is null then
    raise exception 'Level % not found for course % -- refusing to guess', 1, v_course_id;
  end if;

  -- The new modules must sit INSIDE this level, not at the end of the
  -- course. getOrderedLessons() builds the learner's lesson sequence from
  -- modules.order_number alone and ignores level, so a module appended at
  -- the course's max order would put beginner content after the final
  -- level's material. Insert straight after this level's last module and
  -- shift everything below it down instead.
  select coalesce(max(order_number), 0) into v_module_offset
    from public.modules where level_id = v_level;

  -- Two-phase shift: (course_id, order_number) is unique, and a single
  -- "+ N" update can trip that constraint mid-statement, so park the rows
  -- out of range first and bring them back afterwards.
  update public.modules set order_number = order_number + 1000
   where course_id = v_course_id and order_number > v_module_offset;

  insert into public.modules (course_id, level_id, title, description, order_number) values
    (v_course_id, v_level, 'Planning a Course Before You Record It', 'Level 1 went straight from what online tutoring is to recording your first lesson — which is the order most people do it in, and the reason most first courses are abandoned halfway through. This module is the planning that belongs before the camera comes out. Both lessons from Thinkific, a course-hosting platform, but the craft transfers to Udemy, Preply, a YouTube channel or a WhatsApp group.', v_module_offset + 1)
  returning id into v_m1;

  insert into public.lessons (module_id, title, description, youtube_url, order_number, learning_objectives, notes, practice_activity, knowledge_check) values
    (v_m1, 'Deciding What the Course Is Actually For', 'How to plan a course around the outcome a student wants, and turn that into an outline you can actually finish.', 'https://www.youtube.com/watch?v=9GiIT-0b3Ks', 1,
      array['State a course''s promise as a specific outcome rather than a topic', 'Turn that outcome into an ordered outline of lessons', 'Cut material that does not serve the outcome, however interesting it is'],
      'The single decision that makes a course finishable is the promise. "Excel" is a topic and has no end. "By the end of this, you can build a stock sheet for a small shop that totals itself" is an outcome, and it tells you exactly which lessons belong and which do not.

Work backwards from the outcome. What must someone be able to do at the end? What must they be able to do just before that? Keep going until you reach what they can already do on day one. That chain, reversed, is your outline — and it is usually far shorter than the course you imagined, which is a good thing.

The most common beginner mistake is teaching everything you know. Your knowledge is not the curriculum; the student''s destination is. Material you love that does not serve the outcome goes in a second course, or nowhere.

ADDITION BEYOND THE VIDEO — what sells here. A course promising a specific, checkable outcome sells better in this market than a broad survey, because the buyer can tell whether it worked. "Pass the CPA Section 1 mock" or "set up an M-Pesa Till and reconcile it weekly" are promises someone can judge. It also protects you: a student who wanted something you never promised cannot fairly complain, and a refund request usually traces back to a vague promise rather than bad teaching.

On scope, be realistic about your own time. A five-hour course you never finish earns nothing. A forty-minute course that delivers one outcome cleanly can be published this month and improved later.',
      'Write one sentence: "By the end of this course, you will be able to ___." It must contain a verb someone could be watched doing. Then work backwards and list every step from that outcome to what a beginner can already do, in reverse order. Reverse the list — that is your outline. Finally, cross out every item that does not move the student toward the outcome, and count what is left. If it is under ten lessons, you have a course you can actually finish.',
      '[{"question":"What is wrong with planning a course around a topic like \"Excel\"?","options":["Topics are harder to film than outcomes","A topic has no end, so nothing tells you which lessons belong and which do not — an outcome does","Platforms reject topic-based courses","Topics cannot be priced"],"correct_index":1},{"question":"How do you build the outline from the outcome?","options":["List everything you know about the subject, then order it","Copy the structure of a competitor''s course","Work backwards from the outcome to what the student can already do, then reverse that chain","Start with the easiest lessons and keep going until you run out of ideas"],"correct_index":2}]'::jsonb),
    (v_m1, 'Scripting So You Sound Like Yourself', 'How much to script, what to write down, and why reading a full script aloud almost always sounds worse than planning one properly.', 'https://www.youtube.com/watch?v=aIA9LwGMAHY', 2,
      array['Choose between a full script, a beat sheet and bullet notes for a given lesson', 'Write an opening that tells the student what this lesson gives them', 'Plan a lesson so a mistake mid-recording costs one take, not the whole file'],
      'Most people go to one of two extremes: no plan at all, which produces rambling and long silences, or a word-for-word script read aloud, which sounds like a hostage video. The middle is what works — know your opening line exactly, know the two or three beats you must hit, and improvise the connective tissue.

The opening earns the rest. In the first fifteen seconds say what this lesson lets the student do, not who you are. "In this lesson you will build the formula that totals your stock sheet automatically" beats a minute of introduction, and it is also what makes a free preview lesson convert.

Record in short segments with a natural break between beats. If you fluff a sentence twenty minutes into a single take, you either re-record everything or spend an hour editing; if your beats are three minutes each, you re-record three minutes. This one habit saves more time than any editing skill.

A note on this video''s age: it is from 2016. Scripting is craft about speaking and planning, not about software, and nothing in it has been overtaken — the same test this platform applies elsewhere, staleness of fact rather than age of upload.

ADDITION BEYOND THE VIDEO — recording in a real Kenyan room. Your phone is a good enough camera; the audio is what makes a course sound cheap. Record in a small room with soft things in it — a bedroom with a mattress and curtains beats a large tiled hall every time. Turn off the fan. Record a few seconds of silence before you start so an editor can use it. And if there is generator noise or matatu traffic outside, wait rather than push on: viewers forgive shaky video and abandon bad sound.',
      'Take the first lesson from the outline you built. Write its opening line word for word — it must name what the student will be able to do. Then write only the two or three beats the lesson must hit, as bullets, and nothing else. Record it on your phone in one three-minute take. Play it back and mark where you rambled. Re-record only the beat that went wrong, not the whole thing.',
      '[{"question":"Why does a full word-for-word script usually sound worse than a planned outline?","options":["Scripts take longer to write","Reading aloud flattens delivery; knowing the opening line and the required beats while improvising the rest sounds like a person talking","Platforms penalise scripted courses","A script cannot include technical terms"],"correct_index":1},{"question":"Why record in short segments rather than one long take?","options":["Short files upload faster","Platforms limit video length","A fluffed sentence costs you one short re-record instead of the whole take or an hour of editing","Short segments score better in search"],"correct_index":2}]'::jsonb)
  on conflict (module_id, order_number) do nothing;

  -- Bring the shifted modules back, now sitting after the 1 new one(s).
  update public.modules set order_number = order_number - 1000 + 1
   where course_id = v_course_id and order_number > 1000;

end $$;
