-- Level 1 deepening: Affiliate Marketing, and No-Code App Building.
-- Additive only, one new module of two lessons each. Both go from
-- 1 module / 2 lessons to 2 / 4.
--
-- AFFILIATE MARKETING explained what it is and how to pick a niche, then
-- stopped -- before the learner knew what they would actually build or
-- whether the business still works. It gains Ahrefs' site blueprint and,
-- deliberately, Ahrefs' 2026 piece on what Google's helpful-content and
-- spam updates did to affiliate sites. A course that teaches this model
-- without saying that is out of date, and the honest version is also more
-- useful: the sites that survived had first-hand experience, which a
-- Kenyan learner writing about local prices and conditions has by
-- definition and almost nobody else is writing.
--
-- The notes also answer the question nobody answers for learners here:
-- CHECK THE PAYOUT METHOD FIRST. Amazon Associates does not pay to Kenyan
-- bank accounts by default. Months of work for a balance that cannot be
-- withdrawn is the single most wasted effort in this field, and the
-- lesson says to confirm it from the programme's own terms page.
--
-- NO-CODE APP BUILDING asked what no-code is and compared tools, then
-- Level 2 built in specific apps. The concepts underneath -- a screen is
-- a tree of components, and an app needs a database -- are identical in
-- every tool and were never taught. FlutterFlow is the worked example
-- because FlutterFlow University teaches them properly; the notes name
-- the equivalent vocabulary in Glide, Adalo and Bubble so the ideas
-- travel.
--
-- This also partly offsets a known defect: the Level 2 Glide lessons use
-- Glide's older product, which the vendor has moved on from. The new
-- module is the durable part.
--
-- SOURCING NOTE: both channels were found by pointing the several-
-- channels-per-vendor lesson at adjacent categories -- Ahrefs publishes a
-- numbered affiliate course, not just SEO, and FlutterFlow runs a
-- separate "FlutterFlow University" teaching series.
--
-- REJECTED on duration, all from the same two channels: Ahrefs' [1.1]
-- (1:59), [1.2] (2:33) and [1.3] (1:56) -- a numbered course whose early
-- parts are all under the floor. Ahrefs' "Complete Affiliate Marketing
-- Course for Beginners" runs 1h48m, too long for a Level 1 lesson when
-- data costs money. FlutterFlow's "Tour of FlutterFlow" (10:18) clears
-- everything but duplicates Level 1's existing tool comparison.
--
-- Every id confirmed through the YouTube Data API for channel, exact
-- title, duration and embeddability. The four run 4:18 to 10:58.
--
-- All four new lessons carry objectives, notes, a practice activity and a
-- knowledge check, so the 438-lesson bare backlog does not grow.

-- ============ Affiliate Marketing ============
-- Auto-generated by scripts/curriculum/build-level-sql.mjs -- do not
-- hand-edit the lesson content below; regenerate from the source plan
-- JSON instead if something needs to change.

do $$
declare
  v_course_id uuid := '4dead527-2b53-4173-8bd9-e0b20707c738';
  v_level uuid;
  -- modules.order_number is unique per COURSE, not per level (a course's
  -- modules are numbered continuously across all its levels) -- so this
  -- can't just start at 1 for a level beyond the first. Computed here
  -- instead of hardcoded so this script works correctly regardless of how
  -- many modules the course already has.
  v_module_offset int;
  v_m1 uuid;
begin
  -- Appending to a level that already exists. Looked up rather than
  -- inserted, so this adds to the learner's current Level 1 instead of
  -- creating a duplicate one, and no existing module is re-parented.
  select id into v_level from public.levels
    where course_id = v_course_id and order_number = 1;

  if v_level is null then
    raise exception 'Level % not found for course % -- refusing to guess', 1, v_course_id;
  end if;

  -- The new modules must sit INSIDE this level, not at the end of the
  -- course. getOrderedLessons() builds the learner's lesson sequence from
  -- modules.order_number alone and ignores level, so a module appended at
  -- the course's max order would put beginner content after the final
  -- level's material. Insert straight after this level's last module and
  -- shift everything below it down instead.
  select coalesce(max(order_number), 0) into v_module_offset
    from public.modules where level_id = v_level;

  -- Two-phase shift: (course_id, order_number) is unique, and a single
  -- "+ N" update can trip that constraint mid-statement, so park the rows
  -- out of range first and bring them back afterwards.
  update public.modules set order_number = order_number + 1000
   where course_id = v_course_id and order_number > v_module_offset;

  insert into public.modules (course_id, level_id, title, description, order_number) values
    (v_course_id, v_level, 'What It Actually Takes, in 2026', 'Level 1 explained what affiliate marketing is and how to pick a niche, then stopped. This module covers the two things a learner needs before spending months on it: what you actually build, and the honest state of the business now that Google''s updates have wiped out a great many affiliate sites. Both from Ahrefs.', v_module_offset + 1)
  returning id into v_m1;

  insert into public.lessons (module_id, title, description, youtube_url, order_number, learning_objectives, notes, practice_activity, knowledge_check) values
    (v_m1, 'The Blueprint: What You Are Actually Building', 'The concrete shape of an affiliate site — the pages, the structure and the order to build them in — so the plan stops being abstract.', 'https://www.youtube.com/watch?v=559bgY-8aV8', 1,
      array['Describe the page types an affiliate site needs and what each one is for', 'Order the build so the first pages published are the ones that can earn', 'Recognise why a pile of unstructured posts does not become a business'],
      'The useful shift here is from "I will write about my niche" to "I will build these specific pages". Affiliate sites that earn are structured: pages that answer a buying question, pages that compare options, and pages that catch people who are still learning. They link to each other on purpose.

Build order matters more than people expect. Publishing twenty general articles before a single page that could earn is the most common way a year disappears with no income. Start with the pages closest to a purchase decision, because those are the ones an affiliate link belongs on at all.

ADDITION BEYOND THE VIDEO — the money question nobody answers for Kenyan learners. Most large affiliate programmes pay by bank transfer, PayPal or cheque. Amazon Associates does not pay to Kenyan bank accounts by default and its threshold and methods vary by country, so CHECK THE PAYOUT METHOD BEFORE you build anything around a programme. This is the single most wasted effort in affiliate marketing here: months of work for a balance that cannot be withdrawn. Programmes that pay via PayPal, Wise or direct international transfer are the practical starting point, and you should confirm it in writing from the programme''s own terms page, not from a YouTube video.

Also worth planning for: a site takes months to earn anything. If you need money this quarter, the freelancing, virtual assistance or print-on-demand paths on this platform pay sooner. Affiliate marketing is a slow asset, and treating it as quick income is how people give up at month three.',
      'Sketch your site on one page: list the first five pages you would publish, and next to each write which one could carry an affiliate link and why someone reading it would be close to buying. Then pick one affiliate programme in your niche, find its terms page, and write down its payout methods, minimum threshold and whether it pays to Kenya. If you cannot find that in writing, that is your answer about the programme.',
      '[{"question":"Why does build order matter on an affiliate site?","options":["Search engines index older pages first","Publishing many general articles before any page close to a purchase decision is how a year passes with no income","Affiliate programmes require a minimum page count","Hosting costs rise with the number of pages"],"correct_index":1},{"question":"What should you confirm about an affiliate programme before building around it?","options":["How many other affiliates it has","Whether its website looks professional","Its payout methods, threshold and whether it actually pays to Kenya — in writing, from its own terms","Whether it offers a mobile app"],"correct_index":2}]'::jsonb),
    (v_m1, 'What Google''s Updates Did, and What Still Works', 'An honest look at the affiliate business after the search updates that destroyed many affiliate sites — and what the ones that survived did differently.', 'https://www.youtube.com/watch?v=Sk8MAbD39Qw', 2,
      array['Explain why large numbers of affiliate sites lost their traffic', 'Identify what distinguished the sites that kept growing', 'Decide honestly whether this model suits what you can actually offer'],
      'This lesson exists because the alternative is selling you a dream. Google''s helpful-content and spam updates removed the traffic from an enormous number of affiliate sites, including ones built exactly as older tutorials taught. Any course that teaches affiliate marketing without saying so is out of date.

What the survivors had in common is not a trick. It is first-hand experience worth reading — actually using the product, actually knowing the field, showing something a summary of other people''s reviews cannot show. Sites that rewrote what was already online lost. Sites with something of their own kept going.

That is a demanding bar, and it is also an opportunity if you take it seriously: you know things about your market that an overseas affiliate writer does not. Prices in Nairobi shops, which models actually survive local conditions, what the warranty situation really is, which seller delivers. That is first-hand content by definition, and almost nobody is writing it.

ADDITION BEYOND THE VIDEO — decide now, before the work. Ask yourself honestly: can I write something about this niche that is not already on the internet? If the answer is no, affiliate marketing will be a long, unpaid apprenticeship. If the answer is yes — you repair phones, you farm, you teach, you have used the thing — then you have the one asset the surviving sites have, and the rest of this course is worth your time.',
      'Write down three things you know about your chosen niche from direct experience that you could not have got from reading — a price you paid, a product that failed, a step everyone gets wrong. Then search for each one and see whether anyone has written it. What you cannot find is your actual advantage. If you could not fill all three lines, consider a different niche, one you have genuinely lived.',
      '[{"question":"What did the affiliate sites that kept growing have in common?","options":["They published more often than their competitors","First-hand experience worth reading — something a summary of other people''s reviews cannot show","They used paid advertising instead of search","They targeted less competitive countries"],"correct_index":1},{"question":"Why is local, lived knowledge an advantage in affiliate content now?","options":["Search engines rank local domains higher","It is cheaper to produce than researched content","It is first-hand by definition — prices, failures and conditions an overseas writer cannot know — which is exactly what survived the updates","Affiliate programmes pay more for local traffic"],"correct_index":2}]'::jsonb)
  on conflict (module_id, order_number) do nothing;

  -- Bring the shifted modules back, now sitting after the 1 new one(s).
  update public.modules set order_number = order_number - 1000 + 1
   where course_id = v_course_id and order_number > 1000;

end $$;

-- ============ No-Code App Building ============
-- Auto-generated by scripts/curriculum/build-level-sql.mjs -- do not
-- hand-edit the lesson content below; regenerate from the source plan
-- JSON instead if something needs to change.

do $$
declare
  v_course_id uuid := 'ba71d7b5-d813-4429-bda5-c97e9fb1fc14';
  v_level uuid;
  -- modules.order_number is unique per COURSE, not per level (a course's
  -- modules are numbered continuously across all its levels) -- so this
  -- can't just start at 1 for a level beyond the first. Computed here
  -- instead of hardcoded so this script works correctly regardless of how
  -- many modules the course already has.
  v_module_offset int;
  v_m1 uuid;
begin
  -- Appending to a level that already exists. Looked up rather than
  -- inserted, so this adds to the learner's current Level 1 instead of
  -- creating a duplicate one, and no existing module is re-parented.
  select id into v_level from public.levels
    where course_id = v_course_id and order_number = 1;

  if v_level is null then
    raise exception 'Level % not found for course % -- refusing to guess', 1, v_course_id;
  end if;

  -- The new modules must sit INSIDE this level, not at the end of the
  -- course. getOrderedLessons() builds the learner's lesson sequence from
  -- modules.order_number alone and ignores level, so a module appended at
  -- the course's max order would put beginner content after the final
  -- level's material. Insert straight after this level's last module and
  -- shift everything below it down instead.
  select coalesce(max(order_number), 0) into v_module_offset
    from public.modules where level_id = v_level;

  -- Two-phase shift: (course_id, order_number) is unique, and a single
  -- "+ N" update can trip that constraint mid-statement, so park the rows
  -- out of range first and bring them back afterwards.
  update public.modules set order_number = order_number + 1000
   where course_id = v_course_id and order_number > v_module_offset;

  insert into public.modules (course_id, level_id, title, description, order_number) values
    (v_course_id, v_level, 'What Every App Is Actually Made Of', 'Level 1 asked what no-code is and compared the tools, then Level 2 went straight to building in specific apps. The concepts underneath — that a screen is made of components, and that an app needs somewhere to keep its data — are the same in every no-code tool, and were never taught. FlutterFlow is used here as the worked example because its own channel teaches these properly; the ideas transfer to Glide, Adalo, Bubble or anything else.', v_module_offset + 1)
  returning id into v_m1;

  insert into public.lessons (module_id, title, description, youtube_url, order_number, learning_objectives, notes, practice_activity, knowledge_check) values
    (v_m1, 'Screens Are Made of Components', 'The building-block idea behind every app screen: containers, text, images and buttons arranged inside each other. From FlutterFlow''s own channel.', 'https://www.youtube.com/watch?v=2TGhJEUA0uY', 1,
      array['Describe a screen as a tree of nested components rather than a picture', 'Name the handful of component types that make up most screens', 'Recognise the same idea in a different no-code tool'],
      'The mental shift that makes no-code click: a screen is not a drawing, it is a structure. A card is a container holding an image, some text and a button. A list is one design repeated for each row of data. Once you see screens as nested boxes, every tool''s editor stops being mysterious, because they are all editing the same structure with different names for it.

FlutterFlow calls them widgets. Glide calls them components. Adalo calls them components too. Bubble calls them elements. The vocabulary differs; the idea does not. That is why this lesson sits in Level 1, before the course picks a tool.

ADDITION BEYOND THE VIDEO — why this matters for getting unstuck. Most beginner frustration in no-code is a layout that will not do what you want, and almost all of it comes from not knowing which container a thing is sitting inside. When something will not move, will not centre, or will not resize, the answer is nearly always in the structure tree, not in the settings panel you are staring at. Learn to read that tree first and you will solve your own problems instead of searching for a tutorial that matches your exact screen.

A note on this course''s tools: the Glide lessons in Level 2 use Glide''s older product, which the vendor has since moved on from. The concepts in this module are the durable part; specific button positions in any tool will drift, and that is normal.',
      'Open any app on your phone and pick one screen. On paper, draw it as nested boxes: what contains what. Mark every repeated row as one design plus data. Then open any no-code tool''s free tier and rebuild just that structure — no colours, no polish, only the boxes in the right arrangement. Getting the tree right is the skill; decoration is the easy part.',
      '[{"question":"What is the underlying idea behind every app screen?","options":["A picture that the tool converts into code","A tree of components nested inside each other — a card is a container holding an image, text and a button","A single template chosen from a gallery","A spreadsheet with formatting applied"],"correct_index":1},{"question":"Your element will not centre or resize the way you want. Where is the answer usually found?","options":["In the settings panel for that element","In the tool''s colour and theme settings","In the structure tree — which container the element is sitting inside","In the app''s export settings"],"correct_index":2}]'::jsonb),
    (v_m1, 'Where the App Keeps Its Data', 'Connecting an app to a database and showing real, saved information — built as a to-do app, the smallest example that needs everything. From FlutterFlow''s own channel.', 'https://www.youtube.com/watch?v=TFsDJAhvAKQ', 2,
      array['Explain why an app needs a database separate from its screens', 'Set up a collection and connect a screen to it', 'Tell the difference between data that is saved and data that only looks saved'],
      'This is the half of app-building that beginners skip and then cannot understand why nothing works. Screens display; the database remembers. If a to-do list loses its items when you close the app, the items were never in a database — they were only ever on screen.

A to-do app is the standard teaching example for a reason: it is the smallest thing that needs all the pieces. Something to store items, a screen that lists them, a way to add one, a way to mark it done. Every business app you will ever be asked for — a stock list, a client register, an attendance sheet, a delivery tracker — is the same shape with different words.

FlutterFlow uses Firebase and Firestore here, which is Google''s database service. Other tools bundle their own: Glide sits on a sheet, Adalo has its own collections, Bubble has a built-in database. The concepts you need are identical — collections of records, each with fields — and only the setup screens differ.

ADDITION BEYOND THE VIDEO — two things to check before you build for a paying client. First, cost: free tiers are generous for learning and can become billable when an app has real users, and a Firebase bill arrives in dollars. Read the pricing page before you promise anything. Second, where the data lives: a client storing customer names and phone numbers has obligations under Kenya''s Data Protection Act. Know what you are storing and why, do not collect what you do not need, and be able to tell the client where it is kept.',
      'Build the smallest possible data-backed app: one collection with two fields, one screen that lists the records, and one button that adds a record. Then close the app completely and reopen it. If your records are still there, you have understood this lesson. If they are gone, you built a screen, not an app — find where the save step was missed.',
      '[{"question":"Your to-do list loses its items when the app is closed. What does that tell you?","options":["The app needs more memory","The items were never saved to a database — they only ever existed on screen","The screen layout is wrong","The database is too small"],"correct_index":1},{"question":"Why is a to-do app the standard teaching example?","options":["It is the most commonly requested business app","It requires no database","It is the smallest thing that needs all the pieces — storage, a list, adding and updating — and every business app is that same shape","It can be built without any screens"],"correct_index":2}]'::jsonb)
  on conflict (module_id, order_number) do nothing;

  -- Bring the shifted modules back, now sitting after the 1 new one(s).
  update public.modules set order_number = order_number - 1000 + 1
   where course_id = v_course_id and order_number > 1000;

end $$;
