-- Level 1 deepening: SQL & Databases for Beginners. ONE course. Additive
-- only, one new module of two lessons, taking Level 1 from 1 module /
-- 2 lessons to 2 / 4.
--
-- THE GAP, and it is the largest one found in this sweep: every lesson in
-- the course after Level 1 READS data -- SELECT, WHERE, JOIN, GROUP BY,
-- and a data-exploration project. Nothing explains how tables relate to
-- each other, and nothing teaches CREATE TABLE or INSERT. A learner who
-- finishes this course cannot build a database to practise on, and can
-- only ever follow along with someone else's example.
--
-- NO NEW SOURCING WAS NEEDED. SQL was closed on 9 September as having no
-- vendor channel, which remains true -- but the course's own lesson 1
-- already points at freeCodeCamp's 4h20m SQL course, and that video
-- publishes a NAMED CHAPTER LIST. The new lessons send the learner to
-- "Tables & Keys", then "Creating Tables" and "Inserting Data".
--
-- THIS IS THE WEB DEVELOPMENT PATTERN, NOT THE DEFECT REPORTED
-- YESTERDAY. Web Development uses two JavaScript course videos nine times
-- each and it is correct, because every lesson's notes name the chapter
-- to watch. The three courses flagged on 17 September repeat a video with
-- NO notes, so a learner cannot tell the lessons apart. These two new
-- lessons carry the chapter name in bold as their first line. The
-- distinction is the notes, and it is the whole distinction.
--
-- A real benefit for this audience: the learner already opened that video
-- in lesson 1, so watching a different chapter costs no new download. The
-- notes say so, because data costs money in Kenya.
--
-- Written into the notes rather than assumed: that MySQL versus
-- PostgreSQL does not matter at this level and nobody is turned away for
-- having learned keys in MySQL; and a blunt warning that DELETE or UPDATE
-- without WHERE wipes a table instantly with no undo, so practise only on
-- a database you created yourself.
--
-- Both new lessons carry objectives, notes, a practice activity and a
-- knowledge check, so the 438-lesson bare backlog does not grow.

-- Auto-generated by scripts/curriculum/build-level-sql.mjs -- do not
-- hand-edit the lesson content below; regenerate from the source plan
-- JSON instead if something needs to change.

do $$
declare
  v_course_id uuid := '80a09415-4aac-441d-a9ac-386715c56621';
  v_level uuid;
  -- modules.order_number is unique per COURSE, not per level (a course's
  -- modules are numbered continuously across all its levels) -- so this
  -- can't just start at 1 for a level beyond the first. Computed here
  -- instead of hardcoded so this script works correctly regardless of how
  -- many modules the course already has.
  v_module_offset int;
  v_m1 uuid;
begin
  -- Appending to a level that already exists. Looked up rather than
  -- inserted, so this adds to the learner's current Level 1 instead of
  -- creating a duplicate one, and no existing module is re-parented.
  select id into v_level from public.levels
    where course_id = v_course_id and order_number = 1;

  if v_level is null then
    raise exception 'Level % not found for course % -- refusing to guess', 1, v_course_id;
  end if;

  -- The new modules must sit INSIDE this level, not at the end of the
  -- course. getOrderedLessons() builds the learner's lesson sequence from
  -- modules.order_number alone and ignores level, so a module appended at
  -- the course's max order would put beginner content after the final
  -- level's material. Insert straight after this level's last module and
  -- shift everything below it down instead.
  select coalesce(max(order_number), 0) into v_module_offset
    from public.modules where level_id = v_level;

  -- Two-phase shift: (course_id, order_number) is unique, and a single
  -- "+ N" update can trip that constraint mid-statement, so park the rows
  -- out of range first and bring them back afterwards.
  update public.modules set order_number = order_number + 1000
   where course_id = v_course_id and order_number > v_module_offset;

  insert into public.modules (course_id, level_id, title, description, order_number) values
    (v_course_id, v_level, 'How Data Is Actually Stored', 'Every lesson in this course after Level 1 reads data — SELECT, WHERE, JOIN, GROUP BY. None of them explain how the data got there or how tables relate to each other, and a learner who can only read cannot build a database to practise on. This module fixes both, using named chapters of the same freeCodeCamp course you already opened in lesson 1.', v_module_offset + 1)
  returning id into v_m1;

  insert into public.lessons (module_id, title, description, youtube_url, order_number, learning_objectives, notes, practice_activity, knowledge_check) values
    (v_m1, 'Tables, Keys and How Data Relates', 'What a table actually is, and how primary and foreign keys connect one table to another — the idea that makes JOINs make sense later.', 'https://www.youtube.com/watch?v=HXV3zeQKqGY', 1,
      array['Describe a table in terms of rows, columns and data types', 'Explain what a primary key is and why every table needs one', 'Explain how a foreign key links one table to another'],
      'WATCH THE **"Tables & Keys"** CHAPTER of this course — navigate by the chapter name in the video''s description, not by a timestamp someone quoted. This is the same 4-hour freeCodeCamp course you opened in lesson 1, so it should already be in your history; you are watching a different twenty minutes of it, not downloading it again. That matters when data costs money.

The idea to hold onto: a table is one kind of thing — one table for customers, one for orders, never both mixed together. A PRIMARY KEY is the column that makes each row uniquely identifiable, so that "customer 4051" always means exactly one person. A FOREIGN KEY is a column in one table that holds another table''s primary key, and that is the entire mechanism by which an order knows which customer it belongs to.

This is why the JOIN lesson in Level 2 works. A JOIN is not magic — it follows a foreign key back to the primary key it points at. Learners who find JOINs confusing almost always never learned keys, and the fix is this chapter rather than more JOIN practice.

ADDITION BEYOND THE VIDEO — the course uses MySQL, and so does most of the job market''s entry-level SQL work. The concepts here are identical in PostgreSQL, SQL Server, SQLite and the Postgres database behind Supabase; only some function names and installation steps differ. Do not worry that you picked the wrong one. Nobody who can explain keys is turned away for having learned them in MySQL.',
      'On paper, design two tables for a small business you know — say a shop''s customers and its orders. Write out the column names and mark the primary key in each. Then draw the arrow: which column in the orders table points at which column in the customers table? Finally, write one sentence explaining what would go wrong if the orders table just stored the customer''s name as text instead.',
      '[{"question":"What is a primary key for?","options":["It sorts the table automatically","It makes each row uniquely identifiable, so a given id always means exactly one record","It encrypts the row","It limits how many rows a table can hold"],"correct_index":1},{"question":"Why do learners who find JOINs confusing usually need this chapter rather than more JOIN practice?","options":["JOINs require a faster computer","JOIN syntax differs between databases","A JOIN follows a foreign key back to the primary key it points at, so without keys the operation has no meaning","JOINs only work on tables created in the same session"],"correct_index":2}]'::jsonb),
    (v_m1, 'Making Your Own Database to Practise On', 'Creating tables and putting rows into them — so you have data of your own to query instead of only reading someone else''s examples.', 'https://www.youtube.com/watch?v=HXV3zeQKqGY', 2,
      array['Create a table with appropriate columns and data types', 'Insert rows into a table you made', 'Explain why practising on your own data beats following along with a sample database'],
      'WATCH TWO CHAPTERS, in order: **"Creating Tables"**, then **"Inserting Data"**. Same video as the previous lesson — again, navigate by chapter name.

This is the single biggest hole in this course as it stands. Everything else here reads data that already exists. If you cannot create a table and put rows in it, you can only ever follow along with somebody else''s example database, and following along is not the same as knowing how.

CREATE TABLE names the columns and says what kind of data each one holds — text, number, date. INSERT puts rows in. That is genuinely all you need to make a practice database, and once you have one, every other lesson in this course becomes something you can try on data you understand rather than a demo you watch.

ADDITION BEYOND THE VIDEO — what to build first, and a warning. Build the two tables you designed on paper in the previous lesson, with about ten rows each, using real-ish data from something you know: a shop, a chama''s contributions, a class register. Ten rows is enough to see a JOIN work and small enough to check by eye whether the answer is right — which is the actual skill, because SQL will happily return a confidently wrong answer to a badly written query.

The warning: practise on a database you created, never on a live one belonging to anyone else. DELETE and UPDATE without a WHERE clause will remove or overwrite every row in the table, instantly, with no undo. That mistake has ended jobs. Level 2 covers WHERE; until you are fluent with it, keep your experiments in your own practice database.',
      'Create the two tables you designed on paper and insert about ten rows into each, using data you actually recognise. Then run a SELECT on each table and check the output against what you typed. Finally, deliberately break something small — insert a row whose foreign key points at a customer that does not exist — and see what the database does about it. What it refuses to do is as informative as what it allows.',
      '[{"question":"Why is being able to CREATE and INSERT the biggest gap in a read-only SQL course?","options":["Employers test CREATE TABLE more often than SELECT","Without it you can only follow along with someone else''s example database, and following along is not the same as knowing how","SELECT does not work on tables you did not create","It is required before you can install MySQL"],"correct_index":1},{"question":"Why practise only on a database you created yourself?","options":["Live databases run too slowly for practice","Sample databases contain errors","DELETE or UPDATE without a WHERE clause wipes or overwrites every row instantly, with no undo","Your own database returns results faster"],"correct_index":2}]'::jsonb)
  on conflict (module_id, order_number) do nothing;

  -- Bring the shifted modules back, now sitting after the 1 new one(s).
  update public.modules set order_number = order_number - 1000 + 1
   where course_id = v_course_id and order_number > 1000;

end $$;
