-- Auto-generated by scripts/curriculum/build-backfill-sql.py -- do not
-- hand-edit; regenerate from the source plan JSON instead.
--
-- UPDATE only, addressed by lesson id. No lesson is inserted, deleted or
-- re-parented and no id changes, so lesson_progress is untouched.

-- How To Price YOUR Work
update public.lessons set
  learning_objectives = array['Explain why an hourly rate punishes you for getting faster', 'Price a job from the value of the outcome rather than the hours', 'Set a floor below which you will not take work'],
  notes = 'The central argument is that charging by the hour ties your income to your slowness. Get twice as fast and you earn half as much for the same result — which is a strange thing to build a career on. Pricing on the value of the outcome breaks that link: a logo that a business will use for ten years is not worth less because you made it in a day.

In practice, most beginners are not ready to quote a high value price and should not pretend to be. What you can do immediately is price per PROJECT rather than per hour, so that speed benefits you, and revise the number upward each time a job proves easy.

ADDITION BEYOND THE VIDEO — working out your floor, which the video does not do for you. Add up what you must earn in a month: rent, food, transport, data, airtime, any contribution to family. Divide by the number of billable days you can realistically work — not thirty, more like twelve to fifteen once you account for finding work, revisions and life. That figure is your day floor, and no job below it is worth taking, because taking it costs you the time to find one that pays.

On quoting in dollars: a foreign client paying USD is usually the better-paid work, but remember the conversion and the transfer fee are yours to absorb, and the shilling moves. Quote a round USD figure and check what it actually lands as after Wise or Payoneer takes its cut.

Finally, raise your prices by telling new clients a new number, not by negotiating with old ones. That is the easiest price rise there is.',
  practice_activity = 'Work out your monthly must-earn figure and divide it by twelve billable days. Write that day floor down. Then take the last three jobs you did or were offered, work out what you effectively earned per day on each, and mark which ones were below the floor. Finally, re-quote one of them as a single project price you would be content with.',
  knowledge_check = '[{"question": "What is the structural problem with charging by the hour?", "options": ["Clients dislike hourly billing", "It ties your income to your slowness — getting faster earns you less for the same result", "Hourly rates are hard to calculate", "It is not allowed on most platforms"], "correct_index": 1}, {"question": "Why divide your monthly needs by about twelve days rather than thirty?", "options": ["Most clients only pay for twelve days a month", "It produces a rounder number", "Because finding work, revisions and life consume the rest — thirty billable days is not realistic", "Tax is calculated on twelve days"], "correct_index": 2}]'::jsonb
where id = 'bb7dbc81-3409-41e2-a6ef-99545b539d2f';

-- How to Qualify Design Clients & Position Your Work
update public.lessons set
  learning_objectives = array['Ask the three questions that reveal whether a prospect is worth pursuing', 'Recognise the warning signs of a client who will cost you money', 'Decline work without damaging the relationship or your reputation'],
  notes = 'Qualifying is the habit of finding out whether a job is worth having BEFORE you write a proposal. Most freelancers skip it, write proposals for everyone, and lose days to people who were never going to buy.

Three questions do most of the work. What are you trying to achieve? What have you budgeted? When does this need to be finished? An answer of "I don''t know" to the budget question is not disqualifying on its own, but a refusal to discuss it at all usually is.

The warning signs are consistent: a prospect who will not name any budget, who wants a price before describing the work, who mentions that the last three people they hired disappointed them, or who needs it urgently and cannot say why. None of these are certainties. Two together is a pattern.

ADDITION BEYOND THE VIDEO — how to say no, kindly and without burning it. "This is not quite the sort of work I do best — I''d rather point you to someone who will serve you better than take it on and do an average job." That sentence protects your reputation, and referring the job to someone else earns you goodwill you will be repaid for.

One warning specific to this market. Requests to start work before any deposit, paired with promises of much bigger work later, are the most common pattern in non-payment here. So is a client who wants to move the conversation off a platform to avoid its protections. You are allowed to say: "Happy to start once the deposit is through." Nobody serious is offended by that.',
  practice_activity = 'Write your three qualifying questions in the exact words you would send them, and save them where you can paste them. Then think of a past client who cost you more than they paid: list the signs that were visible before you started. That list is your personal warning set — most people''s is the same three or four things each time.',
  knowledge_check = '[{"question": "What is the point of qualifying a prospect?", "options": ["To make them feel they are being assessed", "To find out whether the job is worth having before you spend time writing a proposal", "To justify a higher price", "To collect information for your portfolio"], "correct_index": 1}, {"question": "A prospect wants you to begin before any deposit and mentions much bigger work later. What is that?", "options": ["A normal opening position worth accepting once", "A sign of a well-funded client", "The most common pattern behind non-payment — say you will start once the deposit is through", "A reason to raise your price"], "correct_index": 2}]'::jsonb
where id = '84cacf8b-8963-4e8a-8c82-88c35802b449';

-- New Client Onboarding Process Steps for Freelancers
update public.lessons set
  learning_objectives = array['Set out what happens next immediately after a client says yes', 'Collect everything you need before starting rather than during', 'Make the first week feel organised enough to justify your price'],
  notes = 'The gap between "yes" and starting work is where a surprising number of projects go wrong. The client is excited, then hears nothing for four days, then starts wondering. Onboarding is just the act of filling that gap deliberately.

The minimum version, which takes twenty minutes to set up once and then works forever: a message confirming what was agreed and the price, a request for the deposit, a short list of everything you need from them (logos, text, access, photos, who approves), and the dates. Send it the same day they agree.

The list matters more than it looks. Waiting on a client for materials is the single largest cause of projects running late, and if you ask for everything up front, the delay is visibly theirs rather than ambiguously yours.

ADDITION BEYOND THE VIDEO — decide where the work will happen, and say so. If a client can reach you on WhatsApp at any hour, they will, and you will end up managing the project across four hundred messages with no record of what was agreed. Pick one channel for decisions — email, or a shared document — and say: "WhatsApp is fine for quick questions, but I will confirm anything we decide by email so we both have it." That single sentence prevents most later disputes, and it reads as professionalism rather than distance.

Also agree who approves. A project with two people giving contradictory feedback and no named decision-maker is a project that will need three extra revision rounds.',
  practice_activity = 'Write your onboarding message as a reusable template with five parts: what we agreed, the price and deposit, what I need from you (a numbered list), the dates, and how we will communicate. Then send it to yourself and read it as a client would. Does it make you feel the project is in competent hands?',
  knowledge_check = '[{"question": "Why ask for everything you need from the client up front?", "options": ["It reduces the total amount of work", "Waiting on client materials is the largest cause of late projects, and asking up front makes any delay visibly theirs", "Clients respect longer requests", "It allows you to charge more"], "correct_index": 1}, {"question": "Why name one channel for decisions even if WhatsApp stays open for questions?", "options": ["WhatsApp is unprofessional", "It limits how often the client can contact you", "Decisions scattered across hundreds of messages leave no record of what was agreed, which is where disputes come from", "Email is required for invoicing"], "correct_index": 2}]'::jsonb
where id = 'febe7c4d-8dab-490a-b33b-891ed81da0be';

-- How to Best Handle Feedback and Revisions From Clients
update public.lessons set
  learning_objectives = array['Turn vague feedback into a specific, actionable change', 'Keep revision rounds inside what was agreed', 'Disagree with a client''s instruction without being difficult about it'],
  notes = 'Most difficult feedback is not hostile, it is vague. "I don''t love it" and "can it pop more" are not instructions, and guessing at them is how three revision rounds become seven.

The move is to convert feedback into a decision before you touch the work. "When you say it should pop more — do you mean brighter colours, a larger logo, or more contrast between the text and the background?" Offering two or three concrete options is far more effective than asking an open question, because clients often cannot name what they want but can recognise it immediately.

Collect feedback in one batch per round rather than acting on each message as it arrives. Otherwise you do the same piece of work four times.

ADDITION BEYOND THE VIDEO — when the client is wrong. Sometimes an instruction will genuinely make the work worse, and the professional response is neither silent compliance nor an argument. Say what you would recommend and why, in one or two sentences, and then do what they decide: "I''d keep the text at this size — smaller than this is hard to read on a phone, and most of your customers will see it on a phone. Happy to reduce it if you prefer." You have discharged your duty as the expert; the decision is theirs, and they will remember that you flagged it if it turns out badly.

And note when a round is finished. "That''s round two of the two included — let me know if you''d like a third at KSh X." Said cheerfully at the right moment, this is never a problem. Said for the first time at round six, it is a fight.',
  practice_activity = 'Take three pieces of vague feedback you have received or can imagine — "make it pop", "it feels off", "more professional" — and for each write the clarifying question with two or three concrete options. Then write your one-sentence version of the recommend-then-defer response for a case where you think the client is wrong.',
  knowledge_check = '[{"question": "What is the best response to vague feedback like \"make it pop more\"?", "options": ["Make your best guess and present it", "Ask a clarifying question offering two or three concrete options, since clients often cannot name what they want but recognise it", "Ask them to write a detailed brief", "Explain why the current version is correct"], "correct_index": 1}, {"question": "How should you handle an instruction you believe makes the work worse?", "options": ["Comply silently to keep the relationship", "Refuse on professional grounds", "State your recommendation and the reason in a sentence or two, then do what they decide", "Charge extra for the change"], "correct_index": 2}]'::jsonb
where id = '291293da-95a1-4b52-b98e-fe6cb2f77048';

-- How to Build a Freelance Portfolio (That Gets You Hired)
update public.lessons set
  learning_objectives = array['Choose portfolio pieces by the work you want next, not by chronology', 'Present a piece as a problem and a result rather than a picture', 'Build a credible portfolio before you have paying clients'],
  notes = 'A portfolio is an argument, not an archive. Every piece should be answering the question "can this person solve my problem", and pieces that do not serve that argument weaken it — including good work in a field you no longer want.

The presentation that converts is a short story per piece: what the client needed, what you did, what changed as a result. Two or three sentences. A grid of images with no context asks the viewer to work out why they should be impressed, and most will not bother.

Six strong pieces beat twenty mixed ones. Choose them by the work you want to be hired for next.

ADDITION BEYOND THE VIDEO — the beginner''s problem, which the video assumes away. With no paying clients, invent the brief. Redesign a real local business''s menu, poster or website — a matatu sacco, a salon, a hardware shop — and present it as a self-directed project, labelled honestly as such. Nobody minds. What they are assessing is whether you can think and finish, and a clearly labelled speculative piece proves both. Do not pass it off as commissioned work; that unravels the moment anyone asks.

Where to put it: a free Behance or Dribbble page, a well-organised Google Drive folder, or a single PDF you can send on WhatsApp all work. A learner here does not need to buy a domain to start, and the PDF is often the most practical thing, because it opens on a phone without data-heavy page loads.',
  practice_activity = 'Pick the kind of work you want more of. Choose or create three pieces that argue you can do it, and write each up in three sentences: the need, what you did, the result. Then assemble them into one PDF under five megabytes and send it to a friend on WhatsApp to check it opens and reads well on a phone.',
  knowledge_check = '[{"question": "Why leave out good work from a field you no longer want?", "options": ["Old work looks dated", "A portfolio is an argument that you can solve a particular problem, and unrelated pieces weaken it", "Clients only look at the first item", "It reduces the file size"], "correct_index": 1}, {"question": "How should a beginner with no clients build a portfolio?", "options": ["Wait until paid work arrives", "Present speculative work as though it were commissioned", "Invent the brief — redesign a real local business''s materials and label it honestly as a self-directed project", "Copy existing work from other designers"], "correct_index": 2}]'::jsonb
where id = 'd6754cad-9fe7-488d-9977-e3d18669386b';

-- How to Get Freelance Clients from Referrals (Without Pitching)
update public.lessons set
  learning_objectives = array['Ask for a referral at the moment a client is most willing to give one', 'Make a referral easy by naming exactly who you want to meet', 'Keep past clients in touch without pestering them'],
  notes = 'Referrals are the cheapest work you will ever get, and most freelancers never ask for them — or ask so vaguely that nothing happens. "Let me know if you hear of anyone" produces nothing, because you have given the person a research task.

Two things make it work. TIMING: ask immediately after you deliver something they are pleased with, not months later. SPECIFICITY: name the kind of person you want. "Do you know one other restaurant owner who has the same menu problem you had?" is answerable. "Anyone who needs design" is not.

Ask for two things at that same moment: the referral and a written line you can quote. You are at the peak of their goodwill, and both are free to give.

ADDITION BEYOND THE VIDEO — the follow-up that quietly produces most repeat work. Message every past client once every three or four months, with something useful rather than a request: notice something about their business, send a small thought, ask how the thing you built is performing. No pitch. A third of freelance income in a mature practice is repeat work from people who simply remembered you existed, and the only way to be remembered is to be occasionally present.

Keep the list somewhere: names, what you did, when you last spoke. Fifteen past clients contacted three times a year is forty-five touches — far more productive than the same hours spent on cold outreach, and far less unpleasant.',
  practice_activity = 'Write your referral ask in one sentence, naming a specific kind of person rather than ''anyone''. Then list every client you have ever had, however small, with the date you last spoke to them. Message the three you have neglected longest — with something useful, not a request.',
  knowledge_check = '[{"question": "Why does \"let me know if you hear of anyone\" fail?", "options": ["It is too informal", "It hands the person a research task instead of an answerable question", "It should be sent in writing", "Clients are not allowed to refer freelancers"], "correct_index": 1}, {"question": "What should the periodic message to a past client contain?", "options": ["A reminder of your current rates", "A request for referrals", "Something useful and no pitch — the point is being remembered, which is where repeat work comes from", "A summary of your recent projects"], "correct_index": 2}]'::jsonb
where id = '6997b8d9-b11b-42be-92f6-57d42db72016';
