-- Auto-generated by scripts/curriculum/build-backfill-sql.py -- do not
-- hand-edit; regenerate from the source plan JSON instead.
--
-- UPDATE only, addressed by lesson id. No lesson is inserted, deleted or
-- re-parented and no id changes, so lesson_progress is untouched.

-- Before You Edit Another Video… Watch This
update public.lessons set
  learning_objectives = array['Decide what a video is for before opening the editor', 'Hold attention through the opening seconds rather than the whole runtime', 'Cut to a length the material earns'],
  notes = 'The habits that separate an editor people hire from one who is technically competent are decided before the first cut.

KNOW WHAT THE VIDEO IS FOR. Every video does one job: sell something, explain something, record something, entertain. If you cannot say which, the edit will drift and the client will keep asking for changes they cannot articulate — because the problem is not the cut, it is that nobody decided what the video was for.

THE FIRST FEW SECONDS DECIDE THE REST. Most viewers who leave, leave at the start. So do not open with a logo animation, a slow fade, or throat-clearing. Open with the most interesting thing you have. If someone says something striking two minutes in, that line may belong at the top.

LENGTH IS EARNED, NOT CHOSEN. A three-minute video with two minutes of material is worse than a two-minute video. Nobody has ever complained that something good was too short.

WATCH IT AS A VIEWER. Export it, leave it overnight, watch it once through without touching anything. You will see it. Editors who skip this step deliver work that only makes sense to the person who made it.

ADDITION BEYOND THE VIDEO — two things that matter commercially more than craft. First, MUSIC RIGHTS: using a popular song will get a client''s video muted or taken down, and that is your fault, not theirs. Use properly licensed or free-to-use music, and keep a note of where each track came from. Second, SUBTITLES: a large share of social video is watched with the sound off, and in a multilingual market subtitles also carry viewers who follow the written word more comfortably than the spoken one. Adding them is close to free and it visibly increases how far people watch.',
  practice_activity = 'Take a video you have finished and answer three questions in writing: what is this for, what is the single most interesting moment in it, and does its length match its material? Then re-cut it — put the best moment near the top, and remove a third of the runtime. Watch both versions a day later and decide honestly which you would rather show a client.',
  knowledge_check = '[{"question": "Where do most viewers who leave a video leave?", "options": ["At the start — which is why the opening seconds decide the rest", "At the halfway point", "At the end credits", "Evenly across the runtime"], "correct_index": 0}, {"question": "Why does using a popular song in a client''s video matter?", "options": ["It can get the video muted or taken down, and that is the editor''s responsibility", "It increases the file size", "It slows down the export", "It reduces the audio quality"], "correct_index": 0}]'::jsonb
where id = '7af94a89-b4d0-40a8-a49c-3279a2fbb02c';

-- How to Edit YouTube Videos in 2026
update public.lessons set
  learning_objectives = array['Edit for retention rather than for polish', 'Apply pacing that suits a talking-head video', 'Recognise which YouTube conventions are craft and which are fashion'],
  notes = 'YouTube editing is its own discipline, and the reason is retention: the platform measures how long people keep watching, so the edit is judged on whether the viewer stays rather than on whether it looks tidy.

What that produces in practice:

CUT THE DEAD AIR. Every pause, every ''um'', every restart. A talking-head video with the gaps removed feels twice as alive and is usually a third shorter.

CHANGE SOMETHING REGULARLY. A cut, a zoom, a graphic, a cutaway to what is being described. Not for decoration — a static frame for ninety seconds is when people leave.

B-ROLL EARNS ITS PLACE. Show what is being talked about. It holds attention and it hides the joins in your cuts.

TEXT ON SCREEN for key points and numbers, because many viewers are half-listening.

DELIVER THE PROMISE EARLY. If the title asks a question, do not save the answer for the end. Answer it, then explain it. Withholding it does not keep people; it loses them.

ADDITION BEYOND THE VIDEO — separate the craft from the fashion, because you will be asked for both. The craft is permanent: pace, clarity, the promise kept, dead air removed. The fashion is whatever look is current — a particular caption style, a zoom, a sound effect everyone is using this year. Fashion dates fast and dates a client''s back catalogue with it. Deliver the current style when that is what the client wants, but build on the craft, because it is what still works in five years.

A note on the local reality: heavy, fast-cut editing on long videos costs the viewer data. For an audience on bundles, a tight ten-minute video beats a padded twenty-minute one for reasons that have nothing to do with the algorithm.',
  practice_activity = 'Take five minutes of someone talking to camera — your own footage is fine — and cut it to under three minutes by removing dead air alone, changing nothing else. Then pass through again and make sure something changes on screen at least every ten seconds. Compare the first and last versions and note where you would have stopped watching.',
  knowledge_check = '[{"question": "What is a YouTube edit primarily judged on?", "options": ["Retention — whether the viewer keeps watching", "Visual polish", "The number of effects used", "How closely it matches current trends"], "correct_index": 0}, {"question": "The title asks a question. When should the video answer it?", "options": ["Early — then explain it; withholding it loses viewers rather than keeping them", "At the very end, to hold attention", "Halfway through", "It should not be answered directly"], "correct_index": 0}]'::jsonb
where id = '9af3b5b4-5fa8-46ca-8bf0-1e9a06a2f20f';

-- My Documentary Editing Workflow: A Step-by-Step Guide
update public.lessons set
  learning_objectives = array['Work through a large amount of footage without drowning in it', 'Build a structure from what people actually said', 'Move from a rough assembly to a finished cut in deliberate passes'],
  notes = 'Everything so far has assumed a short video. This lesson is about the job that pays more and frightens beginners: hours of footage, no script, and a story that has to be found rather than followed.

The workflow that makes it possible:

1. WATCH AND LOG. Go through everything once and note what is on each clip and roughly where. Tedious, unavoidable, and the step that decides whether the next week is calm or frantic. Mark anything that makes you sit up.

2. PULL SELECTS. Gather every good moment into one place, without ordering them yet. You are separating the usable from the rest.

3. BUILD A PAPER EDIT. Where there are interviews, transcribe them and arrange the story as TEXT first — quotes in order, on paper or in a document. Rearranging paragraphs is minutes of work; rearranging a timeline is hours. Professionals structure documentaries this way, and skipping it is why beginners spend a fortnight pushing clips around.

4. ASSEMBLE ROUGH. Build the paper edit into a timeline, long and untidy. Do not polish anything.

5. REFINE IN PASSES. One pass for structure. One for pacing. One for b-roll. One for audio. One for colour. Each pass does one job across the whole piece, which is far faster and more consistent than perfecting scene by scene.

ADDITION BEYOND THE VIDEO — the passes matter most on a long project because they are where you can stop. Work that is perfect in the first five minutes and unassembled after that cannot be shown to anyone. Work that is roughly complete end to end can be shown, discussed and improved. Always keep the whole thing at the same level of finish. And back up before each pass: on a project this size, losing a day is a real cost.',
  practice_activity = 'Take at least twenty minutes of raw footage — an event, a long interview, anything — and produce a three-minute cut using the five steps in order. Do the paper edit in writing before you touch the timeline, and do not skip it. Note how long each step takes; the logging will feel wasteful and will save you more time than it costs.',
  knowledge_check = '[{"question": "What is a paper edit and why does it come first?", "options": ["Arranging the story as text before touching the timeline — rearranging paragraphs takes minutes, rearranging a timeline takes hours", "A printed list of every clip", "A written contract with the client", "Notes taken while filming"], "correct_index": 0}, {"question": "Why refine in passes across the whole piece?", "options": ["The project stays at one level of finish, so it can always be shown and discussed", "It uses less disk space", "It avoids the need for backups", "Each pass exports faster"], "correct_index": 0}]'::jsonb
where id = '830eec08-5e82-4b82-81a8-be734a0c5b21';

-- POV: Editing a Real Paid Client Project (Full Process)
update public.lessons set
  learning_objectives = array['Run a client edit as a process with defined stages, not one long effort', 'Collect what you need from a client before starting', 'Handle revisions without the job expanding indefinitely'],
  notes = 'A paid edit is a different job from a personal one, and the difference is almost entirely in what happens around the editing.

BEFORE YOU START, get in writing: what the video is for, where it will be shown and in what shape, how long it should be, the deadline, who approves it, and whether they have a preferred style or an example they like. The last two questions prevent most disputes. So does knowing WHO APPROVES — an edit signed off by the marketing assistant and then reviewed by the owner is two jobs.

GET THE MATERIAL UP FRONT. All the footage, the logo, the music if they have rights to specific tracks, the exact spelling of every name and title. Chasing a missing logo on delivery day is entirely avoidable and entirely your problem once you have accepted the deadline.

SEND A ROUGH CUT EARLY. Not a polished one. The point is to agree the structure before you spend hours refining something they were always going to want restructured. Beginners hide their work until it is perfect and then discover the client wanted a different video.

REVISIONS: state the number before you start. Two rounds is normal. Collect all notes for a round together rather than acting on messages as they arrive — piecemeal changes are how a two-day job becomes a two-week one.

DELIVER PROPERLY: the agreed format and shape, sensibly sized, through a link rather than a compressed chat upload, with the file named for the client rather than for your folder.

ADDITION BEYOND THE VIDEO — the money. Take a deposit, commonly half, before you start; it is standard and nobody serious objects. Keep the raw footage for a stated period and say what that period is. And never hand over the final full-quality file before final payment — a watermarked or lower-resolution preview for approval is normal practice and not an insult. Being paid is part of the craft.',
  practice_activity = 'Write your client brief as a form you can reuse: purpose, platform and shape, length, deadline, who approves, style reference, and what material you need from them. Then write your delivery checklist: format, size, naming, how it is sent, what happens to the raw footage. Use both on your next job, even an unpaid one for practice.',
  knowledge_check = '[{"question": "Why send a rough cut early rather than a polished one?", "options": ["To agree the structure before spending hours refining something they may want restructured", "To show you are working quickly", "Because clients cannot judge finished work", "To reduce the file size"], "correct_index": 0}, {"question": "What is normal practice before final payment?", "options": ["Send a watermarked or lower-resolution preview for approval, not the final full-quality file", "Send the full file and trust the client", "Refuse to show anything", "Deliver only after a month"], "correct_index": 0}]'::jsonb
where id = 'e007af04-46b1-44ba-8027-7751e0c2b872';

-- How To Get Your First Video Editing Clients Online
update public.lessons set
  learning_objectives = array['Build a portfolio before anyone has hired you', 'Find the clients who are nearest rather than the ones who are loudest', 'Approach a business with a specific observation rather than a general offer'],
  notes = 'The first client problem is circular: they want to see work, and you have no work because nobody has hired you. It is broken by making the work anyway.

BUILD THE PORTFOLIO FIRST. Re-edit something that already exists. Take a business''s own poor video and cut a better version. Film and edit something small locally — a market, a workshop, a friend''s business. Three genuinely good short pieces beat a reel of effects. Nobody asks whether you were paid for them.

WHERE THE WORK ACTUALLY IS, close to you: churches and schools recording events; saccos and chamas; small businesses trying and failing at TikTok and Reels; photographers who are asked for video and do not edit; event organisers; people already producing content with no time to cut it. Almost none of them are on a freelance platform, and all of them can be reached directly.

APPROACH WITH SOMETHING SPECIFIC. Not ''I am a video editor, do you need one?'' — which invites ''no''. Instead: ''I saw your event video. I re-cut the first thirty seconds so it opens on the moment people react. Here it is.'' You have shown the skill, done the work, and made the value obvious in one message. Three of these beat a hundred generic applications.

ADDITION BEYOND THE VIDEO — the ongoing work is what to aim for. A single wedding is one payment; a business that needs four social videos every month is income. When you deliver well, ask directly whether they need this regularly, and quote for the month. And ask for the referral on the day they are pleased — video work travels almost entirely by word of mouth, and one satisfied church or school will introduce you to several more.',
  practice_activity = 'Pick one local business or organisation whose video you have actually seen and could improve. Re-cut thirty seconds of it properly and send it to them with one sentence about what you changed and why. Do this for three different places this week. Meanwhile, finish three portfolio pieces so that when someone says yes, you have something to show.',
  knowledge_check = '[{"question": "How do you build a portfolio before anyone has hired you?", "options": ["Make the work anyway — re-cut existing videos and film small local pieces", "Wait for a first paid job", "Buy templates and show those", "Copy other editors'' reels"], "correct_index": 0}, {"question": "What makes an approach effective?", "options": ["A specific improvement you have already made to something of theirs", "A general offer of your services", "A list of the software you use", "The lowest price available"], "correct_index": 0}]'::jsonb
where id = 'ce72868d-3534-45a3-8af1-30a2dba569af';

-- How Much to Charge for Video Editing: Every Pricing Strategy
update public.lessons set
  learning_objectives = array['Choose between per-project, per-minute and monthly pricing for a given job', 'Count the work that is invisible to the client when quoting', 'Raise a rate without losing the client'],
  notes = 'Most beginners undercharge, and the reason is that they price the time on the timeline and not the job.

THE MODELS, and where each fits:

PER PROJECT — one price for a defined deliverable. Best for most work. It requires you to define the deliverable precisely, which is a discipline worth having anyway.

PER FINISHED MINUTE — common for talking-head and long-form work. Simple to quote, but it punishes you when the client sends four hours of footage for a three-minute video, so state the maximum raw footage included.

MONTHLY RETAINER — an agreed number of videos every month for a set fee. This is the goal. It is predictable income, the client stops re-negotiating, and each month gets faster as you learn their style.

HOURLY — avoid. As you get faster you earn less, which is exactly backwards.

WHAT BEGINNERS FORGET TO COUNT: watching and logging footage, transferring and backing up files, exporting and re-exporting, revisions, the back-and-forth with the client, and the hours of failed attempts before the version that worked. The visible edit is a fraction of the job.

SETTING A NUMBER HONESTLY. Work out what you need to earn in a month and how many projects you can actually deliver in one — not in theory, in practice, alongside everything else in your life. Divide. That is your floor. Then check it against what local work pays; do not price against foreign rates you are not competing for, and do not price at the bottom of the market either, because the cheapest editor attracts the most difficult clients.

ADDITION BEYOND THE VIDEO — raise your rate with new clients first, never by surprising an existing one. When you do raise an existing client, give notice, do it when you have just delivered well, and name the new rate plainly without apologising or over-explaining. Most reasonable clients accept it. The ones who leave over a modest increase were the ones costing you the most.',
  practice_activity = 'Price one real job three ways — per project, per finished minute, and as a monthly retainer — and include every invisible hour: logging, transfers, exports, revisions, client messages. Then calculate your floor from what you need per month divided by what you can genuinely deliver. Write that number down and do not quote below it.',
  knowledge_check = '[{"question": "Why is hourly pricing the worst model for an editor?", "options": ["As you get faster you earn less, which is backwards", "Clients refuse to pay hourly", "It is hard to measure", "It excludes revisions"], "correct_index": 0}, {"question": "When should you raise the rate of an existing client?", "options": ["With notice, just after delivering well, stating the new rate plainly", "By surprise on the next invoice", "Never — only new clients pay more", "Immediately after a complaint"], "correct_index": 0}]'::jsonb
where id = 'eb9ec5a7-ce10-44a3-a852-58b77ea4d8f3';
