-- Auto-generated by scripts/curriculum/build-backfill-sql.py -- do not
-- hand-edit; regenerate from the source plan JSON instead.
--
-- UPDATE only, addressed by lesson id. No lesson is inserted, deleted or
-- re-parented and no id changes, so lesson_progress is untouched.

-- Google Analytics Tutorial For Beginners
update public.lessons set
  learning_objectives = array['Find out where visitors came from and what they did', 'Define a conversion so the numbers mean something', 'Avoid the misreadings that lead to bad decisions'],
  notes = 'Analytics answers three questions: who came, where from, and what did they do. Everything else is refinement, and platform versions change constantly, so learn the questions rather than the menus.

DEFINE A CONVERSION FIRST. Before any report is worth reading, decide what a success is: a form submitted, a WhatsApp button tapped, a call started, a purchase. Without that, you are looking at traffic, and traffic is not a result. This is the step beginners skip and it makes every subsequent number meaningless.

WHERE THEY CAME FROM is the report that changes decisions. It tells you which channel actually produced enquiries rather than visits, which is how you decide where next month''s money goes. Use tagged links on every campaign so a visit can be traced back to the advert that caused it — untagged traffic lands in a heap labelled ''direct'' and teaches you nothing.

WHAT THEY DID: which pages, how long, where they left. A page where most people leave immediately is either the wrong promise or too slow.

THE MISREADINGS THAT MATTER:
- Judging tiny numbers. Twenty visits tells you nothing; wait for enough to be real.
- Treating a high bounce as failure. Someone who found the phone number and called got exactly what they came for.
- Comparing unlike periods. A school-holiday week against a term week is not a comparison.
- Forgetting your own visits are in the data, and so are the client''s.

ADDITION BEYOND THE VIDEO — the honest limit here: much of what matters never appears in analytics. WhatsApp conversations, walk-ins, phone calls and word of mouth are invisible, and for most small businesses they are the actual result. So measure off-platform too — ask how people heard about the business, count enquiries by hand, use a distinct phone number or a tracked link per campaign. A marketer who reports only what the dashboard shows is reporting a fraction of their own work, and usually the less impressive fraction.',
  practice_activity = 'For one site you can access, define what a conversion is before looking at anything else, and set it up if you can. Then answer three questions from the data: which channel brought the most conversions, which page loses the most people, and how long the average visit lasts. Finally list the results this business gets that analytics cannot see, and design one way to count each by hand.',
  knowledge_check = '[{"question": "What must be defined before analytics reports mean anything?", "options": ["What counts as a conversion for this business", "The reporting period", "The audience demographics", "The advertising budget"], "correct_index": 0}, {"question": "Why is a high bounce rate not necessarily a failure?", "options": ["Someone who found the phone number and called got exactly what they came for", "Bounce rate is measured inaccurately", "It only counts returning visitors", "Bounces are excluded from conversions"], "correct_index": 0}]'::jsonb
where id = '437e2210-61eb-4dee-ae9d-b4494efeb9c2';

-- 10-Minute SEO for Beginners
update public.lessons set
  learning_objectives = array['Apply the on-page basics to a real page', 'Write titles and descriptions that earn the click', 'Prioritise the small number of fixes that actually move a page'],
  notes = 'Module 1 covered what SEO is. This is the practical half: what you actually change on a page, in order of what pays.

ONE PAGE, ONE SEARCH INTENT. Each page should answer one question thoroughly. A page trying to cover three services ranks for none of them; three pages rank for three.

THE TITLE is the single highest-value element. It is what appears in results and what decides the click. Put the actual thing and the place in it — ''Laptop Repair in Westlands | Same-Day Service'' beats ''Home | Our Company''. An astonishing number of small business pages are still titled ''Home''.

THE DESCRIPTION does not affect ranking directly but decides whether someone clicks. Write it as an advert: what they get, and why you.

HEADINGS structure the page for both readers and search engines. One main heading that states what the page is about, subheadings that break up the rest.

WRITE FOR THE PERSON, using the words they use. Stuffing a phrase in eleven times reads badly and has not worked for many years.

IMAGES: describe them in the alt text, and compress them. Heavy images are the commonest cause of a slow page, and slow is the commonest cause of someone leaving before the page appears.

INTERNAL LINKS between related pages help people and search engines find what else exists.

ADDITION BEYOND THE VIDEO — where a beginner should actually spend the first hour, because it is not the blog. For a local business: complete the local business profile properly with hours, location, category and photographs; get real reviews and reply to them; put the town and neighbourhood in the page titles; and make the phone number tappable on a phone. That hour beats a month of writing articles. Test everything on a phone on mobile data rather than on a laptop — that is where the visitor is, and a page that feels fine on wifi can be unusable on a bundle.',
  practice_activity = 'Take one real page and fix it in this order: rewrite the title to name the thing and the place, write a description that earns a click, set one clear main heading, compress every image, and make the phone number tappable. Time the page load on a phone on mobile data before and after. Then complete that business''s local profile fully.',
  knowledge_check = '[{"question": "Which on-page element is worth the most?", "options": ["The title, since it appears in results and decides the click", "The keyword count in the body", "The number of internal links", "The meta description"], "correct_index": 0}, {"question": "Where should a beginner spend the first hour for a local business?", "options": ["Completing the local business profile, gathering reviews, and putting the town in page titles", "Writing a blog post", "Building links", "Researching competitors"], "correct_index": 0}]'::jsonb
where id = '02011bbd-ccc1-4736-8f81-764c5916b92d';

-- How to Make a Digital Marketing Campaign Plan
update public.lessons set
  learning_objectives = array['Write a plan with one goal and a number attached to it', 'Choose channels and budget from the goal rather than from habit', 'Define in advance what success and failure look like'],
  notes = 'A campaign plan is one page and it answers seven questions. If you cannot answer them, you are not ready to spend money.

1. WHAT IS THE GOAL, as a number and a date. ''Forty enquiries in October'', not ''more awareness''. A goal without a number cannot be failed, which means it cannot be learned from.

2. WHO IS IT FOR. Module 3 did this work; name the persona rather than redoing it.

3. WHAT IS THE OFFER. The specific thing being promoted and why someone would act now. Weak campaigns usually have no offer, just a reminder that the business exists.

4. WHICH CHANNELS, and why each. Two done properly beats five done thinly, especially on a small budget.

5. WHAT IS THE MESSAGE. One sentence you could say to a customer. If it takes a paragraph, it is not ready.

6. WHAT IS THE BUDGET, including your fee, ad spend, and anything you must produce.

7. HOW WILL YOU KNOW IT WORKED. The number from question one, and how you will measure it — which means the tracking exists before the campaign starts, not after.

WRITE THE FAILURE CONDITION TOO. At what cost per enquiry do you stop? Decide it when you are calm, not on day four when money is going out. Beginners without a stopping rule keep spending because stopping feels like admitting failure.

ADDITION BEYOND THE VIDEO — three things to build in here. TIMING follows the local calendar: school term dates and fee periods, harvest, end-of-month salaries, December. A campaign launched the week before school fees are due is competing with an emptier wallet. CAPACITY comes before demand: confirm the business can actually handle forty enquiries, because a successful campaign into a business that cannot answer the phone produces angry customers and blames you. And GET THE OFFER APPROVED IN WRITING — the price, what is included, how long it runs — because a discount the owner did not fully agree to becomes your problem when customers arrive expecting it.',
  practice_activity = 'Write a one-page plan for a real business answering all seven questions, with a number and a date on the goal. Add the failure condition - the cost per enquiry at which you stop. Then check two things before you would spend anything: that the tracking exists, and that the business can actually handle the volume you are aiming for.',
  knowledge_check = '[{"question": "Why must a goal have a number and a date?", "options": ["A goal without them cannot be failed, so nothing can be learned from the campaign", "Clients require specific figures", "Platforms need a target to optimise to", "It determines the budget automatically"], "correct_index": 0}, {"question": "What should be confirmed before launching a campaign?", "options": ["That the business can actually handle the volume of enquiries the campaign aims for", "That competitors are not advertising", "That the budget is large enough for three months", "That the website is newly designed"], "correct_index": 0}]'::jsonb
where id = 'aa37df76-6346-41ed-8a43-cc61e23f550f';

-- How to Run a Successful Multi-Channel Marketing Campaign
update public.lessons set
  learning_objectives = array['Run one message across several channels without repeating yourself identically', 'Give each channel a job in the sequence', 'Work out which channel actually caused the result'],
  notes = 'Multi-channel means the same campaign running in several places, each doing a different job. It is not the same post copied four times, which is what most beginner campaigns actually are.

GIVE EACH CHANNEL A ROLE. A workable sequence for a small business: social introduces the offer to people who do not know it; search catches those who go looking afterwards; retargeting reminds the ones who showed interest; and WhatsApp or the phone closes it. Each channel is doing something the others cannot.

KEEP ONE MESSAGE, CHANGE THE CLOTHES. The offer, the price and the deadline stay identical everywhere; the format and length change per platform. Inconsistency here is expensive — a different price on two channels is a complaint waiting to happen, and it will be screenshotted.

SEQUENCE MATTERS. Retargeting has nobody to talk to until something has run first. Search adverts on a brand nobody has heard of get no searches. Build the awareness, then catch the demand it creates.

WHICH CHANNEL GETS THE CREDIT is genuinely hard, because most people touch several before buying. Two honest approaches: tag every link so you can see the last step, and simply ask — ''where did you hear about us'' at the point of enquiry is crude, free, and often more accurate than the dashboard in a market where much of the journey is offline.

ADDITION BEYOND THE VIDEO — a multi-channel campaign here usually includes channels no international course lists. WhatsApp Status and broadcast lists to existing customers, who are the cheapest audience a business has. Physical posters or flyers where the customers actually walk, which for a local shop can outperform anything online. Announcements through a church, sacco or chama where that is how the community communicates. And the single cheapest channel of all: asking satisfied customers to tell one person. A plan that ignores these because they are not in the dashboard is leaving out the parts that work best.',
  practice_activity = 'Take one offer and plan it across four channels, writing the specific job of each and the order they run in. Keep the offer, price and deadline identical across all four and check them against each other word by word. Then decide how you will attribute the result, including one offline method such as asking every enquirer where they heard about it.',
  knowledge_check = '[{"question": "What makes a campaign multi-channel rather than repeated?", "options": ["Each channel has a distinct job in a sequence", "The same post appears in more places", "It uses a larger budget", "It runs for longer"], "correct_index": 0}, {"question": "What is often the most accurate attribution method in this market?", "options": ["Asking every enquirer where they heard about the business, since much of the journey is offline", "The platform dashboard alone", "Counting website visits", "Comparing follower growth"], "correct_index": 0}]'::jsonb
where id = '98c05fe8-9e28-4d2d-a89a-36e7400e6ec8';

-- How to Pitch Clients for Digital Marketing Services
update public.lessons set
  learning_objectives = array['Open a conversation with a specific observation rather than a service list', 'Propose work scoped to what the business can afford and absorb', 'Say plainly what you cannot promise'],
  notes = 'Most pitches fail because they describe the marketer. A pitch that works describes the client''s situation.

LEAD WITH SOMETHING YOU NOTICED AND CHECKED. ''Your Facebook page sends people to a number that is not on WhatsApp, and your Google listing has the old opening hours, so people searching in the evening think you are closed.'' You have done real work, demonstrated competence, and identified money currently being lost. That opening outperforms any list of services.

TALK IN THEIR TERMS. Not impressions and CTR — enquiries, customers, money. ''Right now you get about four enquiries a week from online. The aim is twelve.''

PROPOSE SOMETHING SMALL FIRST. A full retainer from a stranger is a big ask. One campaign, one month, one defined piece of work, with a clear result to judge — that is an easy yes, and it is how almost every long relationship starts.

BE EXPLICIT ABOUT WHAT IS YOURS AND WHAT IS THEIRS. You do not control the product, the price, whether the phone gets answered, or whether stock exists. Say so pleasantly and in writing at the start. Marketing brings people to the door; what happens at the door is the business''s job.

WHAT YOU CANNOT PROMISE: a specific number of sales, page one of search by a date, or results in the first fortnight. Promising those wins the contract and loses the client, which is a worse outcome than not winning it.

ADDITION BEYOND THE VIDEO — the commercial structure that keeps this workable here. Separate YOUR FEE from AD SPEND explicitly and in writing; conflating them is the most common and most damaging misunderstanding in this work. Take the ad budget in advance and never fund it yourself, because you will not be reimbursed reliably and it turns your fee into a loan. Price a small first engagement so a real local business can say yes rather than defer. And expect to explain the whole idea to owners who have never bought marketing before — the person who can explain it in plain language, without jargon, wins against slicker competitors more often than they expect.',
  practice_activity = 'Choose three real businesses and spend twenty minutes on each finding one specific, checkable problem - a wrong listing, a dead link, an unanswered page, a number that is not on WhatsApp. Write a short message to each leading with that observation and proposing one small defined piece of work. Send them. Also write the two sentences you will use to separate your fee from ad spend.',
  knowledge_check = '[{"question": "What should a pitch open with?", "options": ["A specific problem you noticed and checked on their own marketing", "A list of the services you offer", "Your qualifications and training", "A discount offer"], "correct_index": 0}, {"question": "Which misunderstanding is most damaging in this work?", "options": ["Conflating your fee with the advertising budget", "Not specifying the reporting date", "Failing to name the platforms used", "Working without a written brief"], "correct_index": 0}]'::jsonb
where id = 'a35960e0-4faa-499d-8ed8-f960b9dbc035';

-- How to Report Your Advertising Results to Clients
update public.lessons set
  learning_objectives = array['Write a report a busy owner will actually read', 'Report a bad month without losing the client', 'Connect the numbers to money'],
  notes = 'The report is where a client decides whether to keep paying, so it is not an afterthought — it is the deliverable that renews the contract.

ONE PAGE, IN THEIR LANGUAGE. What we spent, what it produced, what it cost per result, what we learned, what we do next. Impressions and CTR belong further down, if at all.

CONNECT IT TO MONEY. ''We spent X and got 31 enquiries at Y each. You told me about a third become customers and a customer is worth Z, so this returned about W.'' That sentence is the entire argument for your existence, and most beginners never write it because they never asked what a customer is worth. Ask at the start.

SAY WHAT YOU LEARNED. A month that produced little but identified which message works is not a wasted month, and saying so plainly is how you keep a client through a slow start.

REPORTING A BAD MONTH. Do it first, plainly, without burying it: what happened, why you think so, what you are changing, what you need from them. Clients forgive a bad month explained honestly. They do not forgive discovering it themselves, or a report that hides it in a chart on page four. If the cause is on their side — the phone unanswered, stock unavailable, the offer changed without telling you — say that factually and without blame, backed by the evidence.

BE CONSISTENT. Same day each month, same format. Predictability is itself reassuring, and it stops the client asking for updates in between.

ADDITION BEYOND THE VIDEO — two practical points. Include the OFFLINE RESULTS, because in this market they are often the majority: walk-ins, calls, WhatsApp enquiries, people who mentioned the campaign. A report that omits them undersells your own work. And deliver it in the form the client will actually read: for a small business owner, a short WhatsApp message with the three key numbers and a PDF attached gets read; a twelve-page deck emailed on a Friday does not.',
  practice_activity = 'Write a one-page report for any campaign, real or simulated, in the five-part structure. Include the money sentence - cost per enquiry, conversion rate, value of a customer, return - and if you do not know what a customer is worth, that is the question to ask the client today. Then write the same report again for a month that went badly, and read it back asking whether you would keep paying.',
  knowledge_check = '[{"question": "What is the single most important sentence in a report?", "options": ["The one connecting spend to enquiries, conversion and the value of a customer", "The total reach achieved", "The number of posts published", "A summary of the platforms used"], "correct_index": 0}, {"question": "How should a bad month be reported?", "options": ["First and plainly, with the cause, the change you are making, and what you need from the client", "Balanced against the good numbers so it is less alarming", "Omitted until the following month", "Explained in a meeting rather than in writing"], "correct_index": 0}]'::jsonb
where id = '310ba1a2-eb63-422f-ac8c-4a7530f48a78';
