-- Auto-generated by scripts/curriculum/build-backfill-sql.py -- do not
-- hand-edit; regenerate from the source plan JSON instead.
--
-- UPDATE only, addressed by lesson id. No lesson is inserted, deleted or
-- re-parented and no id changes, so lesson_progress is untouched.

-- The Bookkeeping Basics for Beginners
update public.lessons set
  learning_objectives = array['Explain what bookkeeping records and why', 'Name the five kinds of account and what belongs in each', 'Separate business money from personal money properly'],
  notes = 'Bookkeeping is recording what came in, what went out, what you own and what you owe, in a way that can be checked later. Accounting is interpreting those records. You are learning the first, and the first is where small businesses actually fail.

EVERY TRANSACTION TOUCHES TWO PLACES. Money paid for stock means cash down and stock up. A sale on credit means income up and money-owed-to-you up. You do not need formal double entry to start, but you do need the habit of asking what the other side of each transaction is, because that is what makes the books balance and errors findable.

THE FIVE KINDS OF ACCOUNT:
ASSETS - what the business owns or is owed: cash, the M-Pesa float, stock, equipment, money customers owe.
LIABILITIES - what it owes: suppliers, loans, unpaid taxes.
EQUITY - what the owner put in and what the business has kept.
INCOME - what it earns.
EXPENSES - what it spends to earn that.
Every transaction you will ever record belongs in two of those.

WHY IT MATTERS BEYOND COMPLIANCE: without records you cannot tell whether you are actually making money, which products earn and which quietly lose, who owes you, or what you can afford next month. Most small businesses here run on the balance showing on a phone, which is not the same thing at all.

ADDITION BEYOND THE VIDEO - the single biggest bookkeeping problem for a small business in Kenya, and it is not a technical one. BUSINESS AND PERSONAL MONEY RUN THROUGH THE SAME M-PESA NUMBER. Fees, shopping, fare, stock and a customer payment all sit in one statement, and no amount of software fixes it afterwards. The fix is structural and it is the first thing you should do for any client: a SEPARATE TILL, PAYBILL OR BUSINESS NUMBER for the business, and the owner paying themselves a stated amount that is recorded as drawings rather than dipping in. Second, TREAT TRANSACTION CHARGES AS THEIR OWN EXPENSE CATEGORY - individually small, genuinely material over a year, and almost never recorded. Third, PHOTOGRAPH RECEIPTS as they are collected, because paper receipts fade and a phone photograph filed monthly is a real record when a figure is questioned.',
  practice_activity = 'Take one real small business - your own or one you know - and list every place money arrives and leaves: till, paybill, personal number, cash box, bank. Then classify twenty of its recent transactions into the five account types, and write down every one where business and personal money were mixed.',
  knowledge_check = '[{"question": "What is the difference between bookkeeping and accounting?", "options": ["Bookkeeping records the transactions; accounting interprets those records", "Bookkeeping is manual, accounting uses software", "Bookkeeping is for small businesses only", "They are different names for the same work"], "correct_index": 0}, {"question": "What is the biggest practical bookkeeping problem for a Kenyan small business?", "options": ["Business and personal money running through the same M-Pesa number", "Choosing the right software", "Not knowing double entry", "Forgetting to file returns"], "correct_index": 0}]'::jsonb
where id = '732ec2e7-5a2b-466d-9144-a25bab53deeb';

-- QuickBooks Online Tutorial for Beginners (Everything You Need)
update public.lessons set
  learning_objectives = array['Describe what accounting software does for you', 'Judge honestly whether a client should pay for it', 'Know what the skill is worth even where the software is not used'],
  notes = 'QuickBooks is the industry standard, and learning it is worth doing because employers and international clients name it. Learn what it DOES, because that is what transfers.

WHAT THE SOFTWARE ACTUALLY GIVES YOU: a permanent record that cannot be quietly overwritten like a spreadsheet cell; automatic double entry, so you cannot record only one side; invoices you can send and track; reports produced instantly rather than rebuilt; and reconciliation against a statement as a guided process. Those five are the value, and they are the same in every package.

THE LAYOUT IS THE SAME EVERYWHERE: a chart of accounts listing every category, customers and suppliers, transactions in and out, banking, and reports. Every competing product uses different words for those six things.

BE HONEST ABOUT THE COST. This is a monthly subscription billed in foreign currency, and for a shop with forty transactions a week it can be a meaningful share of the profit. A client should pay for it when the volume, the number of people involved, or a lender or auditor asking for proper books makes it worth the money - not because a course used it.

ADDITION BEYOND THE VIDEO - two realities that change how this is used here, and both are worth saying to a client before they subscribe. First, AUTOMATIC BANK FEEDS MOSTLY DO NOT WORK WITH KENYAN BANKS AND NOT WITH M-PESA, which is where most of the transactions are. Module 4 covers what to do instead, but understand the consequence now: the labour-saving that justifies the subscription in other markets often does not arrive here, and someone still imports or enters the transactions. Second, and following from that, A WELL-BUILT SPREADSHEET IS THE RIGHT ANSWER FOR MANY SMALL CLIENTS - a proper table of transactions with categories, a monthly summary and a reconciliation against the M-Pesa statement gives them what they actually need at no monthly cost. Learn QuickBooks for the jobs that require it and for your own employability, and be the person who says plainly when a client does not need it. That honesty is what gets you the work.',
  practice_activity = 'Open a free trial and find the six parts named above - chart of accounts, customers, suppliers, transactions, banking, reports. Then take one real small business and write a one-page recommendation: software or spreadsheet, with the monthly cost, what it would actually save them, and your reasoning in three sentences.',
  knowledge_check = '[{"question": "What does accounting software give you that a spreadsheet does not?", "options": ["A record that cannot be quietly overwritten, and automatic double entry", "Faster typing", "Cheaper running costs", "Better charts"], "correct_index": 0}, {"question": "Why is the usual justification for the subscription weaker here?", "options": ["Automatic bank feeds mostly do not work with Kenyan banks or M-Pesa, so someone still enters the transactions", "The software is not available in Kenya", "Reports are less accurate", "It cannot handle shillings"], "correct_index": 0}]'::jsonb
where id = 'c672e379-770e-4c14-9950-46fe5a5fd161';

-- QuickBooks Online: The Complete Tutorial
update public.lessons set
  learning_objectives = array['Set a company file up correctly from the start', 'Work through the everyday cycle of recording', 'Avoid the setup mistakes that are painful to undo'],
  notes = 'This is the long working tutorial. Follow it with a practice company open, and use a real business you know rather than invented data, because real data produces the awkward cases that teach you something.

SETTING UP, and get these right because changing them later is unpleasant: the financial year, the currency, whether the business is registered for VAT, the chart of accounts, and opening balances - what the business owned, owed and held in cash on the day you start. Starting without opening balances produces books that never agree with reality.

THE EVERYDAY CYCLE, which is the whole job: record income, record expenses, record what customers owe and what you owe suppliers, bring in the bank and mobile money transactions, categorise them, reconcile against the statement, then report.

THE CHART OF ACCOUNTS IS THE SPINE. Module 7 builds one properly. For now, the rule is fewer categories than you think - a chart with ninety accounts means nobody categorises consistently and every report is noise.

CUSTOMERS AND SUPPLIERS AS RECORDS, not as words typed into a description, because that is what makes who-owes-what answerable in one click.

DATE EVERYTHING ON THE DAY IT HAPPENED, not the day you typed it. A month of transactions entered on the 30th tells you nothing about when money actually moved.

ADDITION BEYOND THE VIDEO - the set-up decisions specific to working here. SET THE CURRENCY AND DATE FORMAT DEFERENTIALLY TO LOCAL CONVENTION at the start, because an American date format silently turns the 3rd of April into the 4th of March across a whole year of entries. Decide the VAT SETTING from what the business is actually registered for rather than what it expects to be - check the current position on iTax rather than assuming. Create accounts for the things this market really has and imported charts omit: MOBILE MONEY TRANSACTION CHARGES, a separate MOBILE MONEY account distinct from the bank, OWNER DRAWINGS, and BAD DEBT, because credit given to regular customers and never collected is a real and common cost that goes unrecorded.',
  practice_activity = 'Set up a practice company for a real business: financial year, local currency and date format, the correct VAT setting, opening balances, and a chart with mobile money, transaction charges, owner drawings and bad debt. Then record one full week of its real transactions, dated on the days they happened.',
  knowledge_check = '[{"question": "Why record opening balances at the start?", "options": ["Without them the books never agree with reality", "The software will not run without them", "It speeds up reconciliation", "It is required for VAT"], "correct_index": 0}, {"question": "What silently corrupts a year of entries?", "options": ["A foreign date format turning 3 April into 4 March", "Too few account categories", "Recording customers as records", "Using the local currency"], "correct_index": 0}]'::jsonb
where id = 'a2326d49-387f-4e64-b221-5d1ffe4e68ac';

-- How to Reconcile Your Accounts in QuickBooks Online
update public.lessons set
  learning_objectives = array['Explain what reconciliation proves', 'Work the reconciliation screen confidently', 'Find a difference instead of forcing the books to agree'],
  notes = 'Reconciliation is checking your records against the statement the bank or mobile money provider produced, so that every transaction in one appears in the other. It is the backbone of bookkeeping: until it reconciles, no report you produce means anything.

WHAT IT PROVES: that nothing was missed, nothing was entered twice, and no amount was typed wrongly. Without it, a profit figure is a guess.

THE PROCESS: take the statement for a period, enter its closing balance, tick off every transaction that appears in both, and see what is left. What is left is the work.

THE FOUR REASONS IT DOES NOT AGREE, in the order to check:
A TRANSACTION IN THE STATEMENT BUT NOT IN YOUR RECORDS - usually a charge, a standing payment or something the owner did without telling you.
A TRANSACTION IN YOUR RECORDS BUT NOT THE STATEMENT - entered twice, or dated in the wrong month.
A WRONG AMOUNT, often two digits transposed. A difference divisible by nine is nearly always a transposition, which is a genuinely useful trick.
A WRONG DATE, putting a transaction either side of the period end.

NEVER FORCE IT. The worst thing in bookkeeping is an adjustment entered to make the numbers agree. It hides the real error, it compounds every month afterwards, and it is exactly what an auditor or a lender looks for. Find the difference, however long it takes.

RECONCILE MONTHLY, not yearly. A month of transactions is findable; a year is a project.

ADDITION BEYOND THE VIDEO - reconciling what a Kenyan business actually transacts on. THE M-PESA STATEMENT IS THE MAIN ONE, not the bank, and it can be requested in full rather than read off the app - do that, because the app history is partial and awkward. It arrives with every transaction, the charge on each, and a balance, and it is the most complete record most small businesses have. RECONCILE EACH SOURCE SEPARATELY: the till or paybill, the personal number if business money still runs through it, the bank, and cash. Reconciling a combined pile is how errors hide. Expect TRANSFERS BETWEEN THE OWNER''S OWN ACCOUNTS to look like income or expense and to be miscounted as both - they are neither, and catching them is one of the commonest real corrections you will make.',
  practice_activity = 'Take one real month of an M-Pesa statement and the corresponding records. Reconcile them properly: tick off matches, list what remains, and identify each difference by its type. Check any unexplained difference for divisibility by nine. Write down every transfer between the owner''s own accounts that had been counted as income or expense.',
  knowledge_check = '[{"question": "Why should a difference never be forced with an adjustment?", "options": ["It hides the real error, compounds monthly, and is what an auditor looks for", "Adjustments are not permitted by the software", "It changes the VAT position", "It cannot be undone"], "correct_index": 0}, {"question": "A reconciliation difference is divisible by nine. What does that suggest?", "options": ["Two digits transposed in an amount", "A missing transaction", "A duplicate entry", "A date in the wrong month"], "correct_index": 0}]'::jsonb
where id = 'fb2e8c2d-1b1b-4409-a719-033efd3bf399';

-- Reading Profit & Loss and Balance Sheet Reports
update public.lessons set
  learning_objectives = array['Read the two core reports and say what each answers', 'Explain the difference between profit and cash', 'Turn a report into advice an owner can act on'],
  notes = 'Two reports carry almost all of the value in bookkeeping, and most small business owners have never had either explained to them.

THE PROFIT AND LOSS covers a period and answers whether the business made money. Income, minus the direct cost of what was sold, gives gross profit; minus the running costs gives net profit. Read it by comparing periods rather than staring at one month - this month against last, and against the same month last year.

THE BALANCE SHEET is a moment, not a period, and answers what the business is worth and what it owes. Assets equal liabilities plus equity, always. It is where you see money owed by customers piling up, a loan that is not being repaid, or stock that has grown while sales have not.

THE MOST IMPORTANT THING TO EXPLAIN TO AN OWNER: PROFIT IS NOT CASH. A business can be profitable and unable to pay anyone, because the profit is sitting in stock and in customers who have not paid. This one explanation is the most valuable service a bookkeeper gives a small business here, and it is the reason profitable businesses close.

WHAT TO LOOK AT EACH MONTH: is gross profit percentage holding or slipping, which expense has grown, how much is owed to us and how long has it been owed, and do we have enough cash for what is coming.

ADDITION BEYOND THE VIDEO - make the report answer what the owner actually asks, in their words. They do not ask about gross margin; they ask whether the business is making money, whether they can afford the new machine, and why there is nothing in the till when sales were good. Answer those three, on ONE PAGE, IN SHILLINGS, with a short sentence per figure - and send it in a way that gets read, which here usually means a message with the headline numbers in the text and the report attached rather than a report alone. Pay particular attention to MONEY OWED BY CUSTOMERS, because informal credit to regular customers is normal here, is rarely written down, and is where small businesses lose their working capital without noticing. And separate the OWNER''S DRAWINGS from expenses in what you present, because an owner looking at a loss caused by their own withdrawals is being told something untrue about their business.',
  practice_activity = 'Produce both reports for one real business for the last three months. Write a one-page summary in shillings answering the three questions the owner actually asks, list who owes money and for how long, and show drawings separately from expenses. Then explain the profit-is-not-cash point to the owner and note their reaction.',
  knowledge_check = '[{"question": "Why can a profitable business be unable to pay anyone?", "options": ["The profit is sitting in stock and in customers who have not paid", "The reports are produced incorrectly", "Profit is calculated after tax", "Expenses are recorded late"], "correct_index": 0}, {"question": "Why separate owner drawings from expenses in a report?", "options": ["An owner shown a loss caused by their own withdrawals is being told something untrue", "Drawings are not deductible", "It simplifies the balance sheet", "Software requires the separation"], "correct_index": 0}]'::jsonb
where id = '306b00f1-5343-4e3c-8ba4-88428633346c';

-- Automating Categorization with Bank Rules
update public.lessons set
  learning_objectives = array['Write rules that categorise repeated transactions', 'Keep automation from quietly producing wrong books', 'Decide what must always be reviewed by a person'],
  notes = 'A rule says that when a transaction matches a pattern - this supplier name, this amount, this description - categorise it this way automatically. On a business with hundreds of repetitive transactions it removes most of the typing.

WHERE RULES ARE SAFE: fixed, recurring, unambiguous payments. Rent to the same landlord, the same amount every month. Electricity. The airtime purchase. Transaction charges. A regular supplier who sells you only one kind of thing.

WHERE THEY ARE DANGEROUS: any payee you buy different things from. A rule that sends every payment at a supermarket to Office Supplies will confidently misfile the stock purchase, the owner''s shopping and the staff tea for a year, and nobody notices until the accounts are questioned.

THE DISCIPLINE: build a rule only after you have seen the same transaction categorised the same way several times by hand. Rules are a record of a pattern you have observed, not a guess about the future.

REVIEW BEFORE ACCEPTING. Most software can apply a rule automatically or suggest it for confirmation. Suggest-and-confirm is the right setting for everything except the handful you are certain of. The minute saved is not worth a month of miscategorised books.

CHECK YOUR RULES EVERY FEW MONTHS. Businesses change suppliers and habits, and a rule that was right in March is quietly wrong by September.

ADDITION BEYOND THE VIDEO - the categories that automation gets wrong here, and where a person must always look. MOBILE MONEY DESCRIPTIONS ARE OFTEN JUST A NAME OR A NUMBER, so a rule matching on a person''s name will catch a supplier, a customer refund and the owner''s cousin equally. Never rule on a bare personal name. TRANSFERS BETWEEN THE BUSINESS''S OWN ACCOUNTS - till to bank, bank to personal - look exactly like income or expense and must be handled by a person, because automating them inflates both income and expenses and produces books that look busy and mean nothing. And CASH WITHDRAWALS are not an expense: what matters is what the cash was then used for, which no rule can know. Those three cover most of the damage automation does to a small set of Kenyan books.',
  practice_activity = 'List every transaction that repeats monthly for one real business and build rules only for those that are fixed and unambiguous, set to suggest rather than apply automatically. Then write down the three categories you will always review by hand, and check a month of past entries for transfers that were counted as income or expense.',
  knowledge_check = '[{"question": "When should a rule be created?", "options": ["After you have categorised the same transaction the same way by hand several times", "Before starting, to save work", "Whenever a payee appears twice", "When the software suggests one"], "correct_index": 0}, {"question": "Why must transfers between a business''s own accounts never be automated?", "options": ["They look like income or expense and automating them inflates both", "They are taxed differently", "The software cannot detect them", "They occur too infrequently"], "correct_index": 0}]'::jsonb
where id = 'a0fa3750-6553-4be9-8058-d06bae95a9e5';
