-- Auto-generated by scripts/curriculum/build-backfill-sql.py -- do not
-- hand-edit; regenerate from the source plan JSON instead.
--
-- UPDATE only, addressed by lesson id. No lesson is inserted, deleted or
-- re-parented and no id changes, so lesson_progress is untouched.

-- How to Write a Resume With No Experience (Free Template)
update public.lessons set
  learning_objectives = array['Write a CV when you have no formal employment history', 'Turn what you have actually done into evidence', 'Choose the right document for the job you are applying to'],
  notes = 'A CV exists to get you an interview. Nothing else. Every decision about it follows from that.

WHEN YOU HAVE NO FORMAL JOB HISTORY, you still have material, and most people underestimate it badly. Attachments and internships. Casual and holiday work. A family business you helped run. A group or committee you organised. Church or community responsibility. A course project. Anything you sold. Tutoring. All of it is experience if you describe what you DID and what CHANGED because of it.

THE FORMAT THAT WORKS: name and contacts at the top, a two-line summary saying what you are and what you are looking for, then skills, then experience, then education. Put whichever of skills or experience is stronger first.

DESCRIBE OUTCOMES, NOT DUTIES. Not responsible for social media, but grew the shop page from 200 to 1,400 followers in four months and handled orders through it. Numbers make a claim checkable, and a checkable claim is believed.

KEEP IT TO TWO PAGES AT MOST and one if you are starting out. Every line should earn its place.

BE HONEST. Dates, titles and qualifications get checked, and an exaggeration discovered later costs the job rather than the interview.

ADDITION BEYOND THE VIDEO - the most useful thing in this whole course: THE KENYAN CV AND THE INTERNATIONAL RESUME ARE DIFFERENT DOCUMENTS, and sending the wrong one hurts you either way. A LOCAL CV commonly runs to two pages, often names referees with their contacts, and frequently includes personal details and sometimes a photograph, because that is what many employers here still expect. An INTERNATIONAL OR REMOTE RESUME should be one page, with no photograph, no age, no marital status, no religion and no referees listed - including those things marks you as unfamiliar with the convention and, in some systems, is actively unhelpful. KEEP BOTH VERSIONS and choose by employer. Also assemble your DOCUMENT FOLDER early, because local applications ask for it and scrambling costs you deadlines: scanned certificates and transcripts, your national identification, your KRA PIN, and a certificate of good conduct, which takes time to obtain - start it before you need it.',
  practice_activity = 'Write down every unpaid, casual, family or community thing you have done and rewrite each as an outcome with a number where one exists. Then build both versions: a two-page local CV with referees, and a one-page international resume with no photograph or personal details. Start your certificate of good conduct application this week.',
  knowledge_check = '[{"question": "How should experience be described?", "options": ["As outcomes with numbers, not as duties", "As a full list of responsibilities", "In the words of the job advert", "As briefly as possible"], "correct_index": 0}, {"question": "What belongs on a local CV but not an international resume?", "options": ["A photograph, personal details and named referees", "A skills section", "A two-line summary", "Education history"], "correct_index": 0}]'::jsonb
where id = '561177b0-7b8b-4e03-a93d-7fe71c41825e';

-- How to Make Your LinkedIn Profile Discoverable to Recruiters
update public.lessons set
  learning_objectives = array['Understand how recruiters actually find people', 'Fill the fields that decide whether you appear in a search', 'Judge how much LinkedIn matters for the work you want'],
  notes = 'Recruiters do not browse. They SEARCH, with filters: job title, skills, location, and the words in your profile. Being discoverable means containing the words they type.

THE FIELDS THAT DECIDE WHETHER YOU APPEAR:
THE HEADLINE, which carries the most weight and which most people waste on their current employer''s name.
THE ABOUT SECTION, where the words you use about your work belong.
EACH ROLE, with a real title and a description containing the actual tools and skills.
THE SKILLS LIST, which is directly filtered on.
LOCATION, which is filtered on constantly.

USE THE WORDS THE INDUSTRY USES, not a clever internal title. Nobody searches for growth ninja; people search for social media manager, data analyst, accountant.

THE PHOTOGRAPH matters here, unlike on an international resume. A clear, friendly, well-lit picture of your face. It does not need a studio; it needs daylight and a plain background.

COMPLETE THE PROFILE. Half-finished profiles rank poorly and read as abandoned.

TURN ON the setting that tells recruiters you are open to work, and set it to be visible only to recruiters if your current employer is a concern.

ADDITION BEYOND THE VIDEO - be realistic about where LinkedIn works, because time spent on it is time not spent elsewhere. IT MATTERS GENUINELY for remote and international work, for professional and corporate roles, and for anything in technology, development, finance or marketing - if that is your target, this is worth real effort. IT MATTERS MUCH LESS for local informal hiring, trades, shops, salons and most small businesses here, which hire by referral and WhatsApp, and no profile will change that. Be honest about which world your target job is in and spend your effort accordingly. Two practical points: SET YOUR LOCATION TO THE CITY RECRUITERS WILL SEARCH rather than a small area nobody filters on, and where you would genuinely relocate or work remotely, say so in the About section, because location filters are where most applicants here are silently excluded.',
  practice_activity = 'Search LinkedIn for the job title you want, as a recruiter would, and look at the first ten profiles - note what their headlines and skills say. Then rewrite your own headline, About section and skills using the words the industry actually uses, set your city and your openness to remote work, and add a daylight photograph.',
  knowledge_check = '[{"question": "How do recruiters find people?", "options": ["By searching with filters on title, skills, location and profile words", "By browsing their feed", "Through mutual connections only", "Through job application lists"], "correct_index": 0}, {"question": "Where does LinkedIn effort pay off least?", "options": ["Local informal hiring, trades and small businesses, which hire by referral", "Remote international work", "Corporate professional roles", "Technology and finance roles"], "correct_index": 0}]'::jsonb
where id = '47a55d49-0f41-4d41-bf5f-cc869a80871f';

-- The Best Resume Template for ATS Scanners (and How to Keyword It)
update public.lessons set
  learning_objectives = array['Explain what an applicant tracking system does', 'Format a document so it can be read by machine and person', 'Judge when ATS advice actually applies to you'],
  notes = 'An applicant tracking system is software that receives applications, extracts the text, and lets a recruiter search and filter it. It does not usually reject you on its own - a person still decides - but if it cannot read your document, you are invisible to that person.

WHAT BREAKS MACHINE READING, and this is the whole practical point: text inside images, text in tables and columns, headers and footers carrying important information, unusual fonts, graphics and icons where words should be, and a file format that is not a straightforward document or PDF.

WHAT READS CLEANLY: a single column, ordinary section headings - Experience, Education, Skills - a standard font, real text rather than pictures of text, and a sensible filename with your name in it.

KEYWORDS: use the words in the job advert where they are genuinely true of you. If they say inventory management and you did that, write inventory management rather than a synonym. That is not gaming; it is answering the question they asked.

WHAT NOT TO DO: stuffing invisible keywords, white text, or listing skills you do not have. It is detected, it is embarrassing, and the interview exposes it anyway.

ONE DOCUMENT FOR BOTH READERS. A clean single-column CV reads well to a machine AND to a tired human scanning for eight seconds, which is the actual constraint.

ADDITION BEYOND THE VIDEO - apply this advice where it belongs, because ATS guidance is written for a market that is not entirely yours. AN APPLICANT TRACKING SYSTEM IS ALMOST CERTAINLY IN USE for international and remote roles, large corporates, banks, telecoms and big NGOs. IT IS OFTEN NOT IN USE for the many local jobs applied to by email, on a county or institutional portal, or by delivering a printed copy - there a person reads it, and readability and a decent printed appearance matter more than machine parsing. The good news is the same document serves both: single column, plain fonts, real text. Two local notes: name the file properly, because an inbox holding forty files called CV will lose yours - use your own name and the role; and SEND A PDF unless the advert asks otherwise, since a document file reflows differently on someone else''s machine and can arrive looking broken.',
  practice_activity = 'Take your CV and strip out every table, column, text box, icon and header. Rebuild it single-column with plain headings and real text. Then copy the whole document into a plain text editor - whatever is lost or scrambled there is what a machine sees. Rename the file with your name and the role, and export a PDF.',
  knowledge_check = '[{"question": "What is the practical risk of a heavily formatted CV?", "options": ["The system cannot extract the text, so a recruiter never sees it", "It is automatically rejected", "It prints badly", "It exceeds the file size limit"], "correct_index": 0}, {"question": "How can you see what a machine reads from your CV?", "options": ["Copy it into a plain text editor and see what is lost or scrambled", "Print it in greyscale", "Open it on a phone", "Send it to yourself by email"], "correct_index": 0}]'::jsonb
where id = 'c3e55bf6-70d5-4eb2-85e2-53c3d2a262df';

-- Beyond the Resume: Personal Branding Strategies for Job Seekers
update public.lessons set
  learning_objectives = array['Define personal branding as something concrete', 'Build evidence that exists outside your own claims', 'Be findable when someone searches your name'],
  notes = 'Personal branding sounds like self-promotion and is really something simpler: what someone finds, and what someone says, when they check up on you. You have one whether you built it or not.

THE THREE PARTS:
WHAT YOU SAY YOU ARE - your CV, your profile, your one-sentence description of yourself.
WHAT YOU CAN SHOW - work anyone can look at. Written pieces, designs, a repository, a spreadsheet you built, photographs of work you did, a short video explaining something.
WHAT OTHERS SAY - recommendations, references, and people who will vouch for you unprompted.

THE SECOND ONE CARRIES THE MOST WEIGHT AND IS BUILT LEAST. Anybody can claim a skill. A person who can point to the thing they made ends the argument. If you have no client work, make something real for a real situation and show that.

CONSISTENCY across your CV, your profile and how you introduce yourself. Three different descriptions read as someone who does not know what they are.

BE FINDABLE AND CHECKABLE. Search your own name. What appears is what an employer sees, and an empty result is better than something unfortunate but worse than something good.

SHARE WHAT YOU ARE LEARNING, in small useful pieces. Not thought leadership - a short post about something you actually worked out is enough, and it accumulates.

ADDITION BEYOND THE VIDEO - what this looks like here rather than in a career advice video. THE MOST POWERFUL FORM OF THIS IN KENYA IS BEING KNOWN TO PEOPLE, because a large share of jobs are filled through referral before they are ever advertised. That is worth stating plainly rather than resenting: it means the practical version of personal branding is that the people around you - former classmates, colleagues, church and community, people in your trade - know specifically what you do and are able to mention your name. Tell them what you are looking for, in one clear sentence they can repeat. Second, WHATSAPP AND FACEBOOK GROUPS in your field are where much of this happens, so being visibly useful in one of those does more than any amount of profile polishing. Third, CLEAN UP WHAT IS ALREADY PUBLIC before you start adding - old posts, open profiles, anything you would not want read by an interviewer - because employers here do look.',
  practice_activity = 'Search your own name and write down everything an employer would find. Then build one piece of showable work for a real situation and put it somewhere you can link to. Write your one-sentence description and tell it to five people who might hear of an opening, in words they can repeat.',
  knowledge_check = '[{"question": "Which part of a personal brand carries most weight and is built least?", "options": ["Work anyone can look at", "Your CV wording", "Your job title", "Recommendations"], "correct_index": 0}, {"question": "What is the practical form of personal branding here?", "options": ["The people around you knowing specifically what you do, so they can mention your name", "Posting daily on LinkedIn", "A designed personal logo", "A personal website"], "correct_index": 0}]'::jsonb
where id = '7bebf2b9-07ed-442a-a099-8e702e70fc86';

-- Writing a Keyword Optimized Resume: Get Past the ATS Scanners
update public.lessons set
  learning_objectives = array['Read a job advert for the words that matter', 'Place those words where they are read and believed', 'Stay on the right side of honest'],
  notes = 'Tailoring a CV to a job means answering the question that advert asked, in the words it asked it. Sending the same document to forty employers is why forty employers do not reply.

READ THE ADVERT PROPERLY and mark three things: the hard requirements, which are usually in a must-have list; the tools and systems named; and the words repeated more than once, which tell you what they actually care about.

PLACE THE WORDS WHERE THEY ARE READ: the summary at the top, the skills list, and inside the experience bullets where you genuinely did that thing. A skills list containing a word the rest of the document never demonstrates is noticed by the person, even if it satisfies the machine.

MIRROR THEIR VOCABULARY. If they say stock control and you wrote inventory, change it. Same thing, and matching is free.

PRIORITISE, DO NOT JUST ADD. Move the relevant experience up, cut what is irrelevant to this role, and rewrite the top summary for this job. That takes fifteen minutes and is most of the value.

THE HONESTY LINE IS SIMPLE: you may change wording, order and emphasis. You may not claim what you did not do. Everything on the page must survive being asked about for five minutes.

KEEP A MASTER CV with everything you have ever done, and cut each application down from it. Much faster than rewriting, and you stop forgetting things.

ADDITION BEYOND THE VIDEO - the realistic version when you are sending many applications. TAILORING TAKES FIFTEEN MINUTES, NOT TWO HOURS: rewrite the summary, reorder the experience, match the vocabulary, and stop. Ten tailored applications beat a hundred identical ones, and that is the whole argument. Second, WHERE THE ADVERT NAMES A REQUIREMENT YOU PARTLY MEET, address it rather than hiding it - a line saying what you have done that is closest, and how quickly you learnt something similar, is far better than leaving a gap the reader fills in for themselves. Third, BE CAREFUL WHAT YOU SEND WITH IT: applications here often ask for scanned certificates and identification, and those documents are valuable to a fraudster, so send them only to an employer you have verified is real, and never to an advert that came by WhatsApp from someone you cannot identify.',
  practice_activity = 'Build a master CV containing everything you have ever done. Then take three real adverts and produce three tailored versions in fifteen minutes each, marking the hard requirements, the named tools and the repeated words in each advert first. Check every line of each version would survive five minutes of questioning.',
  knowledge_check = '[{"question": "What does tailoring actually involve?", "options": ["Rewriting the summary, reordering experience and matching vocabulary - about fifteen minutes", "Rewriting the whole document", "Adding every keyword in the advert", "Changing the design for each employer"], "correct_index": 0}, {"question": "Where is the honesty line?", "options": ["Change wording, order and emphasis; never claim what you did not do", "Anything the system cannot verify is acceptable", "Keywords may be added freely", "Job titles may be adjusted upward"], "correct_index": 0}]'::jsonb
where id = 'a7590959-086b-491f-b72b-20441541cf54';

-- LinkedIn Headline Formula That Works
update public.lessons set
  learning_objectives = array['Write a headline that appears in the right searches', 'Say what you do and who you do it for in one line', 'Avoid the phrasings that make a profile invisible'],
  notes = 'The headline is the line under your name. It follows you everywhere on the platform, it carries heavy weight in search, and most people waste it on their employer''s name - which recruiters are not searching for.

THE FORMULA THAT WORKS: what you are, plus what you do or who you do it for, plus something specific. Data Analyst. Turning messy operational data into reports managers use. Excel, Power BI, SQL. Three short parts, each searchable.

USE THE JOB TITLE SOMEONE WOULD TYPE. If you want to be found as an accountant, the word accountant must be there. Aspiring, enthusiast, and self-taught all weaken it and none of them help you appear in a search - if you can do the work, name the work.

INCLUDE THE TOOLS OR SPECIALISMS a recruiter would filter by, because those are literal search terms.

WHAT MAKES A HEADLINE INVISIBLE: only a company name, only a slogan, a motivational quote, or a string of emoji and buzzwords. Also Student at, when you have already done relevant work - lead with what you can do and put the studying after it.

IF YOU ARE CHANGING FIELD, write the headline for the job you are going toward, honestly - naming the skills you have that belong to it rather than the title you have not yet held.

ADDITION BEYOND THE VIDEO - two adjustments for how this is actually searched from here. PUT THE THING A LOCAL OR REMOTE EMPLOYER WOULD FILTER ON in the headline itself, including whether you work remotely, because remote is a filter term and the profiles that say it are the ones that surface. Second, AVOID NAMING ONLY AN INSTITUTION OR AN EMPLOYER nobody outside the country recognises, and describe the function instead - a headline saying the role and the skills travels, while one naming a small local company means nothing to a recruiter three thousand kilometres away. And keep the whole thing readable on a phone, since that is where it will be seen: the first several words carry it, so put the job title first.',
  practice_activity = 'Write five versions of your headline using the three-part formula, each leading with the job title someone would type. Search that title yourself and see whether your profile appears in the results. Then check how the headline truncates on a phone and rewrite so the first few words still say what you are.',
  knowledge_check = '[{"question": "What is the commonest waste of a headline?", "options": ["Filling it with an employer''s name, which recruiters do not search for", "Listing too many skills", "Making it too long", "Including a specialism"], "correct_index": 0}, {"question": "Why avoid words like aspiring or self-taught?", "options": ["They weaken the headline and do not help you appear in any search", "They are considered unprofessional", "They take up character space", "Recruiters filter them out deliberately"], "correct_index": 0}]'::jsonb
where id = '01eb56d9-0755-4068-8456-47c2e1ad5b39';
