-- Auto-generated by scripts/curriculum/build-backfill-sql.py -- do not
-- hand-edit; regenerate from the source plan JSON instead.
--
-- UPDATE only, addressed by lesson id. No lesson is inserted, deleted or
-- re-parented and no id changes, so lesson_progress is untouched.

-- Python and Visual Studio Code for Beginners
update public.lessons set
  learning_objectives = array['Get Python running on the machine you actually have', 'Run your first program and understand what just happened', 'Know the free route when installing is not an option'],
  notes = 'Python is a language whose main virtue is that it reads almost like English, which is why it is the usual first language and why you can build something useful within weeks.

WHAT YOU ARE INSTALLING: Python itself, which runs your code, and an editor - Visual Studio Code - which is where you write it. They are separate things and beginners often conflate them.

THE INSTALL, in order: install Python and tick the option to add it to PATH, which is the step everyone misses and the cause of the python is not recognised error that follows. Then install VS Code, then its Python extension.

YOUR FIRST PROGRAM is one line that prints something. Run it and watch the output appear in the terminal. That loop - write, run, read the output - is the whole of programming, and everything after this is the same loop with more in it.

READ THE ERROR MESSAGES. Python''s errors are unusually clear: they name the file, the line and what went wrong. Beginners panic at red text and skip the one sentence that says exactly what to fix. The last line is the useful one.

USE THE TERMINAL inside the editor rather than a separate window, so what you write and what happens sit side by side.

ADDITION BEYOND THE VIDEO - the route that matters if your machine is modest, borrowed or not yours. YOU DO NOT HAVE TO INSTALL ANYTHING. A free browser notebook runs Python on someone else''s computer, needs no installation, works on a low-specification laptop or a cyber-cafe machine, and is how a great many people here should start - it removes the step that stops most beginners before they have written a line. Download your work when you finish, because a session ends and takes its files with it. Second, INSTALLING PACKAGES COSTS DATA: some libraries are large, so install on wifi where you can, and be aware that a failed install halfway through a bundle is a common and demoralising way to lose an evening. Third, if you do install locally, USE A VIRTUAL ENVIRONMENT per project once you are past the first few weeks - it keeps one project''s packages from breaking another''s, and learning it early saves a confusing afternoon later.',
  practice_activity = 'Get Python running by whichever route suits your machine - installed locally with PATH ticked, or a free browser notebook - and run a program that prints your name. Then deliberately break it, read the error message, and fix it from what the last line says. Write down which route you chose and why.',
  knowledge_check = '[{"question": "Which install step is missed most often?", "options": ["Ticking the option to add Python to PATH", "Installing the editor first", "Choosing the install directory", "Restarting the machine"], "correct_index": 0}, {"question": "What should you do if your machine cannot run a local install?", "options": ["Use a free browser notebook, which needs no installation and runs on any machine", "Wait until you can buy a laptop", "Use a phone app instead", "Learn a different language"], "correct_index": 0}]'::jsonb
where id = 'a786c86a-19ab-4d76-8c0d-215cfb25a1c1';

-- Python Variables — Tutorial for Beginners with Examples
update public.lessons set
  learning_objectives = array['Store and reuse values in a program', 'Distinguish the basic types and why the difference matters', 'Take input from a person and use it safely'],
  notes = 'A variable is a name pointing at a value. That is all. The reason it matters is that a program which refers to names rather than to typed-in values can be changed in one place.

THE TYPES YOU WILL USE CONSTANTLY: a whole number, a decimal number, text, and true-or-false. Python works out the type from what you assign, which is convenient and is also where a specific class of bug lives.

THE BUG THAT CATCHES EVERY BEGINNER: input from a person arrives as TEXT, always, even when they typed a number. Adding 1 to it either fails or joins it onto the end as characters. Convert it deliberately before doing arithmetic - and be ready for the conversion to fail when they type something that is not a number, which Module 4 covers.

NAMING: lowercase with underscores, and names that say what the thing is. total_price, not tp or x. You write a name once and read it fifty times.

TEXT FORMATTING: build strings by inserting values into them rather than gluing pieces together with plus signs, which is both easier to read and avoids the type errors above.

CONSTANTS - values that should not change, like a rate - go in clearly named variables at the top of the file, exactly as in the spreadsheet course. Never type a number into the middle of your logic.

ADDITION BEYOND THE VIDEO - two habits worth forming now because they are painful to retrofit. FIRST, NEVER PUT A PASSWORD, API KEY OR PHONE NUMBER DIRECTLY IN YOUR CODE. Read it from the environment or a separate file you do not share, because code gets copied, pasted into a chat, and pushed to a public repository, and a key in a public repository is found by automated scanners within minutes. This is the single most common serious mistake beginners make and it has real consequences. Second, WRITE FOR THE PERSON WHO READS IT NEXT, who is usually you in a month: clear names and a line of comment where you did something non-obvious. And when you work with money in shillings, remember that decimal arithmetic on floating-point numbers is approximate - fine for a rough total, not for anything anyone is going to reconcile.',
  practice_activity = 'Write a program that asks for a price and a quantity, converts both properly, and prints a formatted total in shillings. Then give it a non-numeric input and watch it fail. Finally move the VAT rate into a named constant at the top and confirm changing one line changes the result.',
  knowledge_check = '[{"question": "What type does input from a person arrive as?", "options": ["Text, always, even when they typed a number", "A number if it looks like one", "Whatever the variable was before", "True or false"], "correct_index": 0}, {"question": "Why must a key never be written into your code?", "options": ["Code gets pasted and pushed publicly, and automated scanners find keys within minutes", "It makes the file larger", "It slows the program down", "Python cannot read long strings"], "correct_index": 0}]'::jsonb
where id = '593fdde9-a976-4b3c-bc35-7b51c5b7d177';

-- Loops and Iterations - For/While Loops
update public.lessons set
  learning_objectives = array['Repeat work without repeating yourself', 'Choose between the two kinds of loop', 'Avoid the loops that never end'],
  notes = 'A loop repeats a block of code. It is the point at which programming starts saving real time, because the difference between doing something to five items and to five thousand becomes one number.

THE TWO KINDS, and the choice is simple:
A FOR LOOP runs once for each item in a collection - each row, each file, each name. Use it whenever you know what you are going through. This is the one you will use most.
A WHILE LOOP runs until a condition stops being true. Use it when you do not know how many times - waiting for valid input, retrying until something works.

THE INFINITE LOOP is the classic while-loop failure: the condition never becomes false because nothing inside changes it. If your program hangs, that is almost always why. Make sure something inside the loop moves toward the exit.

BREAK leaves a loop early; CONTINUE skips to the next turn. Both are useful and both make code harder to follow if scattered, so use them where they genuinely simplify.

LOOPING OVER A COLLECTION DIRECTLY rather than over a count of positions is the more readable Python and avoids a whole class of off-by-one mistakes.

NESTING a loop inside a loop is normal - every row, and every column within it - but be aware that the work multiplies, and three levels deep is usually a sign the problem wants restructuring.

ADDITION BEYOND THE VIDEO - where loops earn their keep in the work you are likely to be paid for. THE REAL USE IS DOING ONE TEDIOUS THING TO MANY ITEMS: renaming two hundred files, pulling a figure out of every row of an exported statement, sending the same formatted message to a list, checking every entry for a missing field. That is the shape of nearly all beginner automation work here, and it is worth recognising as soon as you can write a loop. Two cautions. PRINT SOMETHING INSIDE A LONG LOOP so you can see progress, because a program that appears frozen is usually working and you cannot tell. And when a loop touches something real - sending a message, writing a file, calling a service - TEST IT ON THREE ITEMS BEFORE RUNNING IT ON THREE THOUSAND, because a loop is equally good at doing the wrong thing at scale.',
  practice_activity = 'Write a for loop that goes through a list of prices and totals them, and a while loop that keeps asking for input until the person types a number. Then write a loop that renames or processes a real folder of files - but run it on a copy of three files first and check the result before letting it near the rest.',
  knowledge_check = '[{"question": "When should a while loop be used instead of a for loop?", "options": ["When you do not know how many times it should run", "When the collection is large", "When the code is nested", "When performance matters"], "correct_index": 0}, {"question": "What should you do before running a loop that touches real files or messages?", "options": ["Test it on three items, because a loop is equally good at doing the wrong thing at scale", "Add more comments", "Convert it to a while loop", "Increase the recursion limit"], "correct_index": 0}]'::jsonb
where id = '88b76055-c1dc-486d-ac63-d3021efdbb95';

-- Learn Python - Full Course for Beginners
update public.lessons set
  learning_objectives = array['Work through a long course video without losing the thread', 'Consolidate everything from Modules 1 and 2', 'Build the habit that separates watching from learning'],
  notes = 'This is a full-length course in one video. WATCH IT IN PARTS, over several sessions, with the editor open beside it - streaming several hours in one sitting is expensive on a bundle and you will retain almost none of it. Download it on wifi if you can and work through a chapter at a time.

NAVIGATE BY CHAPTER, not by time. The description lists the sections; work through the ones covering what you have already met - setup, variables, types, input, conditionals, loops - and you will find the same ground explained differently, which is exactly what consolidates it.

TYPE EVERY EXAMPLE YOURSELF. Do not copy and paste, and do not just watch. The muscle of programming is in the typing, the typos and the fixing, and watching someone else program produces a comfortable illusion of understanding that collapses the moment you face a blank file.

PAUSE AND PREDICT. Before the presenter runs anything, say aloud what the output will be. Being wrong is the single most useful thing that can happen to you here, because it locates exactly what you had misunderstood.

BREAK IT ON PURPOSE. After each example works, change something and see what error appears. Collecting errors deliberately is how you stop fearing them.

DO NOT WAIT UNTIL THE END TO BUILD SOMETHING. After the loops chapter you already know enough to write something genuinely useful.

ADDITION BEYOND THE VIDEO - how to actually finish a long course, because most people do not. SET A FIXED SMALL SESSION - forty minutes, three times a week, one chapter - rather than intending to do it all on Saturday, since the Saturday plan collapses the first weekend something happens. KEEP A FILE OF YOUR OWN NOTES AND SNIPPETS as you go, written in your words, because it becomes the thing you actually consult afterwards and the video does not. And WATCH THE DATA COST: download once rather than streaming twice, and prefer working offline in the editor between sessions, which is where the learning happens anyway. If your machine cannot run the tools, Module 1''s browser notebook route works for everything in this course.',
  practice_activity = 'Work through the chapters covering what you already know, typing every example rather than pasting, pausing to predict each output before it runs. Keep your own notes file as you go. Then, after the loops chapter, stop and write one small program of your own without following anybody.',
  knowledge_check = '[{"question": "Why type every example rather than watching?", "options": ["Watching produces a comfortable illusion of understanding that collapses at a blank file", "It is faster", "Copying introduces errors", "The video cannot be paused"], "correct_index": 0}, {"question": "What is the most useful thing that can happen when you predict an output?", "options": ["Being wrong, because it locates exactly what you had misunderstood", "Being right, which confirms progress", "Matching the presenter''s timing", "Finishing the chapter sooner"], "correct_index": 0}]'::jsonb
where id = '65131a5e-ed91-43d4-bab1-4c0e80db0a78';

-- Object-Oriented Programming in Python
update public.lessons set
  learning_objectives = array['Explain what a class is and what problem it solves', 'Write a simple class and use it', 'Judge honestly when you need this and when you do not'],
  notes = 'A class is a template that bundles data and the things you do to that data. An object is one thing made from that template. A class called Student holds a name and a list of marks; each actual student is an object.

THE PARTS: the initialiser, which runs when an object is created and sets its starting values; attributes, which are the data belonging to that object; and methods, which are functions belonging to it.

WHAT PROBLEM IT SOLVES: when you find yourself carrying four related variables around together and passing them into every function, those four things want to be one object. That is the honest trigger for reaching for a class, and it is a feeling you will have before you have the vocabulary for it.

INHERITANCE lets one class build on another. It is genuinely useful and it is also where beginners over-engineer enthusiastically, building five layers of classes for a program that needed a list and a loop.

YOU WILL MEET CLASSES LONG BEFORE YOU WRITE THEM. Every library you use is built from them, so understanding what a class is makes documentation readable, which is most of the benefit at this stage.

ADDITION BEYOND THE VIDEO - the honest position on whether you need this, because courses present it as the natural next step and for most learners here it is not. NEARLY ALL THE PYTHON WORK YOU ARE LIKELY TO BE PAID FOR IN YOUR FIRST YEAR - cleaning an exported statement, automating a monthly report, scraping a page, renaming files, pulling figures out of a spreadsheet - needs functions, loops and dictionaries and never needs you to write a class. Learn enough to READ code that uses them, which is this lesson, and do not delay a project waiting to feel ready. Second, WHERE IT DOES PAY OFF is anything that grows: a script that has become four hundred lines with related values passed everywhere is asking for a class, and recognising that moment is the skill. Third, if you are heading toward employment rather than freelancing, EMPLOYERS DO ASK ABOUT THIS in interviews, so understand it properly even if your own projects do not need it - which is a perfectly good reason to learn something.',
  practice_activity = 'Write one small class - a Student with a name and marks, and a method that returns the average - and create three objects from it. Then take a script you have already written that carries several related variables around and rewrite it using a class. Decide honestly whether the second version is actually better, and write down why.',
  knowledge_check = '[{"question": "What is the honest trigger for reaching for a class?", "options": ["Carrying several related variables around together and passing them into every function", "Having more than a hundred lines", "Needing to use a library", "Starting a new project"], "correct_index": 0}, {"question": "What does most beginner-paid Python work need?", "options": ["Functions, loops and dictionaries - rarely a class you wrote yourself", "Inheritance hierarchies", "Custom classes for each data type", "Object-oriented design throughout"], "correct_index": 0}]'::jsonb
where id = 'eec5f07f-5032-48a8-bcd0-ed01cab20470';

-- Handling Errors with Try/Except
update public.lessons set
  learning_objectives = array['Catch specific errors rather than everything', 'Use else and finally correctly', 'Decide when an error should be allowed to stop the program'],
  notes = 'Module 4 covered the basic shape: try something, catch the failure, carry on. This lesson is the part that separates code that merely survives from code you can trust.

CATCH SPECIFIC EXCEPTIONS, not everything. A bare except swallows every failure including the ones you needed to know about - a typo in a variable name, a missing file, an interrupted program - and turns a clear error into a silent wrong answer. Name the error you expect: the value that would not convert, the file that was not there, the connection that failed.

THE FULL SHAPE: TRY the risky thing; EXCEPT each specific failure with a sensible response; ELSE for what should happen only if nothing failed; FINALLY for what must happen either way, such as closing a file.

DO NOT CATCH WHAT YOU CANNOT HANDLE. If the program genuinely cannot continue without that file, letting it stop with a clear message is better than continuing with nothing and producing a plausible, wrong result three steps later. Catching an error you cannot do anything about is how a small fault becomes an unexplained one.

RAISE YOUR OWN when a caller has given you something impossible. A function handed a negative quantity should say so loudly rather than quietly returning a strange number.

SAY SOMETHING USEFUL. An except block printing an error occurred helps nobody. Print what was being attempted, with the value that broke it.

ADDITION BEYOND THE VIDEO - what this matters for in the work you will actually do. AUTOMATION SCRIPTS FAIL ON REAL DATA, always, and the failure is usually one bad row in three thousand: a blank where a number should be, a date in the wrong format, a name with a stray character. The right pattern is to catch that row, RECORD IT SOMEWHERE WITH ENOUGH DETAIL TO FIND IT, and continue - so you end with the work done and a short list of what needs a human. A script that stops dead on row 412 wastes the run; one that silently skips bad rows is worse, because nobody knows what is missing. Second, WHEN A SCRIPT TOUCHES SOMETHING THAT CANNOT BE UNDONE - sending messages, writing over files, moving money - be conservative: check first, act second, and log what you did, because an error recovered from badly in that situation is not a bug, it is a real problem for a real person.',
  practice_activity = 'Take a script that reads a file of real, messy data and make it survive the bad rows: catch the specific errors, record each failure with its row number and the value that broke it, and continue. At the end, print how many rows worked and write the failures to a file. Then check a deliberately broken row appears there.',
  knowledge_check = '[{"question": "Why is a bare except dangerous?", "options": ["It swallows failures you needed to know about and turns a clear error into a silent wrong answer", "It is slower", "It cannot be nested", "It ignores the finally block"], "correct_index": 0}, {"question": "What should a script do with one bad row in three thousand?", "options": ["Record it with enough detail to find it, and continue, so a human gets a short list", "Stop immediately", "Skip it silently", "Substitute a default value"], "correct_index": 0}]'::jsonb
where id = 'd54d10d2-736e-4e2a-ad20-4a5be2f3b491';
