-- Auto-generated by scripts/curriculum/build-backfill-sql.py -- do not
-- hand-edit; regenerate from the source plan JSON instead.
--
-- UPDATE only, addressed by lesson id. No lesson is inserted, deleted or
-- re-parented and no id changes, so lesson_progress is untouched.

-- Best Podcast Equipment for Beginners (Under $100!)
update public.lessons set
  learning_objectives = array['Know which piece of kit actually changes how you sound', 'Start recording with what you already own', 'Spend money in the right order, if you spend it at all'],
  notes = 'THE ROOM MATTERS MORE THAN THE MICROPHONE. This is the single most useful fact in the whole course and almost no equipment video leads with it. A cheap microphone in a soft, quiet room beats an expensive one in a bare room with a tiled floor, every time. Hard surfaces bounce your voice back into the mic and that echo cannot be removed afterwards by any software.

WHAT THE VIDEO IS FOR: understanding the categories - USB versus XLR, dynamic versus condenser, what a pop filter and a boom arm actually do. Watch it for the vocabulary, not the shopping list.

DYNAMIC OR CONDENSER, briefly. A condenser hears everything, including the room, the fan and the street. A dynamic hears mostly what is directly in front of it. In an untreated room in a noisy place, a DYNAMIC microphone is the more forgiving choice, which is the opposite of what most beginner videos recommend.

USB IS THE RIGHT START. It plugs into a laptop and works. XLR needs an audio interface as well, which is a second purchase and a second thing to go wrong.

ADDITION BEYOND THE VIDEO - what this actually costs and looks like here.

THE PRICES IN THIS VIDEO ARE IN DOLLARS AND THEY ARE NOT THE PRICE YOU WILL PAY. A hundred-dollar microphone is roughly thirteen thousand shillings before shipping, and imported electronics can attract duty and handling on arrival, so the real landed cost is often half again. Price it locally before ordering, and ask whether the seller has it in Nairobi already.

YOU CAN START WITH THE PHONE IN YOUR POCKET, and you should. A modern phone records perfectly acceptable speech through its own microphone when you are in a soft, quiet room and holding it a hand-span away, slightly off to the side of your mouth. Free recording apps exist on both Android and iPhone. Every excuse about equipment is a reason not to start, and starting is the only thing that matters in the first month.

TREAT THE ROOM FOR NOTHING. Record in the room with the most soft material in it - a bedroom with a mattress, curtains and clothes beats a sitting room with a sofa, which beats an office. Hang a heavy blanket on the wall you face. Standing inside a wardrobe full of clothes, phone in hand, genuinely sounds better than a studio-priced microphone in an empty room. Avoid rooms with an iron-sheet roof when it might rain.

THE ORDER TO SPEND, if you spend at all: first nothing, and fix the room. Then a pop filter or a cheap foam windscreen, which stops the thump on P and B sounds. Then closed-back headphones, so you can hear problems while recording. THE MICROPHONE COMES LAST, not first.',
  practice_activity = 'Record the same sixty seconds of speech three times without buying anything: once in your normal room, once in the softest room in the house, and once standing inside a wardrobe or facing a hung blanket. Listen to all three on headphones and write down which is quietest and which has the least echo. That is your recording spot from now on.',
  knowledge_check = '[{"question": "What makes the biggest difference to how a beginner recording sounds?", "options": ["The room - soft and quiet beats an expensive microphone in a bare room", "The microphone, which should be the first purchase", "The editing software", "Recording in stereo rather than mono"], "correct_index": 0}, {"question": "In an untreated, noisy room, which microphone type is more forgiving?", "options": ["A dynamic microphone, because it mostly hears what is in front of it", "A condenser, because it is more sensitive", "Either - the type makes no difference", "A stereo microphone"], "correct_index": 0}]'::jsonb
where id = '73739af0-9a1b-4c7c-a441-8f9e6da10f51';

-- How to Get Started in Voice Over for Beginners: Complete Guide
update public.lessons set
  learning_objectives = array['Understand what voice-over work actually is and who buys it', 'Judge honestly which part of the market is open to you', 'Take the first step that does not cost money'],
  notes = 'VOICE-OVER IS NOT ONE MARKET, it is several, and they want completely different things. Commercial adverts, e-learning and corporate training, explainer videos, audiobooks, documentary narration, phone systems, and character work for animation and games. The skills overlap; the buyers do not.

WHAT THE JOB ACTUALLY IS: reading somebody else''s words, in a specified tone, cleanly, on time, and to a technical spec. It is much less about having a beautiful voice than beginners expect, and much more about being easy to work with, taking direction without sulking, and delivering a clean file when you said you would.

READING ALOUD IS A SKILL YOU CAN PRACTISE TODAY, free. Read a paragraph, record it, listen back, notice where you rushed, where you trailed off, where you sounded like you were reading rather than talking. Most beginners sound like they are reading. Fixing that is the single biggest improvement available to you and it costs nothing.

ADDITION BEYOND THE VIDEO - the honest market picture from here, which no international video will give you.

THE GLOBAL MARKET IS ACCENT-SENSITIVE and you should know this before you spend money. Most English-language commercial and audiobook work specifies an American or British accent, and competing directly there as a Kenyan speaker is a hard road, particularly at the start. That is a fact about the market, not about your ability.

THE MARKETS GENUINELY OPEN TO YOU ARE REAL AND THEY ARE NEARER THAN YOU THINK. Kenyan English, Swahili and Sheng are in demand for local radio and television adverts, for the recorded phone menus that every bank, sacco and insurer needs, for NGO and government training material, for church and school content, for YouTube channels aimed at East Africa, and for e-learning being localised for this region. An international agency cannot serve that and a Nairobi production house needs it constantly. Start where you have the advantage, not where you have the handicap.

CLIENTS ARE NEARER TOO: radio stations, small production houses, advertising agencies, church media teams, and the growing number of YouTube channels here that need a narrator. These are people you can actually reach.

WHAT YOU DO NOT NEED YET: a home studio, an agent, a paid course, or a coach. What you do need, in this order, is a quiet spot, the habit of reading aloud daily, and eventually about sixty to ninety seconds of your best recorded work.',
  practice_activity = 'Record yourself reading three different things for one minute each: a news paragraph, a radio advert script you write yourself, and an explanation of something you know well. Listen back and write one honest sentence about each. Then read the same three again, trying to talk rather than read, and compare.',
  knowledge_check = '[{"question": "What is voice-over work mostly about?", "options": ["Reading somebody else''s words cleanly, in the tone asked for, on time and to spec", "Having an unusually beautiful voice", "Owning professional recording equipment", "Being able to imitate many accents"], "correct_index": 0}, {"question": "Which part of the market is most open to a beginner based in Kenya?", "options": ["Local-language and Kenyan-English work - radio, phone menus, NGO training, regional channels", "American-accent audiobook narration", "British-accent television commercials", "Character work for international animation"], "correct_index": 0}]'::jsonb
where id = 'a84ec9b4-2272-4538-8692-2d44d2bc49bf';

-- Audacity Beginners Guide | Editing Your Podcast
update public.lessons set
  learning_objectives = array['Edit a recording without destroying the original', 'Do the four edits that account for most of the work', 'Export a file at a size people can actually download'],
  notes = 'AUDACITY IS FREE AND RUNS ON AN OLD LAPTOP, which is why this course uses it. Download it only from the official site - the search results for popular free software are full of bundled rubbish.

WORK ON A COPY, ALWAYS. Record, save the raw file, and only then edit. Audacity can be told to undo, but a saved original is the only real protection, and you will at some point delete the wrong thing and save it.

THE FOUR EDITS THAT DO MOST OF THE WORK:
ONE, CUT THE DEAD AIR at the start and end, and the long gaps where nothing happens.
TWO, CUT THE MISTAKES - the false starts, the coughs, the phone ringing.
THREE, NOISE REDUCTION, using a sample of silence to tell Audacity what the noise sounds like.
FOUR, NORMALISE OR AMPLIFY so the whole thing sits at a sensible, consistent volume.

RECORD TEN SECONDS OF SILENCE AT THE START OF EVERY SESSION and do not skip it. That is your room tone, and noise reduction needs it to work. Without it you are guessing.

DO NOT OVERDO NOISE REDUCTION. Past a modest setting it makes voices sound like they are underwater or transmitted by radio, and that artefact is worse than the hiss you were removing. A little hiss is normal and listeners forgive it; a watery, processed voice they do not.

CUT ON THE BREATH. The natural place to make an edit is in the gap where the speaker inhales, because the join is invisible there. Cutting mid-word or mid-breath is what makes amateur edits obvious.

ADDITION BEYOND THE VIDEO - the settings that matter when data costs money.

EXPORT SPEECH AS MONO, NOT STEREO. One voice does not need two channels, and mono halves the file size for no loss at all. This is the easiest saving available and almost nobody does it.

EXPORT AS MP3 AT 64 TO 96 KBPS FOR SPEECH. A WAV file of a forty-minute episode runs to hundreds of megabytes; the same episode as a mono MP3 at 64kbps is a small fraction of that and sounds the same to a listener on a phone. Your listeners pay for their data and so do you when you upload.

SAVE OFTEN AND EXPORT IN PARTS if power is unreliable. Audacity holds unsaved work in a temporary folder and a power cut mid-session can cost you an hour. Record long interviews in several shorter takes for the same reason - a corrupted file loses one take instead of everything.

KEEP TWO COPIES of anything a client has paid for, in two different places.',
  practice_activity = 'Take one of your own recordings into Audacity. Save the raw file untouched first. Then cut the dead air and the mistakes, run noise reduction using ten seconds of room tone, and normalise it. Export it twice - once as stereo WAV and once as mono MP3 at 64kbps - and compare the file sizes and how they sound on a phone.',
  knowledge_check = '[{"question": "Why record ten seconds of silence at the start of a session?", "options": ["It gives noise reduction a sample of the room tone so it knows what to remove", "It gives the recording software time to start properly", "It marks the beginning of the file", "It is needed before you can normalise"], "correct_index": 0}, {"question": "How should a speech-only episode be exported?", "options": ["Mono MP3 at around 64 to 96 kbps, which halves the size with no real loss", "Stereo WAV, for the best quality", "Stereo MP3 at the highest bitrate available", "Whatever the default setting is"], "correct_index": 0}]'::jsonb
where id = '696608fa-4166-4b4e-b3fe-2e030c7078eb';

-- How to Use a Mic Like a Pro (Microphone Technique)
update public.lessons set
  learning_objectives = array['Position yourself so the recording is clean before any editing', 'Stop the three noises that ruin most beginner takes', 'Set a level that neither clips nor disappears'],
  notes = 'MOST BAD AUDIO IS A POSITIONING PROBLEM, not an equipment problem, and positioning is free to fix.

DISTANCE: about a hand-span from the microphone, and consistent. Too far and you record the room instead of yourself. Too close and every P becomes a thump and the recording booms. Consistency matters as much as the distance itself, so if you move about while you talk, that is the first habit to break.

SPEAK ACROSS THE MICROPHONE, NOT INTO IT. Angle it slightly off to one side of your mouth so your breath passes the capsule rather than hitting it. This alone removes most popping, before any pop filter.

KNOW WHICH SIDE IS THE FRONT. Many beginners talk into the top of a side-address microphone and wonder why it sounds thin and distant. Check before you record, not after.

THE THREE NOISES THAT RUIN TAKES: the desk - every tap, every bump, travels straight up a stand into the mic, so use something soft under it and keep your hands still. Your clothes - anything that rustles will be heard. And plosives, the P and B thumps, which positioning and a windscreen fix.

LEVELS: aim for the meter to sit around two-thirds up, peaking well below the top. If it touches the top it CLIPS, and clipping is permanent damage that no software can repair. Recording a little too quiet is fixable; recording too loud is not. When unsure, go quieter.

ADDITION BEYOND THE VIDEO - the noise floor where you actually live.

RECORD AT THE QUIETEST HOUR YOU HAVE, and for most people that is early morning, before traffic and before the compound wakes up. An hour chosen well beats any amount of software cleanup.

THE PREDICTABLE LOCAL NOISES to plan around: matatu and boda traffic, which means facing away from the road and closing windows; a fridge or fan, which you should switch off and remember to switch back on; rain on an iron-sheet roof, which cannot be salvaged at all, so simply do not record through it; roosters and dogs at dawn; and mains hum from a nearby socket or charger, which you can often remove just by moving the cable away from the microphone.

DO A TWENTY-SECOND TEST AND LISTEN TO IT ON HEADPHONES BEFORE THE REAL TAKE, every single time. Discovering a buzz after recording forty minutes is a whole evening lost, and it happens to everyone exactly once before they adopt this habit.',
  practice_activity = 'Record the same paragraph four times, changing one thing each time: at arm''s length, at a hand-span, speaking directly into the mic, and speaking across it. Listen on headphones and write down which sounds best and why. Then run a twenty-second test in your usual spot and identify every background noise you can hear in it.',
  knowledge_check = '[{"question": "Why speak across the microphone rather than straight into it?", "options": ["Your breath passes the capsule instead of hitting it, which removes most popping", "It makes the voice sound louder", "It reduces the file size", "It stops the microphone overheating"], "correct_index": 0}, {"question": "What happens if the recording level touches the top of the meter?", "options": ["It clips, which is permanent damage no software can repair", "It is automatically reduced by the software", "Nothing - that is the ideal level", "The recording becomes stereo"], "correct_index": 0}]'::jsonb
where id = '33b1a37f-2709-4206-b54d-02352ec37fd4';

-- Podcast Compression & EQ in Audacity
update public.lessons set
  learning_objectives = array['Understand what compression and EQ each actually do', 'Apply a restrained, repeatable chain to a voice', 'Know when to stop processing'],
  notes = 'THESE TWO TOOLS ARE WHERE BEGINNERS DO THE MOST DAMAGE, so the guiding rule is: the least that works.

COMPRESSION EVENLY LOUD, NOT LOUDER. It quietly turns down the loudest moments so that the whole thing can then be raised. The result is a voice that stays audible when somebody listens on a phone speaker in a matatu, instead of disappearing in the quiet parts and startling them in the loud ones. That is the entire point, and it is a real one for your audience.

EQ IS SUBTRACTIVE FIRST. Cutting what you do not want almost always sounds better than boosting what you do. The two cuts worth knowing: a HIGH-PASS FILTER rolling off everything below roughly 80Hz, which removes rumble, traffic and desk thumps you cannot even consciously hear but which eat headroom; and a gentle dip around 200 to 400Hz if the voice sounds boxy or muddy. Boosting the top end to add air is a last resort and mostly adds hiss.

THE ORDER MATTERS: clean first, then EQ, then compression, then a final normalise. Compressing before you have removed the rumble just makes the rumble louder along with everything else.

STOP WHEN IT SOUNDS LIKE A PERSON. The test is not whether it sounds impressive on your headphones; it is whether it still sounds like the person talking. Over-compressed voices breathe unnaturally and sound tiring over forty minutes. Over-EQ''d voices sound like a telephone.

SAVE YOUR SETTINGS AND REUSE THEM. Once you have a chain that suits your voice and your room, write the numbers down and apply the same thing every episode. Consistency between episodes matters more to a listener than perfection in any one of them, and it turns an hour of fiddling into two minutes.

ADDITION BEYOND THE VIDEO.

CHECK IT ON A CHEAP PHONE SPEAKER, not only on headphones. That is what most of your audience will actually use, and a mix that sounds rich on headphones can be thin and unintelligible on a phone. If you have to choose, favour the phone.

PROCESSING CANNOT FIX THE THINGS THAT MATTER MOST. Echo from a bare room, a clipped take, and rain on an iron roof are all permanent. No amount of compression or EQ repairs them. Every hour you spend on the recording end saves three at this end, which is why the room lesson came first.

A NOTE ON MUSIC: if you add an intro, use music that is genuinely licensed for the purpose and keep a copy of the licence. Commercial music on a podcast is a real legal risk and platforms do act on it.',
  practice_activity = 'Take one edited recording and process it twice. Once with restraint - a high-pass filter, a gentle compression, a final normalise. Once deliberately overdone, with heavy compression and big EQ boosts. Listen to both on headphones and then on a phone speaker, and write down which you would actually publish and why.',
  knowledge_check = '[{"question": "What does compression actually do for a podcast listener?", "options": ["It evens out loud and quiet moments so the voice stays audible in a noisy place", "It makes the file smaller", "It removes background noise", "It raises the pitch of the voice"], "correct_index": 0}, {"question": "Which problems can processing NOT fix?", "options": ["Room echo, a clipped take and rain noise - all of them are permanent", "Uneven volume between speakers", "Low-frequency rumble", "A voice that sounds slightly muddy"], "correct_index": 0}]'::jsonb
where id = '269f0252-8a26-45c9-aa99-0551dba2f0dd';

-- Voice-Over Microphone Techniques
update public.lessons set
  learning_objectives = array['Use the performance techniques that separate voice-over from ordinary speech', 'Deliver the same line several ways on request', 'Keep a long session consistent from start to finish'],
  notes = 'VOICE-OVER IS A PERFORMANCE, and that is the difference from the podcast technique in module 2. A podcast wants you to sound like yourself talking. A voice-over wants a specific, controlled, repeatable delivery that somebody else has specified.

SMILE WHEN THE SCRIPT IS WARM. It genuinely changes the sound, and listeners hear it without knowing why. Equally, the brief may call for flat and factual, and then you must take the smile out. Being able to switch on request is the skill being paid for.

MARK UP THE SCRIPT BEFORE YOU RECORD: underline the word in each sentence that carries the meaning, mark where you will breathe, and slash where you will pause. Reading cold is why beginners sound like they are reading. Ninety seconds of marking saves twenty minutes of retakes.

PACE AND PAUSE. Beginners rush, because silence feels like a mistake while you are in it. It is not - a pause is how a listener is given a moment to absorb the point. Deliberately slow down and leave gaps; on playback it will sound normal rather than slow.

GIVE THEM OPTIONS. When you record a line, record it three ways - warm, neutral, energetic - and hand over all three. Clients very often cannot say what they want until they hear it, and being the person who anticipated that is how you get asked back.

PROTECT YOUR VOICE ON A LONG SESSION: room-temperature water, no dairy beforehand, and a real break every forty minutes. A tired voice drops in pitch and energy, and an episode that starts bright and ends flat has to be re-recorded.

ADDITION BEYOND THE VIDEO - the two things that lose the job after the recording is fine.

MATCH THE TECHNICAL SPEC EXACTLY. A client who asks for mono WAV at 48kHz with the ends trimmed and no processing means exactly that, and sending a processed stereo MP3 marks you as an amateur no matter how good the read is. Read the spec twice and name the file the way they asked.

KEEP EVERY SESSION CONSISTENT. Same spot, same distance, same settings, and a note of them. Clients come back weeks later asking for one line to be re-recorded and dropped into the finished piece, and if your setup has changed that line will not match, which means redoing the whole job for free. Write your setup down today - the distance, the room, the levels - and keep it with the project.

FINALLY, RECORD A SLATE at the head of the file: your name and the job, spoken plainly. It costs three seconds and it stops your work being confused with somebody else''s in a producer''s folder.',
  practice_activity = 'Take a thirty-second script and mark it up - the key word in each sentence, the breaths, the pauses. Record it three ways: warm, neutral and energetic. Listen back and check that all three are genuinely different. Then write down your exact setup - room, distance, levels - and keep that note for the next session.',
  knowledge_check = '[{"question": "Why record a line three different ways?", "options": ["Clients often cannot say what they want until they hear it, so options get you asked back", "It gives you a backup if one file is corrupted", "It is required by most platforms", "It makes the session longer and therefore better paid"], "correct_index": 0}, {"question": "Why write down your exact recording setup?", "options": ["Clients return later for one re-recorded line, and it will not match if your setup changed", "It is needed to export the file", "It helps you remember which microphone you own", "Platforms ask for it when you sign up"], "correct_index": 0}]'::jsonb
where id = '2038e128-fa35-42e3-b6d2-d683389c1dfd';
