-- Auto-generated by scripts/curriculum/build-backfill-sql.py -- do not
-- hand-edit; regenerate from the source plan JSON instead.
--
-- UPDATE only, addressed by lesson id. No lesson is inserted, deleted or
-- re-parented and no id changes, so lesson_progress is untouched.

-- Overcoming Your Fear of Public Speaking
update public.lessons set
  learning_objectives = array['Recognise speaking fear as ordinary arousal rather than a defect', 'Move your attention from how you are doing to what the audience needs', 'Build tolerance by speaking in small, low-stakes settings on purpose'],
  notes = 'ALMOST EVERYONE IS AFRAID OF THIS, including people you have watched speak well. What separates them is not that the fear went away. It is that they learned what to do while it is happening.

WHAT YOUR BODY IS DOING IS NOT MALFUNCTIONING. A faster heart, shallow breath, dry mouth, shaking hands — that is your body releasing energy because it has judged the situation as important. The same response happens before a race, and athletes call it readiness. The physical sensations of fear and excitement are nearly identical; what differs is the sentence you attach to them. Practise attaching a different one: not I am terrified, but I am ready.

THE REAL MISTAKE IS WHERE YOUR ATTENTION POINTS. Speakers who suffer most are thinking about themselves the whole time — how do I look, was that a stammer, are they bored. Attention pointed at yourself finds faults, because that is what self-examination does. Point it outward instead: what does this room actually need to understand, and are they getting it? You cannot monitor yourself and serve an audience at the same time, and the second job is the one you were asked to do.

THEY CANNOT SEE MOST OF WHAT YOU FEEL. The pounding heart, the churning stomach, the certainty that your voice is shaking — these are enormous from inside and nearly invisible from six feet away. This is worth knowing precisely because you will not believe it in the moment.

PREPARE THE OPENING MORE THAN ANYTHING ELSE. Fear peaks in the first thirty seconds and drops once you are speaking. Knowing your first two sentences cold — not the whole talk, the first two sentences — carries you across the part that frightens you into the part where you are simply talking.

THEN BUILD TOLERANCE DELIBERATELY. Fear shrinks by repetition, not by insight. Ask a question at a meeting. Speak up in church or at a community gathering. Record a two-minute voice note explaining something and listen back. Give a toast. Each one is small enough to survive and real enough to count, and after enough of them the large occasion is no longer your first.

ONE LAST THING WORTH SAYING PLAINLY. Speaking in a second or third language adds a layer that native speakers never think about, and it is not a shortcoming. Slow down slightly, use shorter sentences, and let a pause do the work while you find a word. Audiences wait far more patiently than the voice in your head predicts.',
  practice_activity = 'Speak for two minutes, today, with a recording running. Pick something you already know well and explain it as though to one person who does not. Do not script it and do not restart when you stumble. Then listen back once, and write down two things: one thing that sounded better than it felt, and one specific thing to change next time. Almost everybody discovers the same thing on the first listen — the nerves they were certain would be obvious are not audible. Repeat this three times in the coming week.',
  knowledge_check = '[{"question": "What does this lesson say separates confident speakers from nervous ones?", "options": ["They learned what to do while the fear is happening, not that the fear disappeared", "They genuinely do not feel fear before speaking", "They memorise every word of the talk in advance", "They only speak on subjects they have spoken on before"], "correct_index": 0}, {"question": "Where should your attention go while speaking?", "options": ["Outward, to whether the audience is understanding you", "Inward, to monitor your voice and posture continuously", "On the exact wording you planned, so none is lost", "On the people who look least interested, to win them over"], "correct_index": 0}]'::jsonb
where id = 'cb2a697d-3c0c-4abe-a47f-c8a4e1c04579';

-- 5 Public Speaking Body Language Tips
update public.lessons set
  learning_objectives = array['Stand and move in a way that steadies you rather than distracts', 'Use gesture and eye contact to hold attention in a room or on a call', 'Let silence work instead of filling every gap with sound'],
  notes = 'BODY LANGUAGE IS NOT DECORATION. Before your first sentence lands, a room has already decided whether you seem comfortable — and comfort is contagious in both directions. An audience watching somebody who looks trapped cannot relax enough to listen.

START BY STANDING STILL. The commonest beginner habit is drifting: rocking, shifting weight, pacing without reason. Plant both feet, weight even, and stay there for your opening. Stillness reads as certainty, and it also steadies you, because a moving body keeps telling the nervous system that something is wrong. Move later, on purpose, when you change subject — movement that marks a transition is useful, movement that leaks anxiety is not.

LET YOUR HANDS BE SEEN AND LET THEM WORK. Hands in pockets, gripped behind the back or clamped to a lectern all read as hidden. Gesture within the frame of your body, and let gestures mean something: show a size, separate two ideas into two hands, count three points on three fingers. A gesture that matches your words makes you easier to follow. A gesture repeated without meaning becomes a tic the audience starts watching instead of listening.

EYE CONTACT IS A SERIES OF CONVERSATIONS, NOT A SWEEP. Rest on one person for a full thought, then move to another. Scanning the room continuously makes you look like you are searching for an exit. In a large or dark room, look at sections rather than faces; nobody can tell the difference.

ON A VIDEO CALL, THE RULES CHANGE IN ONE SPECIFIC WAY. Eye contact means looking at the CAMERA, not at the faces on screen — which feels wrong and looks right. Raise the laptop so the lens is at eye height, sit far enough back that your hands are visible, and put the light in front of you rather than behind. If your connection is unreliable, say so at the start and keep going when the picture freezes; the audio usually survives, and a speaker who apologises for the bandwidth every thirty seconds is more disruptive than the bandwidth.

AND USE SILENCE. A pause after an important sentence gives it room to land and gives you room to breathe. It feels enormous to you and reads as composure to everyone else. Most filler sounds — er, ah, so, you know — are pauses that somebody was afraid to leave empty.',
  practice_activity = 'Record yourself on video giving a two-minute explanation while standing. Watch it once with the sound OFF. With no words to follow you will see exactly what your body is doing: the rocking, the hidden hands, the repeated gesture, the wandering eyes. Write down the single most distracting habit and record again, changing only that one thing. Then do the same on a video call setup — camera at eye height, light in front — and check whether it looks like you are meeting the viewer''s eye.',
  knowledge_check = '[{"question": "Why does this lesson recommend standing still during your opening?", "options": ["Stillness reads as certainty and steadies you, while aimless movement leaks anxiety", "Moving while speaking is considered rude in most audiences", "It stops the microphone from picking up footsteps", "It makes the talk look more rehearsed"], "correct_index": 0}, {"question": "On a video call, where should you look to create eye contact?", "options": ["At the camera lens, even though looking at the faces on screen feels more natural", "At the faces on screen, which is what the viewer sees", "At your own thumbnail image, to check your framing", "Slightly above the screen, so both are in view"], "correct_index": 0}]'::jsonb
where id = '3c0c69e2-0e84-4442-b813-1b94f3d4ef77';

-- How to Structure a Speech
update public.lessons set
  learning_objectives = array['Decide the one thing you want remembered before writing anything', 'Build an opening, a middle of no more than three points, and a real close', 'Outline in points rather than sentences so you can speak instead of recite'],
  notes = 'STRUCTURE IS WHAT MAKES A TALK FOLLOWABLE FROM A SEAT. A reader can go back a paragraph; a listener cannot. Everything here exists to solve that one problem.

BEGIN BY WRITING ONE SENTENCE: if they remember nothing else, they should remember this. Every part of the talk either supports that sentence or comes out. This is the same idea the earlier module called building a talk around one idea, and it is doing the heavy lifting here too — structure without a governing idea is just tidy wandering.

THE OPENING HAS ONE JOB: earn the next two minutes. A specific story, a surprising number, a real question the audience has themselves — any of these work. Do not spend the opening thanking people, apologising for being nervous, or explaining what you are about to explain. Say something worth hearing first; housekeeping can wait.

THE MIDDLE HOLDS AT MOST THREE POINTS. Not because three is magic, but because a listener without notes cannot carry more. Each point needs its own evidence — an example, a demonstration, a number, a short story — because a point without evidence is an opinion, and a point with an example is remembered. Between points, SIGNPOST: say that was the first of three, here is the second. In writing that would be clumsy; out loud it is the handrail that stops people getting lost.

THE CLOSE IS NOT A SUMMARY. It returns to the one sentence and asks for something: a decision, an action, a change of mind. Land it and stop. Talks that trail off do so because the speaker never decided what the last line was — so decide it, and know it by heart.

OUTLINE IN POINTS, NOT SENTENCES. A full script gets recited, and recitation always sounds like recitation. Five or six phrases on a card let you speak the idea freshly each time, which is what an audience actually responds to. The two exceptions are the first line and the last line, which are worth having word for word.

AND TIME IT OUT LOUD. Speaking takes longer than reading, everybody overruns, and the cut is always made from the middle. Rehearse aloud once with a clock, then cut until it fits with room to spare.',
  practice_activity = 'Take a talk you might really have to give — a project update, a pitch, a speech at a family event — and write the one sentence you want remembered. Under it write no more than three points, and beside each one name the specific example or number that proves it. Write the first line and the last line out in full. Then deliver it aloud against a clock. If it overruns, cut a point rather than speaking faster; two points delivered properly beat three rushed.',
  knowledge_check = '[{"question": "What should the opening of a talk do?", "options": ["Earn the next two minutes with something worth hearing", "Thank the organisers and outline the agenda", "Warn the audience that you are nervous so they make allowances", "Summarise the conclusion so nobody has to wait for it"], "correct_index": 0}, {"question": "Why outline in points rather than writing the talk out in full sentences?", "options": ["A full script gets recited, and recitation sounds like recitation", "Points are faster to write", "Full scripts are harder to time accurately", "Reading from a script is not allowed in most settings"], "correct_index": 0}]'::jsonb
where id = '1fb3fc69-2afb-48ec-b671-7ad697b7e86f';

-- 3 Techniques for Managing Speaking Anxiety
update public.lessons set
  learning_objectives = array['Use breathing that actually lowers arousal rather than raising it', 'Rehearse under conditions close to the real thing', 'Have a plan for the moment your mind goes blank'],
  notes = 'THE FIRST LESSON WAS ABOUT WHAT FEAR IS. THIS ONE IS ABOUT WHAT TO DO IN THE TEN MINUTES BEFORE YOU SPEAK, AND DURING.

BREATHE OUT LONGER THAN YOU BREATHE IN. This is the one physical technique with a clear mechanism: a long exhale slows the heart, and a long inhale speeds it up. So in for four, out for six or eight, for about a minute. The common advice to take a deep breath, done as a big fast inhale, does the opposite of what people want. Do this while waiting, not while walking to the front, so that the effect has arrived before you do.

REHEARSE UNDER CONDITIONS THAT RESEMBLE THE REAL ONES. Practising in your head while lying down prepares you for nothing. Stand up, say the words out loud at full volume, and if you can, rehearse in the actual room or on the actual call platform. Anxiety is largely uncertainty, and every detail you have already lived through is one fewer unknown. If there is a microphone, hold something. If there will be slides, click through them.

HAVE A PLAN FOR GOING BLANK, because it happens to everyone eventually and the panic comes from having no move. The move is this: stop, look at your card or notes, and say a short bridging sentence out loud while you find your place — so, the point I want to leave you with is. Silence for three seconds while you check a note reads as thinking. Apologising, laughing nervously and explaining that you have lost your place is what turns a pause into an incident. Keep a card with your three points on it even when you are sure you will not need it; its real job is to stop you fearing the blank rather than to be read.

TWO SMALLER THINGS THAT HELP MORE THAN THEY SOUND. Arrive early enough to stand where you will speak while the room is still empty. And drink water beforehand, because a dry mouth is the single most common physical complaint and it is largely preventable.

ONE THING TO AVOID: do not try to be calm. Aiming for calm makes every symptom evidence of failure. Aim to be useful while activated, which is achievable and is what experienced speakers are actually doing.',
  practice_activity = 'Try the breathing on its own first, away from any speaking: in for four, out for eight, for one minute, and notice what changes. Then combine all three techniques in one rehearsal — breathe first, deliver a two-minute talk standing and out loud, and deliberately stop halfway, look at your card, say your bridging sentence and continue. Practising the recovery is the point; you are rehearsing the move you will need under pressure so that it is already familiar.',
  knowledge_check = '[{"question": "Which breathing pattern lowers arousal before speaking?", "options": ["A longer exhale than inhale, such as in for four and out for eight", "A large fast inhale held as long as possible", "Rapid shallow breaths to increase oxygen", "Holding the breath until the first sentence"], "correct_index": 0}, {"question": "What is the recommended move when your mind goes blank mid-talk?", "options": ["Stop, check your notes, and say a short bridging sentence while you find your place", "Apologise and explain that you have lost your place", "Keep talking about anything until the thread returns", "Skip to the conclusion and finish early"], "correct_index": 0}]'::jsonb
where id = 'eb7bc10f-7730-45e4-8d6f-453bd1c88809';

-- Presenting Like a Pro: Body Language
update public.lessons set
  learning_objectives = array['Match your delivery to the size and format of the room', 'Vary pace, volume and pitch so the talk does not flatten', 'Handle slides, notes and questions without losing the audience'],
  notes = 'THE BASICS FROM THE EARLIER LESSON — STILLNESS, VISIBLE HANDS, REAL EYE CONTACT, PAUSES — DO NOT CHANGE. What changes at this level is calibration: the same delivery does not work in a boardroom, a hall and a video call.

SCALE TO THE ROOM. In a small room, normal conversational energy is right and anything larger reads as performance. In a hall, gestures must get bigger and slower or they vanish, and you must speak to the back row — not louder so much as more deliberately, with longer pauses, because sound and attention both take longer to travel. On camera, the frame is tight: big gestures leave the shot, and the effective range of your expression is your face and voice.

VARY THE VOICE, BECAUSE MONOTONE IS WHAT LOSES ROOMS, not weak content. Three dials: PACE — slow down for the thing that matters, speed up through context; VOLUME — dropping quieter for one sentence pulls an audience in harder than getting louder; PITCH — ending sentences on a downward tone sounds settled, while ending upward makes every statement sound like a question you are not sure of. You do not need to sound like a broadcaster. You need to not sound the same for twenty minutes.

SLIDES ARE BEHIND YOU, NOT IN FRONT OF YOU. Never read them aloud — an audience reads faster than you speak, so reading slides makes you redundant and slightly irritating. Show, then turn back and talk. Stand to one side, not in front. Blank the screen when you want attention back on you.

QUESTIONS ARE THE PART PEOPLE UNDER-REHEARSE. Listen to the whole question without preparing your answer over it. Repeat or paraphrase it so the room hears it. Answer the question that was asked rather than the one you prepared. And I do not know, I will find out and come back to you is a complete, credible answer — bluffing is the only way to actually lose the room.

FINALLY, EXPECT THE ROOM TO BE MIXED. In many settings here the audience spans languages, seniority and how much background they have. Define a term the first time you use it, keep sentences short, and do not assume the quiet people are lost — or that the confident ones are following.',
  practice_activity = 'Take the same two-minute talk and deliver it three times: once seated as if in a small meeting, once standing as if to a full hall, and once to a camera. Record all three. Watching them back, check one thing per version — in the meeting version, whether the energy is too big; in the hall version, whether gestures are large and slow enough to read from a distance; in the camera version, whether your hands stay in frame. Then have somebody ask you three questions about it, including one you cannot answer, and practise saying so.',
  knowledge_check = '[{"question": "What loses a room most reliably, according to this lesson?", "options": ["A monotone delivery that never varies in pace, volume or pitch", "Content that is too advanced for the audience", "Speaking for longer than fifteen minutes", "Using slides at all"], "correct_index": 0}, {"question": "You are asked a question you cannot answer. What is the best response?", "options": ["Say you do not know, and that you will find out and come back to them", "Give your best guess confidently so you do not look unprepared", "Redirect to a point you did prepare", "Say the question is outside the scope of the talk"], "correct_index": 0}]'::jsonb
where id = '150794f8-accb-46c8-83d0-a98ae6fa1abd';

-- The 60-Second Pitch That Gets You Hired
update public.lessons set
  learning_objectives = array['Build a sixty-second introduction around a problem you solve', 'Show proof instead of claiming adjectives about yourself', 'End with a specific, easy next step rather than a vague hope'],
  notes = 'THIS IS WHERE SPEAKING TURNS INTO INCOME. The sixty-second pitch answers the question you get in every interview, every client call and every introduction: so, tell me about yourself.

MOST ANSWERS FAIL THE SAME WAY — they are a career history in chronological order, and the listener has stopped listening by the second job. A pitch is not a summary of your past. It is an offer, aimed at the person in front of you.

FOUR PARTS, AND THEY FIT IN SIXTY SECONDS.

ONE, WHO YOU HELP AND WHAT PROBLEM YOU SOLVE. Not your title — the problem. I help small shops stop losing stock they have already paid for says more than I am a bookkeeper.

TWO, PROOF. One specific, checkable thing you have done: a number, a named result, a piece of work they can look at. This is the part that carries the whole pitch, because everyone else is claiming adjectives. Hardworking, passionate and reliable are what somebody says when they have nothing to show; a real example makes those adjectives unnecessary.

THREE, WHY THEM, IN ONE LINE. Something that shows you know who you are talking to — their product, their sector, something they posted. It takes five seconds and it is the difference between a pitch and a broadcast.

FOUR, THE ASK. A specific small next step: may I send a two-page sample, are you the right person to speak to about this, could we talk for fifteen minutes next week. Vague endings — I would love to work with you sometime — put the work of deciding onto them, and nothing happens.

HAVE A TEN-SECOND VERSION TOO, for the times when sixty is all wrong: the problem you solve, one proof, the ask.

DELIVER IT SLIGHTLY SLOWER THAN FEELS RIGHT, because nerves speed everybody up and a rushed pitch sounds anxious. Know the first line and the ask word for word; improvise the middle so it stays alive.

AND SAY IT OUT LOUD BEFORE IT MATTERS. A pitch written and never spoken has never been tested — on paper it reads fine, in the mouth it turns out to be three sentences too long.',
  practice_activity = 'Write your sixty-second pitch in the four parts, then time yourself saying it aloud. If it runs over, cut from the problem statement rather than from the proof. Now make the ten-second version. Then send the sixty-second version as a voice note to somebody whose judgement you trust and ask them one question: after hearing it, what do you think I do? If their answer does not match what you actually offer, the problem is in part one, and that is the part to rewrite.',
  knowledge_check = '[{"question": "Which part of the pitch carries the most weight?", "options": ["Specific, checkable proof of something you have done", "A clear statement of your job title and years of experience", "Adjectives such as hardworking, passionate and reliable", "A chronological summary of your previous roles"], "correct_index": 0}, {"question": "How should the pitch end?", "options": ["With a specific small next step, such as asking to send a sample or book fifteen minutes", "With an open statement that you would love to work together sometime", "With your contact details read out in full", "With a question about the salary or budget"], "correct_index": 0}]'::jsonb
where id = '1711d95a-98d6-450f-a1ee-c81b9adba83e';
